// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"github.com/fsnotify/fsnotify"
	"github.com/schmitthub/clawker/internal/config"
	"sync"
)

// Ensure, that ConfigMock does implement config.Config.
// If this is not the case, regenerate this file with moq.
var _ config.Config = &ConfigMock{}

// ConfigMock is a mock implementation of config.Config.
//
//	func TestSomethingThatUsesConfig(t *testing.T) {
//
//		// make and configure a mocked config.Config
//		mockedConfig := &ConfigMock{
//			BridgePIDFilePathFunc: func(containerID string) (string, error) {
//				panic("mock out the BridgePIDFilePath method")
//			},
//			BridgesSubdirFunc: func() (string, error) {
//				panic("mock out the BridgesSubdir method")
//			},
//			BuildSubdirFunc: func() (string, error) {
//				panic("mock out the BuildSubdir method")
//			},
//			ClawkerIgnoreNameFunc: func() string {
//				panic("mock out the ClawkerIgnoreName method")
//			},
//			ClawkerNetworkFunc: func() string {
//				panic("mock out the ClawkerNetwork method")
//			},
//			ConfigDirEnvVarFunc: func() string {
//				panic("mock out the ConfigDirEnvVar method")
//			},
//			ContainerGIDFunc: func() int {
//				panic("mock out the ContainerGID method")
//			},
//			ContainerUIDFunc: func() int {
//				panic("mock out the ContainerUID method")
//			},
//			DataDirEnvVarFunc: func() string {
//				panic("mock out the DataDirEnvVar method")
//			},
//			DockerfilesSubdirFunc: func() (string, error) {
//				panic("mock out the DockerfilesSubdir method")
//			},
//			DomainFunc: func() string {
//				panic("mock out the Domain method")
//			},
//			EngineLabelPrefixFunc: func() string {
//				panic("mock out the EngineLabelPrefix method")
//			},
//			EngineManagedLabelFunc: func() string {
//				panic("mock out the EngineManagedLabel method")
//			},
//			GetFunc: func(key string) (any, error) {
//				panic("mock out the Get method")
//			},
//			GetProjectIgnoreFileFunc: func() (string, error) {
//				panic("mock out the GetProjectIgnoreFile method")
//			},
//			GetProjectRootFunc: func() (string, error) {
//				panic("mock out the GetProjectRoot method")
//			},
//			GrafanaURLFunc: func(host string, https bool) string {
//				panic("mock out the GrafanaURL method")
//			},
//			HostProxyConfigFunc: func() config.HostProxyConfig {
//				panic("mock out the HostProxyConfig method")
//			},
//			HostProxyLogFilePathFunc: func() (string, error) {
//				panic("mock out the HostProxyLogFilePath method")
//			},
//			HostProxyPIDFilePathFunc: func() (string, error) {
//				panic("mock out the HostProxyPIDFilePath method")
//			},
//			JaegerURLFunc: func(host string, https bool) string {
//				panic("mock out the JaegerURL method")
//			},
//			LabelAgentFunc: func() string {
//				panic("mock out the LabelAgent method")
//			},
//			LabelBaseImageFunc: func() string {
//				panic("mock out the LabelBaseImage method")
//			},
//			LabelCreatedFunc: func() string {
//				panic("mock out the LabelCreated method")
//			},
//			LabelDomainFunc: func() string {
//				panic("mock out the LabelDomain method")
//			},
//			LabelE2ETestFunc: func() string {
//				panic("mock out the LabelE2ETest method")
//			},
//			LabelFlavorFunc: func() string {
//				panic("mock out the LabelFlavor method")
//			},
//			LabelImageFunc: func() string {
//				panic("mock out the LabelImage method")
//			},
//			LabelManagedFunc: func() string {
//				panic("mock out the LabelManaged method")
//			},
//			LabelMonitoringStackFunc: func() string {
//				panic("mock out the LabelMonitoringStack method")
//			},
//			LabelPrefixFunc: func() string {
//				panic("mock out the LabelPrefix method")
//			},
//			LabelProjectFunc: func() string {
//				panic("mock out the LabelProject method")
//			},
//			LabelPurposeFunc: func() string {
//				panic("mock out the LabelPurpose method")
//			},
//			LabelTestFunc: func() string {
//				panic("mock out the LabelTest method")
//			},
//			LabelTestNameFunc: func() string {
//				panic("mock out the LabelTestName method")
//			},
//			LabelVersionFunc: func() string {
//				panic("mock out the LabelVersion method")
//			},
//			LabelWorkdirFunc: func() string {
//				panic("mock out the LabelWorkdir method")
//			},
//			LoggingFunc: func() map[string]any {
//				panic("mock out the Logging method")
//			},
//			LoggingConfigFunc: func() config.LoggingConfig {
//				panic("mock out the LoggingConfig method")
//			},
//			LogsSubdirFunc: func() (string, error) {
//				panic("mock out the LogsSubdir method")
//			},
//			ManagedLabelValueFunc: func() string {
//				panic("mock out the ManagedLabelValue method")
//			},
//			MonitorSubdirFunc: func() (string, error) {
//				panic("mock out the MonitorSubdir method")
//			},
//			MonitoringConfigFunc: func() config.MonitoringConfig {
//				panic("mock out the MonitoringConfig method")
//			},
//			PidsSubdirFunc: func() (string, error) {
//				panic("mock out the PidsSubdir method")
//			},
//			ProjectFunc: func() *config.Project {
//				panic("mock out the Project method")
//			},
//			ProjectConfigFileNameFunc: func() string {
//				panic("mock out the ProjectConfigFileName method")
//			},
//			ProjectRegistryFileNameFunc: func() string {
//				panic("mock out the ProjectRegistryFileName method")
//			},
//			PrometheusURLFunc: func(host string, https bool) string {
//				panic("mock out the PrometheusURL method")
//			},
//			RequiredFirewallDomainsFunc: func() []string {
//				panic("mock out the RequiredFirewallDomains method")
//			},
//			SetFunc: func(key string, value any) error {
//				panic("mock out the Set method")
//			},
//			SettingsFunc: func() config.Settings {
//				panic("mock out the Settings method")
//			},
//			SettingsFileNameFunc: func() string {
//				panic("mock out the SettingsFileName method")
//			},
//			ShareSubdirFunc: func() (string, error) {
//				panic("mock out the ShareSubdir method")
//			},
//			StateDirEnvVarFunc: func() string {
//				panic("mock out the StateDirEnvVar method")
//			},
//			TestRepoDirEnvVarFunc: func() string {
//				panic("mock out the TestRepoDirEnvVar method")
//			},
//			WatchFunc: func(onChange func(fsnotify.Event)) error {
//				panic("mock out the Watch method")
//			},
//			WorktreesSubdirFunc: func() (string, error) {
//				panic("mock out the WorktreesSubdir method")
//			},
//			WriteFunc: func(opts config.WriteOptions) error {
//				panic("mock out the Write method")
//			},
//		}
//
//		// use mockedConfig in code that requires config.Config
//		// and then make assertions.
//
//	}
type ConfigMock struct {
	// BridgePIDFilePathFunc mocks the BridgePIDFilePath method.
	BridgePIDFilePathFunc func(containerID string) (string, error)

	// BridgesSubdirFunc mocks the BridgesSubdir method.
	BridgesSubdirFunc func() (string, error)

	// BuildSubdirFunc mocks the BuildSubdir method.
	BuildSubdirFunc func() (string, error)

	// ClawkerIgnoreNameFunc mocks the ClawkerIgnoreName method.
	ClawkerIgnoreNameFunc func() string

	// ClawkerNetworkFunc mocks the ClawkerNetwork method.
	ClawkerNetworkFunc func() string

	// ConfigDirEnvVarFunc mocks the ConfigDirEnvVar method.
	ConfigDirEnvVarFunc func() string

	// ContainerGIDFunc mocks the ContainerGID method.
	ContainerGIDFunc func() int

	// ContainerUIDFunc mocks the ContainerUID method.
	ContainerUIDFunc func() int

	// DataDirEnvVarFunc mocks the DataDirEnvVar method.
	DataDirEnvVarFunc func() string

	// DockerfilesSubdirFunc mocks the DockerfilesSubdir method.
	DockerfilesSubdirFunc func() (string, error)

	// DomainFunc mocks the Domain method.
	DomainFunc func() string

	// EngineLabelPrefixFunc mocks the EngineLabelPrefix method.
	EngineLabelPrefixFunc func() string

	// EngineManagedLabelFunc mocks the EngineManagedLabel method.
	EngineManagedLabelFunc func() string

	// GetFunc mocks the Get method.
	GetFunc func(key string) (any, error)

	// GetProjectIgnoreFileFunc mocks the GetProjectIgnoreFile method.
	GetProjectIgnoreFileFunc func() (string, error)

	// GetProjectRootFunc mocks the GetProjectRoot method.
	GetProjectRootFunc func() (string, error)

	// GrafanaURLFunc mocks the GrafanaURL method.
	GrafanaURLFunc func(host string, https bool) string

	// HostProxyConfigFunc mocks the HostProxyConfig method.
	HostProxyConfigFunc func() config.HostProxyConfig

	// HostProxyLogFilePathFunc mocks the HostProxyLogFilePath method.
	HostProxyLogFilePathFunc func() (string, error)

	// HostProxyPIDFilePathFunc mocks the HostProxyPIDFilePath method.
	HostProxyPIDFilePathFunc func() (string, error)

	// JaegerURLFunc mocks the JaegerURL method.
	JaegerURLFunc func(host string, https bool) string

	// LabelAgentFunc mocks the LabelAgent method.
	LabelAgentFunc func() string

	// LabelBaseImageFunc mocks the LabelBaseImage method.
	LabelBaseImageFunc func() string

	// LabelCreatedFunc mocks the LabelCreated method.
	LabelCreatedFunc func() string

	// LabelDomainFunc mocks the LabelDomain method.
	LabelDomainFunc func() string

	// LabelE2ETestFunc mocks the LabelE2ETest method.
	LabelE2ETestFunc func() string

	// LabelFlavorFunc mocks the LabelFlavor method.
	LabelFlavorFunc func() string

	// LabelImageFunc mocks the LabelImage method.
	LabelImageFunc func() string

	// LabelManagedFunc mocks the LabelManaged method.
	LabelManagedFunc func() string

	// LabelMonitoringStackFunc mocks the LabelMonitoringStack method.
	LabelMonitoringStackFunc func() string

	// LabelPrefixFunc mocks the LabelPrefix method.
	LabelPrefixFunc func() string

	// LabelProjectFunc mocks the LabelProject method.
	LabelProjectFunc func() string

	// LabelPurposeFunc mocks the LabelPurpose method.
	LabelPurposeFunc func() string

	// LabelTestFunc mocks the LabelTest method.
	LabelTestFunc func() string

	// LabelTestNameFunc mocks the LabelTestName method.
	LabelTestNameFunc func() string

	// LabelVersionFunc mocks the LabelVersion method.
	LabelVersionFunc func() string

	// LabelWorkdirFunc mocks the LabelWorkdir method.
	LabelWorkdirFunc func() string

	// LoggingFunc mocks the Logging method.
	LoggingFunc func() map[string]any

	// LoggingConfigFunc mocks the LoggingConfig method.
	LoggingConfigFunc func() config.LoggingConfig

	// LogsSubdirFunc mocks the LogsSubdir method.
	LogsSubdirFunc func() (string, error)

	// ManagedLabelValueFunc mocks the ManagedLabelValue method.
	ManagedLabelValueFunc func() string

	// MonitorSubdirFunc mocks the MonitorSubdir method.
	MonitorSubdirFunc func() (string, error)

	// MonitoringConfigFunc mocks the MonitoringConfig method.
	MonitoringConfigFunc func() config.MonitoringConfig

	// PidsSubdirFunc mocks the PidsSubdir method.
	PidsSubdirFunc func() (string, error)

	// ProjectFunc mocks the Project method.
	ProjectFunc func() *config.Project

	// ProjectConfigFileNameFunc mocks the ProjectConfigFileName method.
	ProjectConfigFileNameFunc func() string

	// ProjectRegistryFileNameFunc mocks the ProjectRegistryFileName method.
	ProjectRegistryFileNameFunc func() string

	// PrometheusURLFunc mocks the PrometheusURL method.
	PrometheusURLFunc func(host string, https bool) string

	// RequiredFirewallDomainsFunc mocks the RequiredFirewallDomains method.
	RequiredFirewallDomainsFunc func() []string

	// SetFunc mocks the Set method.
	SetFunc func(key string, value any) error

	// SettingsFunc mocks the Settings method.
	SettingsFunc func() config.Settings

	// SettingsFileNameFunc mocks the SettingsFileName method.
	SettingsFileNameFunc func() string

	// ShareSubdirFunc mocks the ShareSubdir method.
	ShareSubdirFunc func() (string, error)

	// StateDirEnvVarFunc mocks the StateDirEnvVar method.
	StateDirEnvVarFunc func() string

	// TestRepoDirEnvVarFunc mocks the TestRepoDirEnvVar method.
	TestRepoDirEnvVarFunc func() string

	// WatchFunc mocks the Watch method.
	WatchFunc func(onChange func(fsnotify.Event)) error

	// WorktreesSubdirFunc mocks the WorktreesSubdir method.
	WorktreesSubdirFunc func() (string, error)

	// WriteFunc mocks the Write method.
	WriteFunc func(opts config.WriteOptions) error

	// calls tracks calls to the methods.
	calls struct {
		// BridgePIDFilePath holds details about calls to the BridgePIDFilePath method.
		BridgePIDFilePath []struct {
			// ContainerID is the containerID argument value.
			ContainerID string
		}
		// BridgesSubdir holds details about calls to the BridgesSubdir method.
		BridgesSubdir []struct {
		}
		// BuildSubdir holds details about calls to the BuildSubdir method.
		BuildSubdir []struct {
		}
		// ClawkerIgnoreName holds details about calls to the ClawkerIgnoreName method.
		ClawkerIgnoreName []struct {
		}
		// ClawkerNetwork holds details about calls to the ClawkerNetwork method.
		ClawkerNetwork []struct {
		}
		// ConfigDirEnvVar holds details about calls to the ConfigDirEnvVar method.
		ConfigDirEnvVar []struct {
		}
		// ContainerGID holds details about calls to the ContainerGID method.
		ContainerGID []struct {
		}
		// ContainerUID holds details about calls to the ContainerUID method.
		ContainerUID []struct {
		}
		// DataDirEnvVar holds details about calls to the DataDirEnvVar method.
		DataDirEnvVar []struct {
		}
		// DockerfilesSubdir holds details about calls to the DockerfilesSubdir method.
		DockerfilesSubdir []struct {
		}
		// Domain holds details about calls to the Domain method.
		Domain []struct {
		}
		// EngineLabelPrefix holds details about calls to the EngineLabelPrefix method.
		EngineLabelPrefix []struct {
		}
		// EngineManagedLabel holds details about calls to the EngineManagedLabel method.
		EngineManagedLabel []struct {
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// Key is the key argument value.
			Key string
		}
		// GetProjectIgnoreFile holds details about calls to the GetProjectIgnoreFile method.
		GetProjectIgnoreFile []struct {
		}
		// GetProjectRoot holds details about calls to the GetProjectRoot method.
		GetProjectRoot []struct {
		}
		// GrafanaURL holds details about calls to the GrafanaURL method.
		GrafanaURL []struct {
			// Host is the host argument value.
			Host string
			// HTTPS is the https argument value.
			HTTPS bool
		}
		// HostProxyConfig holds details about calls to the HostProxyConfig method.
		HostProxyConfig []struct {
		}
		// HostProxyLogFilePath holds details about calls to the HostProxyLogFilePath method.
		HostProxyLogFilePath []struct {
		}
		// HostProxyPIDFilePath holds details about calls to the HostProxyPIDFilePath method.
		HostProxyPIDFilePath []struct {
		}
		// JaegerURL holds details about calls to the JaegerURL method.
		JaegerURL []struct {
			// Host is the host argument value.
			Host string
			// HTTPS is the https argument value.
			HTTPS bool
		}
		// LabelAgent holds details about calls to the LabelAgent method.
		LabelAgent []struct {
		}
		// LabelBaseImage holds details about calls to the LabelBaseImage method.
		LabelBaseImage []struct {
		}
		// LabelCreated holds details about calls to the LabelCreated method.
		LabelCreated []struct {
		}
		// LabelDomain holds details about calls to the LabelDomain method.
		LabelDomain []struct {
		}
		// LabelE2ETest holds details about calls to the LabelE2ETest method.
		LabelE2ETest []struct {
		}
		// LabelFlavor holds details about calls to the LabelFlavor method.
		LabelFlavor []struct {
		}
		// LabelImage holds details about calls to the LabelImage method.
		LabelImage []struct {
		}
		// LabelManaged holds details about calls to the LabelManaged method.
		LabelManaged []struct {
		}
		// LabelMonitoringStack holds details about calls to the LabelMonitoringStack method.
		LabelMonitoringStack []struct {
		}
		// LabelPrefix holds details about calls to the LabelPrefix method.
		LabelPrefix []struct {
		}
		// LabelProject holds details about calls to the LabelProject method.
		LabelProject []struct {
		}
		// LabelPurpose holds details about calls to the LabelPurpose method.
		LabelPurpose []struct {
		}
		// LabelTest holds details about calls to the LabelTest method.
		LabelTest []struct {
		}
		// LabelTestName holds details about calls to the LabelTestName method.
		LabelTestName []struct {
		}
		// LabelVersion holds details about calls to the LabelVersion method.
		LabelVersion []struct {
		}
		// LabelWorkdir holds details about calls to the LabelWorkdir method.
		LabelWorkdir []struct {
		}
		// Logging holds details about calls to the Logging method.
		Logging []struct {
		}
		// LoggingConfig holds details about calls to the LoggingConfig method.
		LoggingConfig []struct {
		}
		// LogsSubdir holds details about calls to the LogsSubdir method.
		LogsSubdir []struct {
		}
		// ManagedLabelValue holds details about calls to the ManagedLabelValue method.
		ManagedLabelValue []struct {
		}
		// MonitorSubdir holds details about calls to the MonitorSubdir method.
		MonitorSubdir []struct {
		}
		// MonitoringConfig holds details about calls to the MonitoringConfig method.
		MonitoringConfig []struct {
		}
		// PidsSubdir holds details about calls to the PidsSubdir method.
		PidsSubdir []struct {
		}
		// Project holds details about calls to the Project method.
		Project []struct {
		}
		// ProjectConfigFileName holds details about calls to the ProjectConfigFileName method.
		ProjectConfigFileName []struct {
		}
		// ProjectRegistryFileName holds details about calls to the ProjectRegistryFileName method.
		ProjectRegistryFileName []struct {
		}
		// PrometheusURL holds details about calls to the PrometheusURL method.
		PrometheusURL []struct {
			// Host is the host argument value.
			Host string
			// HTTPS is the https argument value.
			HTTPS bool
		}
		// RequiredFirewallDomains holds details about calls to the RequiredFirewallDomains method.
		RequiredFirewallDomains []struct {
		}
		// Set holds details about calls to the Set method.
		Set []struct {
			// Key is the key argument value.
			Key string
			// Value is the value argument value.
			Value any
		}
		// Settings holds details about calls to the Settings method.
		Settings []struct {
		}
		// SettingsFileName holds details about calls to the SettingsFileName method.
		SettingsFileName []struct {
		}
		// ShareSubdir holds details about calls to the ShareSubdir method.
		ShareSubdir []struct {
		}
		// StateDirEnvVar holds details about calls to the StateDirEnvVar method.
		StateDirEnvVar []struct {
		}
		// TestRepoDirEnvVar holds details about calls to the TestRepoDirEnvVar method.
		TestRepoDirEnvVar []struct {
		}
		// Watch holds details about calls to the Watch method.
		Watch []struct {
			// OnChange is the onChange argument value.
			OnChange func(fsnotify.Event)
		}
		// WorktreesSubdir holds details about calls to the WorktreesSubdir method.
		WorktreesSubdir []struct {
		}
		// Write holds details about calls to the Write method.
		Write []struct {
			// Opts is the opts argument value.
			Opts config.WriteOptions
		}
	}
	lockBridgePIDFilePath       sync.RWMutex
	lockBridgesSubdir           sync.RWMutex
	lockBuildSubdir             sync.RWMutex
	lockClawkerIgnoreName       sync.RWMutex
	lockClawkerNetwork          sync.RWMutex
	lockConfigDirEnvVar         sync.RWMutex
	lockContainerGID            sync.RWMutex
	lockContainerUID            sync.RWMutex
	lockDataDirEnvVar           sync.RWMutex
	lockDockerfilesSubdir       sync.RWMutex
	lockDomain                  sync.RWMutex
	lockEngineLabelPrefix       sync.RWMutex
	lockEngineManagedLabel      sync.RWMutex
	lockGet                     sync.RWMutex
	lockGetProjectIgnoreFile    sync.RWMutex
	lockGetProjectRoot          sync.RWMutex
	lockGrafanaURL              sync.RWMutex
	lockHostProxyConfig         sync.RWMutex
	lockHostProxyLogFilePath    sync.RWMutex
	lockHostProxyPIDFilePath    sync.RWMutex
	lockJaegerURL               sync.RWMutex
	lockLabelAgent              sync.RWMutex
	lockLabelBaseImage          sync.RWMutex
	lockLabelCreated            sync.RWMutex
	lockLabelDomain             sync.RWMutex
	lockLabelE2ETest            sync.RWMutex
	lockLabelFlavor             sync.RWMutex
	lockLabelImage              sync.RWMutex
	lockLabelManaged            sync.RWMutex
	lockLabelMonitoringStack    sync.RWMutex
	lockLabelPrefix             sync.RWMutex
	lockLabelProject            sync.RWMutex
	lockLabelPurpose            sync.RWMutex
	lockLabelTest               sync.RWMutex
	lockLabelTestName           sync.RWMutex
	lockLabelVersion            sync.RWMutex
	lockLabelWorkdir            sync.RWMutex
	lockLogging                 sync.RWMutex
	lockLoggingConfig           sync.RWMutex
	lockLogsSubdir              sync.RWMutex
	lockManagedLabelValue       sync.RWMutex
	lockMonitorSubdir           sync.RWMutex
	lockMonitoringConfig        sync.RWMutex
	lockPidsSubdir              sync.RWMutex
	lockProject                 sync.RWMutex
	lockProjectConfigFileName   sync.RWMutex
	lockProjectRegistryFileName sync.RWMutex
	lockPrometheusURL           sync.RWMutex
	lockRequiredFirewallDomains sync.RWMutex
	lockSet                     sync.RWMutex
	lockSettings                sync.RWMutex
	lockSettingsFileName        sync.RWMutex
	lockShareSubdir             sync.RWMutex
	lockStateDirEnvVar          sync.RWMutex
	lockTestRepoDirEnvVar       sync.RWMutex
	lockWatch                   sync.RWMutex
	lockWorktreesSubdir         sync.RWMutex
	lockWrite                   sync.RWMutex
}

// BridgePIDFilePath calls BridgePIDFilePathFunc.
func (mock *ConfigMock) BridgePIDFilePath(containerID string) (string, error) {
	if mock.BridgePIDFilePathFunc == nil {
		panic("ConfigMock.BridgePIDFilePathFunc: method is nil but Config.BridgePIDFilePath was just called")
	}
	callInfo := struct {
		ContainerID string
	}{
		ContainerID: containerID,
	}
	mock.lockBridgePIDFilePath.Lock()
	mock.calls.BridgePIDFilePath = append(mock.calls.BridgePIDFilePath, callInfo)
	mock.lockBridgePIDFilePath.Unlock()
	return mock.BridgePIDFilePathFunc(containerID)
}

// BridgePIDFilePathCalls gets all the calls that were made to BridgePIDFilePath.
// Check the length with:
//
//	len(mockedConfig.BridgePIDFilePathCalls())
func (mock *ConfigMock) BridgePIDFilePathCalls() []struct {
	ContainerID string
} {
	var calls []struct {
		ContainerID string
	}
	mock.lockBridgePIDFilePath.RLock()
	calls = mock.calls.BridgePIDFilePath
	mock.lockBridgePIDFilePath.RUnlock()
	return calls
}

// BridgesSubdir calls BridgesSubdirFunc.
func (mock *ConfigMock) BridgesSubdir() (string, error) {
	if mock.BridgesSubdirFunc == nil {
		panic("ConfigMock.BridgesSubdirFunc: method is nil but Config.BridgesSubdir was just called")
	}
	callInfo := struct {
	}{}
	mock.lockBridgesSubdir.Lock()
	mock.calls.BridgesSubdir = append(mock.calls.BridgesSubdir, callInfo)
	mock.lockBridgesSubdir.Unlock()
	return mock.BridgesSubdirFunc()
}

// BridgesSubdirCalls gets all the calls that were made to BridgesSubdir.
// Check the length with:
//
//	len(mockedConfig.BridgesSubdirCalls())
func (mock *ConfigMock) BridgesSubdirCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockBridgesSubdir.RLock()
	calls = mock.calls.BridgesSubdir
	mock.lockBridgesSubdir.RUnlock()
	return calls
}

// BuildSubdir calls BuildSubdirFunc.
func (mock *ConfigMock) BuildSubdir() (string, error) {
	if mock.BuildSubdirFunc == nil {
		panic("ConfigMock.BuildSubdirFunc: method is nil but Config.BuildSubdir was just called")
	}
	callInfo := struct {
	}{}
	mock.lockBuildSubdir.Lock()
	mock.calls.BuildSubdir = append(mock.calls.BuildSubdir, callInfo)
	mock.lockBuildSubdir.Unlock()
	return mock.BuildSubdirFunc()
}

// BuildSubdirCalls gets all the calls that were made to BuildSubdir.
// Check the length with:
//
//	len(mockedConfig.BuildSubdirCalls())
func (mock *ConfigMock) BuildSubdirCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockBuildSubdir.RLock()
	calls = mock.calls.BuildSubdir
	mock.lockBuildSubdir.RUnlock()
	return calls
}

// ClawkerIgnoreName calls ClawkerIgnoreNameFunc.
func (mock *ConfigMock) ClawkerIgnoreName() string {
	if mock.ClawkerIgnoreNameFunc == nil {
		panic("ConfigMock.ClawkerIgnoreNameFunc: method is nil but Config.ClawkerIgnoreName was just called")
	}
	callInfo := struct {
	}{}
	mock.lockClawkerIgnoreName.Lock()
	mock.calls.ClawkerIgnoreName = append(mock.calls.ClawkerIgnoreName, callInfo)
	mock.lockClawkerIgnoreName.Unlock()
	return mock.ClawkerIgnoreNameFunc()
}

// ClawkerIgnoreNameCalls gets all the calls that were made to ClawkerIgnoreName.
// Check the length with:
//
//	len(mockedConfig.ClawkerIgnoreNameCalls())
func (mock *ConfigMock) ClawkerIgnoreNameCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockClawkerIgnoreName.RLock()
	calls = mock.calls.ClawkerIgnoreName
	mock.lockClawkerIgnoreName.RUnlock()
	return calls
}

// ClawkerNetwork calls ClawkerNetworkFunc.
func (mock *ConfigMock) ClawkerNetwork() string {
	if mock.ClawkerNetworkFunc == nil {
		panic("ConfigMock.ClawkerNetworkFunc: method is nil but Config.ClawkerNetwork was just called")
	}
	callInfo := struct {
	}{}
	mock.lockClawkerNetwork.Lock()
	mock.calls.ClawkerNetwork = append(mock.calls.ClawkerNetwork, callInfo)
	mock.lockClawkerNetwork.Unlock()
	return mock.ClawkerNetworkFunc()
}

// ClawkerNetworkCalls gets all the calls that were made to ClawkerNetwork.
// Check the length with:
//
//	len(mockedConfig.ClawkerNetworkCalls())
func (mock *ConfigMock) ClawkerNetworkCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockClawkerNetwork.RLock()
	calls = mock.calls.ClawkerNetwork
	mock.lockClawkerNetwork.RUnlock()
	return calls
}

// ConfigDirEnvVar calls ConfigDirEnvVarFunc.
func (mock *ConfigMock) ConfigDirEnvVar() string {
	if mock.ConfigDirEnvVarFunc == nil {
		panic("ConfigMock.ConfigDirEnvVarFunc: method is nil but Config.ConfigDirEnvVar was just called")
	}
	callInfo := struct {
	}{}
	mock.lockConfigDirEnvVar.Lock()
	mock.calls.ConfigDirEnvVar = append(mock.calls.ConfigDirEnvVar, callInfo)
	mock.lockConfigDirEnvVar.Unlock()
	return mock.ConfigDirEnvVarFunc()
}

// ConfigDirEnvVarCalls gets all the calls that were made to ConfigDirEnvVar.
// Check the length with:
//
//	len(mockedConfig.ConfigDirEnvVarCalls())
func (mock *ConfigMock) ConfigDirEnvVarCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockConfigDirEnvVar.RLock()
	calls = mock.calls.ConfigDirEnvVar
	mock.lockConfigDirEnvVar.RUnlock()
	return calls
}

// ContainerGID calls ContainerGIDFunc.
func (mock *ConfigMock) ContainerGID() int {
	if mock.ContainerGIDFunc == nil {
		panic("ConfigMock.ContainerGIDFunc: method is nil but Config.ContainerGID was just called")
	}
	callInfo := struct {
	}{}
	mock.lockContainerGID.Lock()
	mock.calls.ContainerGID = append(mock.calls.ContainerGID, callInfo)
	mock.lockContainerGID.Unlock()
	return mock.ContainerGIDFunc()
}

// ContainerGIDCalls gets all the calls that were made to ContainerGID.
// Check the length with:
//
//	len(mockedConfig.ContainerGIDCalls())
func (mock *ConfigMock) ContainerGIDCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockContainerGID.RLock()
	calls = mock.calls.ContainerGID
	mock.lockContainerGID.RUnlock()
	return calls
}

// ContainerUID calls ContainerUIDFunc.
func (mock *ConfigMock) ContainerUID() int {
	if mock.ContainerUIDFunc == nil {
		panic("ConfigMock.ContainerUIDFunc: method is nil but Config.ContainerUID was just called")
	}
	callInfo := struct {
	}{}
	mock.lockContainerUID.Lock()
	mock.calls.ContainerUID = append(mock.calls.ContainerUID, callInfo)
	mock.lockContainerUID.Unlock()
	return mock.ContainerUIDFunc()
}

// ContainerUIDCalls gets all the calls that were made to ContainerUID.
// Check the length with:
//
//	len(mockedConfig.ContainerUIDCalls())
func (mock *ConfigMock) ContainerUIDCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockContainerUID.RLock()
	calls = mock.calls.ContainerUID
	mock.lockContainerUID.RUnlock()
	return calls
}

// DataDirEnvVar calls DataDirEnvVarFunc.
func (mock *ConfigMock) DataDirEnvVar() string {
	if mock.DataDirEnvVarFunc == nil {
		panic("ConfigMock.DataDirEnvVarFunc: method is nil but Config.DataDirEnvVar was just called")
	}
	callInfo := struct {
	}{}
	mock.lockDataDirEnvVar.Lock()
	mock.calls.DataDirEnvVar = append(mock.calls.DataDirEnvVar, callInfo)
	mock.lockDataDirEnvVar.Unlock()
	return mock.DataDirEnvVarFunc()
}

// DataDirEnvVarCalls gets all the calls that were made to DataDirEnvVar.
// Check the length with:
//
//	len(mockedConfig.DataDirEnvVarCalls())
func (mock *ConfigMock) DataDirEnvVarCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockDataDirEnvVar.RLock()
	calls = mock.calls.DataDirEnvVar
	mock.lockDataDirEnvVar.RUnlock()
	return calls
}

// DockerfilesSubdir calls DockerfilesSubdirFunc.
func (mock *ConfigMock) DockerfilesSubdir() (string, error) {
	if mock.DockerfilesSubdirFunc == nil {
		panic("ConfigMock.DockerfilesSubdirFunc: method is nil but Config.DockerfilesSubdir was just called")
	}
	callInfo := struct {
	}{}
	mock.lockDockerfilesSubdir.Lock()
	mock.calls.DockerfilesSubdir = append(mock.calls.DockerfilesSubdir, callInfo)
	mock.lockDockerfilesSubdir.Unlock()
	return mock.DockerfilesSubdirFunc()
}

// DockerfilesSubdirCalls gets all the calls that were made to DockerfilesSubdir.
// Check the length with:
//
//	len(mockedConfig.DockerfilesSubdirCalls())
func (mock *ConfigMock) DockerfilesSubdirCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockDockerfilesSubdir.RLock()
	calls = mock.calls.DockerfilesSubdir
	mock.lockDockerfilesSubdir.RUnlock()
	return calls
}

// Domain calls DomainFunc.
func (mock *ConfigMock) Domain() string {
	if mock.DomainFunc == nil {
		panic("ConfigMock.DomainFunc: method is nil but Config.Domain was just called")
	}
	callInfo := struct {
	}{}
	mock.lockDomain.Lock()
	mock.calls.Domain = append(mock.calls.Domain, callInfo)
	mock.lockDomain.Unlock()
	return mock.DomainFunc()
}

// DomainCalls gets all the calls that were made to Domain.
// Check the length with:
//
//	len(mockedConfig.DomainCalls())
func (mock *ConfigMock) DomainCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockDomain.RLock()
	calls = mock.calls.Domain
	mock.lockDomain.RUnlock()
	return calls
}

// EngineLabelPrefix calls EngineLabelPrefixFunc.
func (mock *ConfigMock) EngineLabelPrefix() string {
	if mock.EngineLabelPrefixFunc == nil {
		panic("ConfigMock.EngineLabelPrefixFunc: method is nil but Config.EngineLabelPrefix was just called")
	}
	callInfo := struct {
	}{}
	mock.lockEngineLabelPrefix.Lock()
	mock.calls.EngineLabelPrefix = append(mock.calls.EngineLabelPrefix, callInfo)
	mock.lockEngineLabelPrefix.Unlock()
	return mock.EngineLabelPrefixFunc()
}

// EngineLabelPrefixCalls gets all the calls that were made to EngineLabelPrefix.
// Check the length with:
//
//	len(mockedConfig.EngineLabelPrefixCalls())
func (mock *ConfigMock) EngineLabelPrefixCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockEngineLabelPrefix.RLock()
	calls = mock.calls.EngineLabelPrefix
	mock.lockEngineLabelPrefix.RUnlock()
	return calls
}

// EngineManagedLabel calls EngineManagedLabelFunc.
func (mock *ConfigMock) EngineManagedLabel() string {
	if mock.EngineManagedLabelFunc == nil {
		panic("ConfigMock.EngineManagedLabelFunc: method is nil but Config.EngineManagedLabel was just called")
	}
	callInfo := struct {
	}{}
	mock.lockEngineManagedLabel.Lock()
	mock.calls.EngineManagedLabel = append(mock.calls.EngineManagedLabel, callInfo)
	mock.lockEngineManagedLabel.Unlock()
	return mock.EngineManagedLabelFunc()
}

// EngineManagedLabelCalls gets all the calls that were made to EngineManagedLabel.
// Check the length with:
//
//	len(mockedConfig.EngineManagedLabelCalls())
func (mock *ConfigMock) EngineManagedLabelCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockEngineManagedLabel.RLock()
	calls = mock.calls.EngineManagedLabel
	mock.lockEngineManagedLabel.RUnlock()
	return calls
}

// Get calls GetFunc.
func (mock *ConfigMock) Get(key string) (any, error) {
	if mock.GetFunc == nil {
		panic("ConfigMock.GetFunc: method is nil but Config.Get was just called")
	}
	callInfo := struct {
		Key string
	}{
		Key: key,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(key)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedConfig.GetCalls())
func (mock *ConfigMock) GetCalls() []struct {
	Key string
} {
	var calls []struct {
		Key string
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// GetProjectIgnoreFile calls GetProjectIgnoreFileFunc.
func (mock *ConfigMock) GetProjectIgnoreFile() (string, error) {
	if mock.GetProjectIgnoreFileFunc == nil {
		panic("ConfigMock.GetProjectIgnoreFileFunc: method is nil but Config.GetProjectIgnoreFile was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetProjectIgnoreFile.Lock()
	mock.calls.GetProjectIgnoreFile = append(mock.calls.GetProjectIgnoreFile, callInfo)
	mock.lockGetProjectIgnoreFile.Unlock()
	return mock.GetProjectIgnoreFileFunc()
}

// GetProjectIgnoreFileCalls gets all the calls that were made to GetProjectIgnoreFile.
// Check the length with:
//
//	len(mockedConfig.GetProjectIgnoreFileCalls())
func (mock *ConfigMock) GetProjectIgnoreFileCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetProjectIgnoreFile.RLock()
	calls = mock.calls.GetProjectIgnoreFile
	mock.lockGetProjectIgnoreFile.RUnlock()
	return calls
}

// GetProjectRoot calls GetProjectRootFunc.
func (mock *ConfigMock) GetProjectRoot() (string, error) {
	if mock.GetProjectRootFunc == nil {
		panic("ConfigMock.GetProjectRootFunc: method is nil but Config.GetProjectRoot was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetProjectRoot.Lock()
	mock.calls.GetProjectRoot = append(mock.calls.GetProjectRoot, callInfo)
	mock.lockGetProjectRoot.Unlock()
	return mock.GetProjectRootFunc()
}

// GetProjectRootCalls gets all the calls that were made to GetProjectRoot.
// Check the length with:
//
//	len(mockedConfig.GetProjectRootCalls())
func (mock *ConfigMock) GetProjectRootCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetProjectRoot.RLock()
	calls = mock.calls.GetProjectRoot
	mock.lockGetProjectRoot.RUnlock()
	return calls
}

// GrafanaURL calls GrafanaURLFunc.
func (mock *ConfigMock) GrafanaURL(host string, https bool) string {
	if mock.GrafanaURLFunc == nil {
		panic("ConfigMock.GrafanaURLFunc: method is nil but Config.GrafanaURL was just called")
	}
	callInfo := struct {
		Host  string
		HTTPS bool
	}{
		Host:  host,
		HTTPS: https,
	}
	mock.lockGrafanaURL.Lock()
	mock.calls.GrafanaURL = append(mock.calls.GrafanaURL, callInfo)
	mock.lockGrafanaURL.Unlock()
	return mock.GrafanaURLFunc(host, https)
}

// GrafanaURLCalls gets all the calls that were made to GrafanaURL.
// Check the length with:
//
//	len(mockedConfig.GrafanaURLCalls())
func (mock *ConfigMock) GrafanaURLCalls() []struct {
	Host  string
	HTTPS bool
} {
	var calls []struct {
		Host  string
		HTTPS bool
	}
	mock.lockGrafanaURL.RLock()
	calls = mock.calls.GrafanaURL
	mock.lockGrafanaURL.RUnlock()
	return calls
}

// HostProxyConfig calls HostProxyConfigFunc.
func (mock *ConfigMock) HostProxyConfig() config.HostProxyConfig {
	if mock.HostProxyConfigFunc == nil {
		panic("ConfigMock.HostProxyConfigFunc: method is nil but Config.HostProxyConfig was just called")
	}
	callInfo := struct {
	}{}
	mock.lockHostProxyConfig.Lock()
	mock.calls.HostProxyConfig = append(mock.calls.HostProxyConfig, callInfo)
	mock.lockHostProxyConfig.Unlock()
	return mock.HostProxyConfigFunc()
}

// HostProxyConfigCalls gets all the calls that were made to HostProxyConfig.
// Check the length with:
//
//	len(mockedConfig.HostProxyConfigCalls())
func (mock *ConfigMock) HostProxyConfigCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockHostProxyConfig.RLock()
	calls = mock.calls.HostProxyConfig
	mock.lockHostProxyConfig.RUnlock()
	return calls
}

// HostProxyLogFilePath calls HostProxyLogFilePathFunc.
func (mock *ConfigMock) HostProxyLogFilePath() (string, error) {
	if mock.HostProxyLogFilePathFunc == nil {
		panic("ConfigMock.HostProxyLogFilePathFunc: method is nil but Config.HostProxyLogFilePath was just called")
	}
	callInfo := struct {
	}{}
	mock.lockHostProxyLogFilePath.Lock()
	mock.calls.HostProxyLogFilePath = append(mock.calls.HostProxyLogFilePath, callInfo)
	mock.lockHostProxyLogFilePath.Unlock()
	return mock.HostProxyLogFilePathFunc()
}

// HostProxyLogFilePathCalls gets all the calls that were made to HostProxyLogFilePath.
// Check the length with:
//
//	len(mockedConfig.HostProxyLogFilePathCalls())
func (mock *ConfigMock) HostProxyLogFilePathCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockHostProxyLogFilePath.RLock()
	calls = mock.calls.HostProxyLogFilePath
	mock.lockHostProxyLogFilePath.RUnlock()
	return calls
}

// HostProxyPIDFilePath calls HostProxyPIDFilePathFunc.
func (mock *ConfigMock) HostProxyPIDFilePath() (string, error) {
	if mock.HostProxyPIDFilePathFunc == nil {
		panic("ConfigMock.HostProxyPIDFilePathFunc: method is nil but Config.HostProxyPIDFilePath was just called")
	}
	callInfo := struct {
	}{}
	mock.lockHostProxyPIDFilePath.Lock()
	mock.calls.HostProxyPIDFilePath = append(mock.calls.HostProxyPIDFilePath, callInfo)
	mock.lockHostProxyPIDFilePath.Unlock()
	return mock.HostProxyPIDFilePathFunc()
}

// HostProxyPIDFilePathCalls gets all the calls that were made to HostProxyPIDFilePath.
// Check the length with:
//
//	len(mockedConfig.HostProxyPIDFilePathCalls())
func (mock *ConfigMock) HostProxyPIDFilePathCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockHostProxyPIDFilePath.RLock()
	calls = mock.calls.HostProxyPIDFilePath
	mock.lockHostProxyPIDFilePath.RUnlock()
	return calls
}

// JaegerURL calls JaegerURLFunc.
func (mock *ConfigMock) JaegerURL(host string, https bool) string {
	if mock.JaegerURLFunc == nil {
		panic("ConfigMock.JaegerURLFunc: method is nil but Config.JaegerURL was just called")
	}
	callInfo := struct {
		Host  string
		HTTPS bool
	}{
		Host:  host,
		HTTPS: https,
	}
	mock.lockJaegerURL.Lock()
	mock.calls.JaegerURL = append(mock.calls.JaegerURL, callInfo)
	mock.lockJaegerURL.Unlock()
	return mock.JaegerURLFunc(host, https)
}

// JaegerURLCalls gets all the calls that were made to JaegerURL.
// Check the length with:
//
//	len(mockedConfig.JaegerURLCalls())
func (mock *ConfigMock) JaegerURLCalls() []struct {
	Host  string
	HTTPS bool
} {
	var calls []struct {
		Host  string
		HTTPS bool
	}
	mock.lockJaegerURL.RLock()
	calls = mock.calls.JaegerURL
	mock.lockJaegerURL.RUnlock()
	return calls
}

// LabelAgent calls LabelAgentFunc.
func (mock *ConfigMock) LabelAgent() string {
	if mock.LabelAgentFunc == nil {
		panic("ConfigMock.LabelAgentFunc: method is nil but Config.LabelAgent was just called")
	}
	callInfo := struct {
	}{}
	mock.lockLabelAgent.Lock()
	mock.calls.LabelAgent = append(mock.calls.LabelAgent, callInfo)
	mock.lockLabelAgent.Unlock()
	return mock.LabelAgentFunc()
}

// LabelAgentCalls gets all the calls that were made to LabelAgent.
// Check the length with:
//
//	len(mockedConfig.LabelAgentCalls())
func (mock *ConfigMock) LabelAgentCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockLabelAgent.RLock()
	calls = mock.calls.LabelAgent
	mock.lockLabelAgent.RUnlock()
	return calls
}

// LabelBaseImage calls LabelBaseImageFunc.
func (mock *ConfigMock) LabelBaseImage() string {
	if mock.LabelBaseImageFunc == nil {
		panic("ConfigMock.LabelBaseImageFunc: method is nil but Config.LabelBaseImage was just called")
	}
	callInfo := struct {
	}{}
	mock.lockLabelBaseImage.Lock()
	mock.calls.LabelBaseImage = append(mock.calls.LabelBaseImage, callInfo)
	mock.lockLabelBaseImage.Unlock()
	return mock.LabelBaseImageFunc()
}

// LabelBaseImageCalls gets all the calls that were made to LabelBaseImage.
// Check the length with:
//
//	len(mockedConfig.LabelBaseImageCalls())
func (mock *ConfigMock) LabelBaseImageCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockLabelBaseImage.RLock()
	calls = mock.calls.LabelBaseImage
	mock.lockLabelBaseImage.RUnlock()
	return calls
}

// LabelCreated calls LabelCreatedFunc.
func (mock *ConfigMock) LabelCreated() string {
	if mock.LabelCreatedFunc == nil {
		panic("ConfigMock.LabelCreatedFunc: method is nil but Config.LabelCreated was just called")
	}
	callInfo := struct {
	}{}
	mock.lockLabelCreated.Lock()
	mock.calls.LabelCreated = append(mock.calls.LabelCreated, callInfo)
	mock.lockLabelCreated.Unlock()
	return mock.LabelCreatedFunc()
}

// LabelCreatedCalls gets all the calls that were made to LabelCreated.
// Check the length with:
//
//	len(mockedConfig.LabelCreatedCalls())
func (mock *ConfigMock) LabelCreatedCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockLabelCreated.RLock()
	calls = mock.calls.LabelCreated
	mock.lockLabelCreated.RUnlock()
	return calls
}

// LabelDomain calls LabelDomainFunc.
func (mock *ConfigMock) LabelDomain() string {
	if mock.LabelDomainFunc == nil {
		panic("ConfigMock.LabelDomainFunc: method is nil but Config.LabelDomain was just called")
	}
	callInfo := struct {
	}{}
	mock.lockLabelDomain.Lock()
	mock.calls.LabelDomain = append(mock.calls.LabelDomain, callInfo)
	mock.lockLabelDomain.Unlock()
	return mock.LabelDomainFunc()
}

// LabelDomainCalls gets all the calls that were made to LabelDomain.
// Check the length with:
//
//	len(mockedConfig.LabelDomainCalls())
func (mock *ConfigMock) LabelDomainCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockLabelDomain.RLock()
	calls = mock.calls.LabelDomain
	mock.lockLabelDomain.RUnlock()
	return calls
}

// LabelE2ETest calls LabelE2ETestFunc.
func (mock *ConfigMock) LabelE2ETest() string {
	if mock.LabelE2ETestFunc == nil {
		panic("ConfigMock.LabelE2ETestFunc: method is nil but Config.LabelE2ETest was just called")
	}
	callInfo := struct {
	}{}
	mock.lockLabelE2ETest.Lock()
	mock.calls.LabelE2ETest = append(mock.calls.LabelE2ETest, callInfo)
	mock.lockLabelE2ETest.Unlock()
	return mock.LabelE2ETestFunc()
}

// LabelE2ETestCalls gets all the calls that were made to LabelE2ETest.
// Check the length with:
//
//	len(mockedConfig.LabelE2ETestCalls())
func (mock *ConfigMock) LabelE2ETestCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockLabelE2ETest.RLock()
	calls = mock.calls.LabelE2ETest
	mock.lockLabelE2ETest.RUnlock()
	return calls
}

// LabelFlavor calls LabelFlavorFunc.
func (mock *ConfigMock) LabelFlavor() string {
	if mock.LabelFlavorFunc == nil {
		panic("ConfigMock.LabelFlavorFunc: method is nil but Config.LabelFlavor was just called")
	}
	callInfo := struct {
	}{}
	mock.lockLabelFlavor.Lock()
	mock.calls.LabelFlavor = append(mock.calls.LabelFlavor, callInfo)
	mock.lockLabelFlavor.Unlock()
	return mock.LabelFlavorFunc()
}

// LabelFlavorCalls gets all the calls that were made to LabelFlavor.
// Check the length with:
//
//	len(mockedConfig.LabelFlavorCalls())
func (mock *ConfigMock) LabelFlavorCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockLabelFlavor.RLock()
	calls = mock.calls.LabelFlavor
	mock.lockLabelFlavor.RUnlock()
	return calls
}

// LabelImage calls LabelImageFunc.
func (mock *ConfigMock) LabelImage() string {
	if mock.LabelImageFunc == nil {
		panic("ConfigMock.LabelImageFunc: method is nil but Config.LabelImage was just called")
	}
	callInfo := struct {
	}{}
	mock.lockLabelImage.Lock()
	mock.calls.LabelImage = append(mock.calls.LabelImage, callInfo)
	mock.lockLabelImage.Unlock()
	return mock.LabelImageFunc()
}

// LabelImageCalls gets all the calls that were made to LabelImage.
// Check the length with:
//
//	len(mockedConfig.LabelImageCalls())
func (mock *ConfigMock) LabelImageCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockLabelImage.RLock()
	calls = mock.calls.LabelImage
	mock.lockLabelImage.RUnlock()
	return calls
}

// LabelManaged calls LabelManagedFunc.
func (mock *ConfigMock) LabelManaged() string {
	if mock.LabelManagedFunc == nil {
		panic("ConfigMock.LabelManagedFunc: method is nil but Config.LabelManaged was just called")
	}
	callInfo := struct {
	}{}
	mock.lockLabelManaged.Lock()
	mock.calls.LabelManaged = append(mock.calls.LabelManaged, callInfo)
	mock.lockLabelManaged.Unlock()
	return mock.LabelManagedFunc()
}

// LabelManagedCalls gets all the calls that were made to LabelManaged.
// Check the length with:
//
//	len(mockedConfig.LabelManagedCalls())
func (mock *ConfigMock) LabelManagedCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockLabelManaged.RLock()
	calls = mock.calls.LabelManaged
	mock.lockLabelManaged.RUnlock()
	return calls
}

// LabelMonitoringStack calls LabelMonitoringStackFunc.
func (mock *ConfigMock) LabelMonitoringStack() string {
	if mock.LabelMonitoringStackFunc == nil {
		panic("ConfigMock.LabelMonitoringStackFunc: method is nil but Config.LabelMonitoringStack was just called")
	}
	callInfo := struct {
	}{}
	mock.lockLabelMonitoringStack.Lock()
	mock.calls.LabelMonitoringStack = append(mock.calls.LabelMonitoringStack, callInfo)
	mock.lockLabelMonitoringStack.Unlock()
	return mock.LabelMonitoringStackFunc()
}

// LabelMonitoringStackCalls gets all the calls that were made to LabelMonitoringStack.
// Check the length with:
//
//	len(mockedConfig.LabelMonitoringStackCalls())
func (mock *ConfigMock) LabelMonitoringStackCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockLabelMonitoringStack.RLock()
	calls = mock.calls.LabelMonitoringStack
	mock.lockLabelMonitoringStack.RUnlock()
	return calls
}

// LabelPrefix calls LabelPrefixFunc.
func (mock *ConfigMock) LabelPrefix() string {
	if mock.LabelPrefixFunc == nil {
		panic("ConfigMock.LabelPrefixFunc: method is nil but Config.LabelPrefix was just called")
	}
	callInfo := struct {
	}{}
	mock.lockLabelPrefix.Lock()
	mock.calls.LabelPrefix = append(mock.calls.LabelPrefix, callInfo)
	mock.lockLabelPrefix.Unlock()
	return mock.LabelPrefixFunc()
}

// LabelPrefixCalls gets all the calls that were made to LabelPrefix.
// Check the length with:
//
//	len(mockedConfig.LabelPrefixCalls())
func (mock *ConfigMock) LabelPrefixCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockLabelPrefix.RLock()
	calls = mock.calls.LabelPrefix
	mock.lockLabelPrefix.RUnlock()
	return calls
}

// LabelProject calls LabelProjectFunc.
func (mock *ConfigMock) LabelProject() string {
	if mock.LabelProjectFunc == nil {
		panic("ConfigMock.LabelProjectFunc: method is nil but Config.LabelProject was just called")
	}
	callInfo := struct {
	}{}
	mock.lockLabelProject.Lock()
	mock.calls.LabelProject = append(mock.calls.LabelProject, callInfo)
	mock.lockLabelProject.Unlock()
	return mock.LabelProjectFunc()
}

// LabelProjectCalls gets all the calls that were made to LabelProject.
// Check the length with:
//
//	len(mockedConfig.LabelProjectCalls())
func (mock *ConfigMock) LabelProjectCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockLabelProject.RLock()
	calls = mock.calls.LabelProject
	mock.lockLabelProject.RUnlock()
	return calls
}

// LabelPurpose calls LabelPurposeFunc.
func (mock *ConfigMock) LabelPurpose() string {
	if mock.LabelPurposeFunc == nil {
		panic("ConfigMock.LabelPurposeFunc: method is nil but Config.LabelPurpose was just called")
	}
	callInfo := struct {
	}{}
	mock.lockLabelPurpose.Lock()
	mock.calls.LabelPurpose = append(mock.calls.LabelPurpose, callInfo)
	mock.lockLabelPurpose.Unlock()
	return mock.LabelPurposeFunc()
}

// LabelPurposeCalls gets all the calls that were made to LabelPurpose.
// Check the length with:
//
//	len(mockedConfig.LabelPurposeCalls())
func (mock *ConfigMock) LabelPurposeCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockLabelPurpose.RLock()
	calls = mock.calls.LabelPurpose
	mock.lockLabelPurpose.RUnlock()
	return calls
}

// LabelTest calls LabelTestFunc.
func (mock *ConfigMock) LabelTest() string {
	if mock.LabelTestFunc == nil {
		panic("ConfigMock.LabelTestFunc: method is nil but Config.LabelTest was just called")
	}
	callInfo := struct {
	}{}
	mock.lockLabelTest.Lock()
	mock.calls.LabelTest = append(mock.calls.LabelTest, callInfo)
	mock.lockLabelTest.Unlock()
	return mock.LabelTestFunc()
}

// LabelTestCalls gets all the calls that were made to LabelTest.
// Check the length with:
//
//	len(mockedConfig.LabelTestCalls())
func (mock *ConfigMock) LabelTestCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockLabelTest.RLock()
	calls = mock.calls.LabelTest
	mock.lockLabelTest.RUnlock()
	return calls
}

// LabelTestName calls LabelTestNameFunc.
func (mock *ConfigMock) LabelTestName() string {
	if mock.LabelTestNameFunc == nil {
		panic("ConfigMock.LabelTestNameFunc: method is nil but Config.LabelTestName was just called")
	}
	callInfo := struct {
	}{}
	mock.lockLabelTestName.Lock()
	mock.calls.LabelTestName = append(mock.calls.LabelTestName, callInfo)
	mock.lockLabelTestName.Unlock()
	return mock.LabelTestNameFunc()
}

// LabelTestNameCalls gets all the calls that were made to LabelTestName.
// Check the length with:
//
//	len(mockedConfig.LabelTestNameCalls())
func (mock *ConfigMock) LabelTestNameCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockLabelTestName.RLock()
	calls = mock.calls.LabelTestName
	mock.lockLabelTestName.RUnlock()
	return calls
}

// LabelVersion calls LabelVersionFunc.
func (mock *ConfigMock) LabelVersion() string {
	if mock.LabelVersionFunc == nil {
		panic("ConfigMock.LabelVersionFunc: method is nil but Config.LabelVersion was just called")
	}
	callInfo := struct {
	}{}
	mock.lockLabelVersion.Lock()
	mock.calls.LabelVersion = append(mock.calls.LabelVersion, callInfo)
	mock.lockLabelVersion.Unlock()
	return mock.LabelVersionFunc()
}

// LabelVersionCalls gets all the calls that were made to LabelVersion.
// Check the length with:
//
//	len(mockedConfig.LabelVersionCalls())
func (mock *ConfigMock) LabelVersionCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockLabelVersion.RLock()
	calls = mock.calls.LabelVersion
	mock.lockLabelVersion.RUnlock()
	return calls
}

// LabelWorkdir calls LabelWorkdirFunc.
func (mock *ConfigMock) LabelWorkdir() string {
	if mock.LabelWorkdirFunc == nil {
		panic("ConfigMock.LabelWorkdirFunc: method is nil but Config.LabelWorkdir was just called")
	}
	callInfo := struct {
	}{}
	mock.lockLabelWorkdir.Lock()
	mock.calls.LabelWorkdir = append(mock.calls.LabelWorkdir, callInfo)
	mock.lockLabelWorkdir.Unlock()
	return mock.LabelWorkdirFunc()
}

// LabelWorkdirCalls gets all the calls that were made to LabelWorkdir.
// Check the length with:
//
//	len(mockedConfig.LabelWorkdirCalls())
func (mock *ConfigMock) LabelWorkdirCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockLabelWorkdir.RLock()
	calls = mock.calls.LabelWorkdir
	mock.lockLabelWorkdir.RUnlock()
	return calls
}

// Logging calls LoggingFunc.
func (mock *ConfigMock) Logging() map[string]any {
	if mock.LoggingFunc == nil {
		panic("ConfigMock.LoggingFunc: method is nil but Config.Logging was just called")
	}
	callInfo := struct {
	}{}
	mock.lockLogging.Lock()
	mock.calls.Logging = append(mock.calls.Logging, callInfo)
	mock.lockLogging.Unlock()
	return mock.LoggingFunc()
}

// LoggingCalls gets all the calls that were made to Logging.
// Check the length with:
//
//	len(mockedConfig.LoggingCalls())
func (mock *ConfigMock) LoggingCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockLogging.RLock()
	calls = mock.calls.Logging
	mock.lockLogging.RUnlock()
	return calls
}

// LoggingConfig calls LoggingConfigFunc.
func (mock *ConfigMock) LoggingConfig() config.LoggingConfig {
	if mock.LoggingConfigFunc == nil {
		panic("ConfigMock.LoggingConfigFunc: method is nil but Config.LoggingConfig was just called")
	}
	callInfo := struct {
	}{}
	mock.lockLoggingConfig.Lock()
	mock.calls.LoggingConfig = append(mock.calls.LoggingConfig, callInfo)
	mock.lockLoggingConfig.Unlock()
	return mock.LoggingConfigFunc()
}

// LoggingConfigCalls gets all the calls that were made to LoggingConfig.
// Check the length with:
//
//	len(mockedConfig.LoggingConfigCalls())
func (mock *ConfigMock) LoggingConfigCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockLoggingConfig.RLock()
	calls = mock.calls.LoggingConfig
	mock.lockLoggingConfig.RUnlock()
	return calls
}

// LogsSubdir calls LogsSubdirFunc.
func (mock *ConfigMock) LogsSubdir() (string, error) {
	if mock.LogsSubdirFunc == nil {
		panic("ConfigMock.LogsSubdirFunc: method is nil but Config.LogsSubdir was just called")
	}
	callInfo := struct {
	}{}
	mock.lockLogsSubdir.Lock()
	mock.calls.LogsSubdir = append(mock.calls.LogsSubdir, callInfo)
	mock.lockLogsSubdir.Unlock()
	return mock.LogsSubdirFunc()
}

// LogsSubdirCalls gets all the calls that were made to LogsSubdir.
// Check the length with:
//
//	len(mockedConfig.LogsSubdirCalls())
func (mock *ConfigMock) LogsSubdirCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockLogsSubdir.RLock()
	calls = mock.calls.LogsSubdir
	mock.lockLogsSubdir.RUnlock()
	return calls
}

// ManagedLabelValue calls ManagedLabelValueFunc.
func (mock *ConfigMock) ManagedLabelValue() string {
	if mock.ManagedLabelValueFunc == nil {
		panic("ConfigMock.ManagedLabelValueFunc: method is nil but Config.ManagedLabelValue was just called")
	}
	callInfo := struct {
	}{}
	mock.lockManagedLabelValue.Lock()
	mock.calls.ManagedLabelValue = append(mock.calls.ManagedLabelValue, callInfo)
	mock.lockManagedLabelValue.Unlock()
	return mock.ManagedLabelValueFunc()
}

// ManagedLabelValueCalls gets all the calls that were made to ManagedLabelValue.
// Check the length with:
//
//	len(mockedConfig.ManagedLabelValueCalls())
func (mock *ConfigMock) ManagedLabelValueCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockManagedLabelValue.RLock()
	calls = mock.calls.ManagedLabelValue
	mock.lockManagedLabelValue.RUnlock()
	return calls
}

// MonitorSubdir calls MonitorSubdirFunc.
func (mock *ConfigMock) MonitorSubdir() (string, error) {
	if mock.MonitorSubdirFunc == nil {
		panic("ConfigMock.MonitorSubdirFunc: method is nil but Config.MonitorSubdir was just called")
	}
	callInfo := struct {
	}{}
	mock.lockMonitorSubdir.Lock()
	mock.calls.MonitorSubdir = append(mock.calls.MonitorSubdir, callInfo)
	mock.lockMonitorSubdir.Unlock()
	return mock.MonitorSubdirFunc()
}

// MonitorSubdirCalls gets all the calls that were made to MonitorSubdir.
// Check the length with:
//
//	len(mockedConfig.MonitorSubdirCalls())
func (mock *ConfigMock) MonitorSubdirCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockMonitorSubdir.RLock()
	calls = mock.calls.MonitorSubdir
	mock.lockMonitorSubdir.RUnlock()
	return calls
}

// MonitoringConfig calls MonitoringConfigFunc.
func (mock *ConfigMock) MonitoringConfig() config.MonitoringConfig {
	if mock.MonitoringConfigFunc == nil {
		panic("ConfigMock.MonitoringConfigFunc: method is nil but Config.MonitoringConfig was just called")
	}
	callInfo := struct {
	}{}
	mock.lockMonitoringConfig.Lock()
	mock.calls.MonitoringConfig = append(mock.calls.MonitoringConfig, callInfo)
	mock.lockMonitoringConfig.Unlock()
	return mock.MonitoringConfigFunc()
}

// MonitoringConfigCalls gets all the calls that were made to MonitoringConfig.
// Check the length with:
//
//	len(mockedConfig.MonitoringConfigCalls())
func (mock *ConfigMock) MonitoringConfigCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockMonitoringConfig.RLock()
	calls = mock.calls.MonitoringConfig
	mock.lockMonitoringConfig.RUnlock()
	return calls
}

// PidsSubdir calls PidsSubdirFunc.
func (mock *ConfigMock) PidsSubdir() (string, error) {
	if mock.PidsSubdirFunc == nil {
		panic("ConfigMock.PidsSubdirFunc: method is nil but Config.PidsSubdir was just called")
	}
	callInfo := struct {
	}{}
	mock.lockPidsSubdir.Lock()
	mock.calls.PidsSubdir = append(mock.calls.PidsSubdir, callInfo)
	mock.lockPidsSubdir.Unlock()
	return mock.PidsSubdirFunc()
}

// PidsSubdirCalls gets all the calls that were made to PidsSubdir.
// Check the length with:
//
//	len(mockedConfig.PidsSubdirCalls())
func (mock *ConfigMock) PidsSubdirCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockPidsSubdir.RLock()
	calls = mock.calls.PidsSubdir
	mock.lockPidsSubdir.RUnlock()
	return calls
}

// Project calls ProjectFunc.
func (mock *ConfigMock) Project() *config.Project {
	if mock.ProjectFunc == nil {
		panic("ConfigMock.ProjectFunc: method is nil but Config.Project was just called")
	}
	callInfo := struct {
	}{}
	mock.lockProject.Lock()
	mock.calls.Project = append(mock.calls.Project, callInfo)
	mock.lockProject.Unlock()
	return mock.ProjectFunc()
}

// ProjectCalls gets all the calls that were made to Project.
// Check the length with:
//
//	len(mockedConfig.ProjectCalls())
func (mock *ConfigMock) ProjectCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockProject.RLock()
	calls = mock.calls.Project
	mock.lockProject.RUnlock()
	return calls
}

// ProjectConfigFileName calls ProjectConfigFileNameFunc.
func (mock *ConfigMock) ProjectConfigFileName() string {
	if mock.ProjectConfigFileNameFunc == nil {
		panic("ConfigMock.ProjectConfigFileNameFunc: method is nil but Config.ProjectConfigFileName was just called")
	}
	callInfo := struct {
	}{}
	mock.lockProjectConfigFileName.Lock()
	mock.calls.ProjectConfigFileName = append(mock.calls.ProjectConfigFileName, callInfo)
	mock.lockProjectConfigFileName.Unlock()
	return mock.ProjectConfigFileNameFunc()
}

// ProjectConfigFileNameCalls gets all the calls that were made to ProjectConfigFileName.
// Check the length with:
//
//	len(mockedConfig.ProjectConfigFileNameCalls())
func (mock *ConfigMock) ProjectConfigFileNameCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockProjectConfigFileName.RLock()
	calls = mock.calls.ProjectConfigFileName
	mock.lockProjectConfigFileName.RUnlock()
	return calls
}

// ProjectRegistryFileName calls ProjectRegistryFileNameFunc.
func (mock *ConfigMock) ProjectRegistryFileName() string {
	if mock.ProjectRegistryFileNameFunc == nil {
		panic("ConfigMock.ProjectRegistryFileNameFunc: method is nil but Config.ProjectRegistryFileName was just called")
	}
	callInfo := struct {
	}{}
	mock.lockProjectRegistryFileName.Lock()
	mock.calls.ProjectRegistryFileName = append(mock.calls.ProjectRegistryFileName, callInfo)
	mock.lockProjectRegistryFileName.Unlock()
	return mock.ProjectRegistryFileNameFunc()
}

// ProjectRegistryFileNameCalls gets all the calls that were made to ProjectRegistryFileName.
// Check the length with:
//
//	len(mockedConfig.ProjectRegistryFileNameCalls())
func (mock *ConfigMock) ProjectRegistryFileNameCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockProjectRegistryFileName.RLock()
	calls = mock.calls.ProjectRegistryFileName
	mock.lockProjectRegistryFileName.RUnlock()
	return calls
}

// PrometheusURL calls PrometheusURLFunc.
func (mock *ConfigMock) PrometheusURL(host string, https bool) string {
	if mock.PrometheusURLFunc == nil {
		panic("ConfigMock.PrometheusURLFunc: method is nil but Config.PrometheusURL was just called")
	}
	callInfo := struct {
		Host  string
		HTTPS bool
	}{
		Host:  host,
		HTTPS: https,
	}
	mock.lockPrometheusURL.Lock()
	mock.calls.PrometheusURL = append(mock.calls.PrometheusURL, callInfo)
	mock.lockPrometheusURL.Unlock()
	return mock.PrometheusURLFunc(host, https)
}

// PrometheusURLCalls gets all the calls that were made to PrometheusURL.
// Check the length with:
//
//	len(mockedConfig.PrometheusURLCalls())
func (mock *ConfigMock) PrometheusURLCalls() []struct {
	Host  string
	HTTPS bool
} {
	var calls []struct {
		Host  string
		HTTPS bool
	}
	mock.lockPrometheusURL.RLock()
	calls = mock.calls.PrometheusURL
	mock.lockPrometheusURL.RUnlock()
	return calls
}

// RequiredFirewallDomains calls RequiredFirewallDomainsFunc.
func (mock *ConfigMock) RequiredFirewallDomains() []string {
	if mock.RequiredFirewallDomainsFunc == nil {
		panic("ConfigMock.RequiredFirewallDomainsFunc: method is nil but Config.RequiredFirewallDomains was just called")
	}
	callInfo := struct {
	}{}
	mock.lockRequiredFirewallDomains.Lock()
	mock.calls.RequiredFirewallDomains = append(mock.calls.RequiredFirewallDomains, callInfo)
	mock.lockRequiredFirewallDomains.Unlock()
	return mock.RequiredFirewallDomainsFunc()
}

// RequiredFirewallDomainsCalls gets all the calls that were made to RequiredFirewallDomains.
// Check the length with:
//
//	len(mockedConfig.RequiredFirewallDomainsCalls())
func (mock *ConfigMock) RequiredFirewallDomainsCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockRequiredFirewallDomains.RLock()
	calls = mock.calls.RequiredFirewallDomains
	mock.lockRequiredFirewallDomains.RUnlock()
	return calls
}

// Set calls SetFunc.
func (mock *ConfigMock) Set(key string, value any) error {
	if mock.SetFunc == nil {
		panic("ConfigMock.SetFunc: method is nil but Config.Set was just called")
	}
	callInfo := struct {
		Key   string
		Value any
	}{
		Key:   key,
		Value: value,
	}
	mock.lockSet.Lock()
	mock.calls.Set = append(mock.calls.Set, callInfo)
	mock.lockSet.Unlock()
	return mock.SetFunc(key, value)
}

// SetCalls gets all the calls that were made to Set.
// Check the length with:
//
//	len(mockedConfig.SetCalls())
func (mock *ConfigMock) SetCalls() []struct {
	Key   string
	Value any
} {
	var calls []struct {
		Key   string
		Value any
	}
	mock.lockSet.RLock()
	calls = mock.calls.Set
	mock.lockSet.RUnlock()
	return calls
}

// Settings calls SettingsFunc.
func (mock *ConfigMock) Settings() config.Settings {
	if mock.SettingsFunc == nil {
		panic("ConfigMock.SettingsFunc: method is nil but Config.Settings was just called")
	}
	callInfo := struct {
	}{}
	mock.lockSettings.Lock()
	mock.calls.Settings = append(mock.calls.Settings, callInfo)
	mock.lockSettings.Unlock()
	return mock.SettingsFunc()
}

// SettingsCalls gets all the calls that were made to Settings.
// Check the length with:
//
//	len(mockedConfig.SettingsCalls())
func (mock *ConfigMock) SettingsCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockSettings.RLock()
	calls = mock.calls.Settings
	mock.lockSettings.RUnlock()
	return calls
}

// SettingsFileName calls SettingsFileNameFunc.
func (mock *ConfigMock) SettingsFileName() string {
	if mock.SettingsFileNameFunc == nil {
		panic("ConfigMock.SettingsFileNameFunc: method is nil but Config.SettingsFileName was just called")
	}
	callInfo := struct {
	}{}
	mock.lockSettingsFileName.Lock()
	mock.calls.SettingsFileName = append(mock.calls.SettingsFileName, callInfo)
	mock.lockSettingsFileName.Unlock()
	return mock.SettingsFileNameFunc()
}

// SettingsFileNameCalls gets all the calls that were made to SettingsFileName.
// Check the length with:
//
//	len(mockedConfig.SettingsFileNameCalls())
func (mock *ConfigMock) SettingsFileNameCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockSettingsFileName.RLock()
	calls = mock.calls.SettingsFileName
	mock.lockSettingsFileName.RUnlock()
	return calls
}

// ShareSubdir calls ShareSubdirFunc.
func (mock *ConfigMock) ShareSubdir() (string, error) {
	if mock.ShareSubdirFunc == nil {
		panic("ConfigMock.ShareSubdirFunc: method is nil but Config.ShareSubdir was just called")
	}
	callInfo := struct {
	}{}
	mock.lockShareSubdir.Lock()
	mock.calls.ShareSubdir = append(mock.calls.ShareSubdir, callInfo)
	mock.lockShareSubdir.Unlock()
	return mock.ShareSubdirFunc()
}

// ShareSubdirCalls gets all the calls that were made to ShareSubdir.
// Check the length with:
//
//	len(mockedConfig.ShareSubdirCalls())
func (mock *ConfigMock) ShareSubdirCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockShareSubdir.RLock()
	calls = mock.calls.ShareSubdir
	mock.lockShareSubdir.RUnlock()
	return calls
}

// StateDirEnvVar calls StateDirEnvVarFunc.
func (mock *ConfigMock) StateDirEnvVar() string {
	if mock.StateDirEnvVarFunc == nil {
		panic("ConfigMock.StateDirEnvVarFunc: method is nil but Config.StateDirEnvVar was just called")
	}
	callInfo := struct {
	}{}
	mock.lockStateDirEnvVar.Lock()
	mock.calls.StateDirEnvVar = append(mock.calls.StateDirEnvVar, callInfo)
	mock.lockStateDirEnvVar.Unlock()
	return mock.StateDirEnvVarFunc()
}

// StateDirEnvVarCalls gets all the calls that were made to StateDirEnvVar.
// Check the length with:
//
//	len(mockedConfig.StateDirEnvVarCalls())
func (mock *ConfigMock) StateDirEnvVarCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockStateDirEnvVar.RLock()
	calls = mock.calls.StateDirEnvVar
	mock.lockStateDirEnvVar.RUnlock()
	return calls
}

// TestRepoDirEnvVar calls TestRepoDirEnvVarFunc.
func (mock *ConfigMock) TestRepoDirEnvVar() string {
	if mock.TestRepoDirEnvVarFunc == nil {
		panic("ConfigMock.TestRepoDirEnvVarFunc: method is nil but Config.TestRepoDirEnvVar was just called")
	}
	callInfo := struct {
	}{}
	mock.lockTestRepoDirEnvVar.Lock()
	mock.calls.TestRepoDirEnvVar = append(mock.calls.TestRepoDirEnvVar, callInfo)
	mock.lockTestRepoDirEnvVar.Unlock()
	return mock.TestRepoDirEnvVarFunc()
}

// TestRepoDirEnvVarCalls gets all the calls that were made to TestRepoDirEnvVar.
// Check the length with:
//
//	len(mockedConfig.TestRepoDirEnvVarCalls())
func (mock *ConfigMock) TestRepoDirEnvVarCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockTestRepoDirEnvVar.RLock()
	calls = mock.calls.TestRepoDirEnvVar
	mock.lockTestRepoDirEnvVar.RUnlock()
	return calls
}

// Watch calls WatchFunc.
func (mock *ConfigMock) Watch(onChange func(fsnotify.Event)) error {
	if mock.WatchFunc == nil {
		panic("ConfigMock.WatchFunc: method is nil but Config.Watch was just called")
	}
	callInfo := struct {
		OnChange func(fsnotify.Event)
	}{
		OnChange: onChange,
	}
	mock.lockWatch.Lock()
	mock.calls.Watch = append(mock.calls.Watch, callInfo)
	mock.lockWatch.Unlock()
	return mock.WatchFunc(onChange)
}

// WatchCalls gets all the calls that were made to Watch.
// Check the length with:
//
//	len(mockedConfig.WatchCalls())
func (mock *ConfigMock) WatchCalls() []struct {
	OnChange func(fsnotify.Event)
} {
	var calls []struct {
		OnChange func(fsnotify.Event)
	}
	mock.lockWatch.RLock()
	calls = mock.calls.Watch
	mock.lockWatch.RUnlock()
	return calls
}

// WorktreesSubdir calls WorktreesSubdirFunc.
func (mock *ConfigMock) WorktreesSubdir() (string, error) {
	if mock.WorktreesSubdirFunc == nil {
		panic("ConfigMock.WorktreesSubdirFunc: method is nil but Config.WorktreesSubdir was just called")
	}
	callInfo := struct {
	}{}
	mock.lockWorktreesSubdir.Lock()
	mock.calls.WorktreesSubdir = append(mock.calls.WorktreesSubdir, callInfo)
	mock.lockWorktreesSubdir.Unlock()
	return mock.WorktreesSubdirFunc()
}

// WorktreesSubdirCalls gets all the calls that were made to WorktreesSubdir.
// Check the length with:
//
//	len(mockedConfig.WorktreesSubdirCalls())
func (mock *ConfigMock) WorktreesSubdirCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockWorktreesSubdir.RLock()
	calls = mock.calls.WorktreesSubdir
	mock.lockWorktreesSubdir.RUnlock()
	return calls
}

// Write calls WriteFunc.
func (mock *ConfigMock) Write(opts config.WriteOptions) error {
	if mock.WriteFunc == nil {
		panic("ConfigMock.WriteFunc: method is nil but Config.Write was just called")
	}
	callInfo := struct {
		Opts config.WriteOptions
	}{
		Opts: opts,
	}
	mock.lockWrite.Lock()
	mock.calls.Write = append(mock.calls.Write, callInfo)
	mock.lockWrite.Unlock()
	return mock.WriteFunc(opts)
}

// WriteCalls gets all the calls that were made to Write.
// Check the length with:
//
//	len(mockedConfig.WriteCalls())
func (mock *ConfigMock) WriteCalls() []struct {
	Opts config.WriteOptions
} {
	var calls []struct {
		Opts config.WriteOptions
	}
	mock.lockWrite.RLock()
	calls = mock.calls.Write
	mock.lockWrite.RUnlock()
	return calls
}
