// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	context "context"
	"github.com/schmitthub/clawker/api/clawkerd/v1"
	grpc "google.golang.org/grpc"
	sync "sync"
)

// Ensure, that ClawkerdServiceClientMock does implement v1.ClawkerdServiceClient.
// If this is not the case, regenerate this file with moq.
var _ v1.ClawkerdServiceClient = &ClawkerdServiceClientMock{}

// ClawkerdServiceClientMock is a mock implementation of v1.ClawkerdServiceClient.
//
//	func TestSomethingThatUsesClawkerdServiceClient(t *testing.T) {
//
//		// make and configure a mocked v1.ClawkerdServiceClient
//		mockedClawkerdServiceClient := &ClawkerdServiceClientMock{
//			SessionFunc: func(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[v1.Command, v1.Response], error) {
//				panic("mock out the Session method")
//			},
//		}
//
//		// use mockedClawkerdServiceClient in code that requires v1.ClawkerdServiceClient
//		// and then make assertions.
//
//	}
type ClawkerdServiceClientMock struct {
	// SessionFunc mocks the Session method.
	SessionFunc func(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[v1.Command, v1.Response], error)

	// calls tracks calls to the methods.
	calls struct {
		// Session holds details about calls to the Session method.
		Session []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Opts is the opts argument value.
			Opts []grpc.CallOption
		}
	}
	lockSession sync.RWMutex
}

// Session calls SessionFunc.
func (mock *ClawkerdServiceClientMock) Session(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[v1.Command, v1.Response], error) {
	if mock.SessionFunc == nil {
		panic("ClawkerdServiceClientMock.SessionFunc: method is nil but ClawkerdServiceClient.Session was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Opts []grpc.CallOption
	}{
		Ctx:  ctx,
		Opts: opts,
	}
	mock.lockSession.Lock()
	mock.calls.Session = append(mock.calls.Session, callInfo)
	mock.lockSession.Unlock()
	return mock.SessionFunc(ctx, opts...)
}

// SessionCalls gets all the calls that were made to Session.
// Check the length with:
//
//	len(mockedClawkerdServiceClient.SessionCalls())
func (mock *ClawkerdServiceClientMock) SessionCalls() []struct {
	Ctx  context.Context
	Opts []grpc.CallOption
} {
	var calls []struct {
		Ctx  context.Context
		Opts []grpc.CallOption
	}
	mock.lockSession.RLock()
	calls = mock.calls.Session
	mock.lockSession.RUnlock()
	return calls
}
