version: 2

project_name: clawker

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: clawker
    main: ./cmd/clawker
    binary: clawker
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/schmitthub/clawker/internal/clawker.Version={{.Version}}
      - -X github.com/schmitthub/clawker/internal/clawker.Commit={{.ShortCommit}}

archives:
  - id: default
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - Merge pull request
      - Merge branch

release:
  github:
    owner: schmitthub
    name: clawker
  prerelease: auto
  name_template: "{{.ProjectName}} v{{.Version}}"
