// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/agent.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// InitEventStatus tracks the lifecycle of an init step.
type InitEventStatus int32

const (
	InitEventStatus_INIT_EVENT_STATUS_UNSPECIFIED InitEventStatus = 0
	// STARTED indicates a step has begun execution.
	InitEventStatus_INIT_EVENT_STATUS_STARTED InitEventStatus = 1
	// COMPLETED indicates a step finished successfully.
	InitEventStatus_INIT_EVENT_STATUS_COMPLETED InitEventStatus = 2
	// FAILED indicates a step encountered an error.
	InitEventStatus_INIT_EVENT_STATUS_FAILED InitEventStatus = 3
	// READY is the final event — all init steps are complete.
	InitEventStatus_INIT_EVENT_STATUS_READY InitEventStatus = 4
)

// Enum value maps for InitEventStatus.
var (
	InitEventStatus_name = map[int32]string{
		0: "INIT_EVENT_STATUS_UNSPECIFIED",
		1: "INIT_EVENT_STATUS_STARTED",
		2: "INIT_EVENT_STATUS_COMPLETED",
		3: "INIT_EVENT_STATUS_FAILED",
		4: "INIT_EVENT_STATUS_READY",
	}
	InitEventStatus_value = map[string]int32{
		"INIT_EVENT_STATUS_UNSPECIFIED": 0,
		"INIT_EVENT_STATUS_STARTED":     1,
		"INIT_EVENT_STATUS_COMPLETED":   2,
		"INIT_EVENT_STATUS_FAILED":      3,
		"INIT_EVENT_STATUS_READY":       4,
	}
)

func (x InitEventStatus) Enum() *InitEventStatus {
	p := new(InitEventStatus)
	*p = x
	return p
}

func (x InitEventStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InitEventStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_agent_proto_enumTypes[0].Descriptor()
}

func (InitEventStatus) Type() protoreflect.EnumType {
	return &file_v1_agent_proto_enumTypes[0]
}

func (x InitEventStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InitEventStatus.Descriptor instead.
func (InitEventStatus) EnumDescriptor() ([]byte, []int) {
	return file_v1_agent_proto_rawDescGZIP(), []int{0}
}

// RegisterRequest is sent by clawkerd to the control plane on startup.
type RegisterRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// container_id is the Docker container ID (hostname inside container).
	ContainerId string `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	// secret is the shared secret for authentication.
	Secret string `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	// version is the clawkerd binary version.
	Version string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	// listen_port is the gRPC port clawkerd is listening on inside the container.
	// The control plane resolves the container's IP via Docker inspect and connects
	// back to <container_ip>:<listen_port> for AgentCommandService RPCs.
	ListenPort    uint32 `protobuf:"varint,4,opt,name=listen_port,json=listenPort,proto3" json:"listen_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *RegisterRequest) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *RegisterRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RegisterRequest) GetListenPort() uint32 {
	if x != nil {
		return x.ListenPort
	}
	return 0
}

// RegisterResponse indicates whether registration was accepted.
// On success, includes ClawkerdConfiguration for logger initialization.
type RegisterResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// accepted is true if the agent was registered successfully.
	Accepted bool `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	// reason provides context when registration is rejected.
	Reason string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	// config is the operational configuration for clawkerd (identity, OTEL, file logging).
	// Only populated when accepted is true.
	Config        *ClawkerdConfiguration `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *RegisterResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *RegisterResponse) GetConfig() *ClawkerdConfiguration {
	if x != nil {
		return x.Config
	}
	return nil
}

// ClawkerdConfiguration is the operational config delivered by the control plane
// during registration. clawkerd uses this to initialize its logger with structured
// logging, OTEL bridge, and project/agent context fields.
// Named "Clawkerd" (not "Agent") because "agent" means Claude Code instance in our domain.
type ClawkerdConfiguration struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// project is the project name for logger context fields.
	Project string `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	// agent is the agent name for logger context fields.
	Agent string `protobuf:"bytes,2,opt,name=agent,proto3" json:"agent,omitempty"`
	// otel configures the OTEL logging bridge (endpoint, timeouts, batching).
	Otel *OtelLogConfig `protobuf:"bytes,3,opt,name=otel,proto3" json:"otel,omitempty"`
	// file_logging configures file-based log rotation.
	FileLogging   *FileLogConfig `protobuf:"bytes,4,opt,name=file_logging,json=fileLogging,proto3" json:"file_logging,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClawkerdConfiguration) Reset() {
	*x = ClawkerdConfiguration{}
	mi := &file_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClawkerdConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClawkerdConfiguration) ProtoMessage() {}

func (x *ClawkerdConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClawkerdConfiguration.ProtoReflect.Descriptor instead.
func (*ClawkerdConfiguration) Descriptor() ([]byte, []int) {
	return file_v1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *ClawkerdConfiguration) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *ClawkerdConfiguration) GetAgent() string {
	if x != nil {
		return x.Agent
	}
	return ""
}

func (x *ClawkerdConfiguration) GetOtel() *OtelLogConfig {
	if x != nil {
		return x.Otel
	}
	return nil
}

func (x *ClawkerdConfiguration) GetFileLogging() *FileLogConfig {
	if x != nil {
		return x.FileLogging
	}
	return nil
}

// OtelLogConfig configures the OTEL zerolog bridge for streaming logs to the collector.
type OtelLogConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// endpoint is the OTLP HTTP endpoint (host:port, no scheme). e.g. "otel-collector:4318"
	Endpoint string `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	// insecure disables TLS (true for local collector).
	Insecure bool `protobuf:"varint,2,opt,name=insecure,proto3" json:"insecure,omitempty"`
	// timeout_seconds is the export timeout (default: 5).
	TimeoutSeconds int32 `protobuf:"varint,3,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	// max_queue_size is the batch processor queue size (default: 2048).
	MaxQueueSize int32 `protobuf:"varint,4,opt,name=max_queue_size,json=maxQueueSize,proto3" json:"max_queue_size,omitempty"`
	// export_interval_seconds is the batch export interval (default: 5).
	ExportIntervalSeconds int32 `protobuf:"varint,5,opt,name=export_interval_seconds,json=exportIntervalSeconds,proto3" json:"export_interval_seconds,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *OtelLogConfig) Reset() {
	*x = OtelLogConfig{}
	mi := &file_v1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OtelLogConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OtelLogConfig) ProtoMessage() {}

func (x *OtelLogConfig) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OtelLogConfig.ProtoReflect.Descriptor instead.
func (*OtelLogConfig) Descriptor() ([]byte, []int) {
	return file_v1_agent_proto_rawDescGZIP(), []int{3}
}

func (x *OtelLogConfig) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *OtelLogConfig) GetInsecure() bool {
	if x != nil {
		return x.Insecure
	}
	return false
}

func (x *OtelLogConfig) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *OtelLogConfig) GetMaxQueueSize() int32 {
	if x != nil {
		return x.MaxQueueSize
	}
	return 0
}

func (x *OtelLogConfig) GetExportIntervalSeconds() int32 {
	if x != nil {
		return x.ExportIntervalSeconds
	}
	return 0
}

// FileLogConfig configures file-based logging with rotation.
type FileLogConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// enabled enables file logging.
	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// max_size_mb is the max log file size in MB before rotation (default: 50).
	MaxSizeMb int32 `protobuf:"varint,2,opt,name=max_size_mb,json=maxSizeMb,proto3" json:"max_size_mb,omitempty"`
	// max_age_days is the max days to retain old logs (default: 7).
	MaxAgeDays int32 `protobuf:"varint,3,opt,name=max_age_days,json=maxAgeDays,proto3" json:"max_age_days,omitempty"`
	// max_backups is the max number of old log files to keep (default: 3).
	MaxBackups int32 `protobuf:"varint,4,opt,name=max_backups,json=maxBackups,proto3" json:"max_backups,omitempty"`
	// compress enables gzip compression of rotated log files (default: true).
	Compress      bool `protobuf:"varint,5,opt,name=compress,proto3" json:"compress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileLogConfig) Reset() {
	*x = FileLogConfig{}
	mi := &file_v1_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileLogConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileLogConfig) ProtoMessage() {}

func (x *FileLogConfig) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileLogConfig.ProtoReflect.Descriptor instead.
func (*FileLogConfig) Descriptor() ([]byte, []int) {
	return file_v1_agent_proto_rawDescGZIP(), []int{4}
}

func (x *FileLogConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *FileLogConfig) GetMaxSizeMb() int32 {
	if x != nil {
		return x.MaxSizeMb
	}
	return 0
}

func (x *FileLogConfig) GetMaxAgeDays() int32 {
	if x != nil {
		return x.MaxAgeDays
	}
	return 0
}

func (x *FileLogConfig) GetMaxBackups() int32 {
	if x != nil {
		return x.MaxBackups
	}
	return 0
}

func (x *FileLogConfig) GetCompress() bool {
	if x != nil {
		return x.Compress
	}
	return false
}

// RunInitRequest is the declarative init specification sent by the control plane.
// clawkerd owns execution — it runs the steps and reports progress.
type RunInitRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// steps is the ordered list of init steps to execute.
	Steps         []*InitStep `protobuf:"bytes,1,rep,name=steps,proto3" json:"steps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunInitRequest) Reset() {
	*x = RunInitRequest{}
	mi := &file_v1_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunInitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunInitRequest) ProtoMessage() {}

func (x *RunInitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunInitRequest.ProtoReflect.Descriptor instead.
func (*RunInitRequest) Descriptor() ([]byte, []int) {
	return file_v1_agent_proto_rawDescGZIP(), []int{5}
}

func (x *RunInitRequest) GetSteps() []*InitStep {
	if x != nil {
		return x.Steps
	}
	return nil
}

// InitStep is a single init command to execute.
type InitStep struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name identifies this step (e.g. "firewall", "git-config").
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// command is the bash command to execute.
	Command       string `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitStep) Reset() {
	*x = InitStep{}
	mi := &file_v1_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitStep) ProtoMessage() {}

func (x *InitStep) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitStep.ProtoReflect.Descriptor instead.
func (*InitStep) Descriptor() ([]byte, []int) {
	return file_v1_agent_proto_rawDescGZIP(), []int{6}
}

func (x *InitStep) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InitStep) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

// RunInitResponse is streamed from clawkerd back to the control plane
// as each init step progresses.
type RunInitResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// step_name identifies which step this event is for.
	StepName string `protobuf:"bytes,1,opt,name=step_name,json=stepName,proto3" json:"step_name,omitempty"`
	// status is the current status of this step.
	Status InitEventStatus `protobuf:"varint,2,opt,name=status,proto3,enum=clawker.agent.v1.InitEventStatus" json:"status,omitempty"`
	// output contains captured stdout from the command.
	Output string `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`
	// error contains stderr or error message if the step failed.
	Error         string `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunInitResponse) Reset() {
	*x = RunInitResponse{}
	mi := &file_v1_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunInitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunInitResponse) ProtoMessage() {}

func (x *RunInitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunInitResponse.ProtoReflect.Descriptor instead.
func (*RunInitResponse) Descriptor() ([]byte, []int) {
	return file_v1_agent_proto_rawDescGZIP(), []int{7}
}

func (x *RunInitResponse) GetStepName() string {
	if x != nil {
		return x.StepName
	}
	return ""
}

func (x *RunInitResponse) GetStatus() InitEventStatus {
	if x != nil {
		return x.Status
	}
	return InitEventStatus_INIT_EVENT_STATUS_UNSPECIFIED
}

func (x *RunInitResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *RunInitResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_v1_agent_proto protoreflect.FileDescriptor

const file_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x0ev1/agent.proto\x12\x10clawker.agent.v1\"\x87\x01\n" +
	"\x0fRegisterRequest\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x16\n" +
	"\x06secret\x18\x02 \x01(\tR\x06secret\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x1f\n" +
	"\vlisten_port\x18\x04 \x01(\rR\n" +
	"listenPort\"\x87\x01\n" +
	"\x10RegisterResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12?\n" +
	"\x06config\x18\x03 \x01(\v2'.clawker.agent.v1.ClawkerdConfigurationR\x06config\"\xc0\x01\n" +
	"\x15ClawkerdConfiguration\x12\x18\n" +
	"\aproject\x18\x01 \x01(\tR\aproject\x12\x14\n" +
	"\x05agent\x18\x02 \x01(\tR\x05agent\x123\n" +
	"\x04otel\x18\x03 \x01(\v2\x1f.clawker.agent.v1.OtelLogConfigR\x04otel\x12B\n" +
	"\ffile_logging\x18\x04 \x01(\v2\x1f.clawker.agent.v1.FileLogConfigR\vfileLogging\"\xce\x01\n" +
	"\rOtelLogConfig\x12\x1a\n" +
	"\bendpoint\x18\x01 \x01(\tR\bendpoint\x12\x1a\n" +
	"\binsecure\x18\x02 \x01(\bR\binsecure\x12'\n" +
	"\x0ftimeout_seconds\x18\x03 \x01(\x05R\x0etimeoutSeconds\x12$\n" +
	"\x0emax_queue_size\x18\x04 \x01(\x05R\fmaxQueueSize\x126\n" +
	"\x17export_interval_seconds\x18\x05 \x01(\x05R\x15exportIntervalSeconds\"\xa8\x01\n" +
	"\rFileLogConfig\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x1e\n" +
	"\vmax_size_mb\x18\x02 \x01(\x05R\tmaxSizeMb\x12 \n" +
	"\fmax_age_days\x18\x03 \x01(\x05R\n" +
	"maxAgeDays\x12\x1f\n" +
	"\vmax_backups\x18\x04 \x01(\x05R\n" +
	"maxBackups\x12\x1a\n" +
	"\bcompress\x18\x05 \x01(\bR\bcompress\"B\n" +
	"\x0eRunInitRequest\x120\n" +
	"\x05steps\x18\x01 \x03(\v2\x1a.clawker.agent.v1.InitStepR\x05steps\"8\n" +
	"\bInitStep\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\"\x97\x01\n" +
	"\x0fRunInitResponse\x12\x1b\n" +
	"\tstep_name\x18\x01 \x01(\tR\bstepName\x129\n" +
	"\x06status\x18\x02 \x01(\x0e2!.clawker.agent.v1.InitEventStatusR\x06status\x12\x16\n" +
	"\x06output\x18\x03 \x01(\tR\x06output\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error*\xaf\x01\n" +
	"\x0fInitEventStatus\x12!\n" +
	"\x1dINIT_EVENT_STATUS_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19INIT_EVENT_STATUS_STARTED\x10\x01\x12\x1f\n" +
	"\x1bINIT_EVENT_STATUS_COMPLETED\x10\x02\x12\x1c\n" +
	"\x18INIT_EVENT_STATUS_FAILED\x10\x03\x12\x1b\n" +
	"\x17INIT_EVENT_STATUS_READY\x10\x042j\n" +
	"\x15AgentReportingService\x12Q\n" +
	"\bRegister\x12!.clawker.agent.v1.RegisterRequest\x1a\".clawker.agent.v1.RegisterResponse2g\n" +
	"\x13AgentCommandService\x12P\n" +
	"\aRunInit\x12 .clawker.agent.v1.RunInitRequest\x1a!.clawker.agent.v1.RunInitResponse0\x01B=Z;github.com/schmitthub/clawker/internal/clawkerd/protocol/v1b\x06proto3"

var (
	file_v1_agent_proto_rawDescOnce sync.Once
	file_v1_agent_proto_rawDescData []byte
)

func file_v1_agent_proto_rawDescGZIP() []byte {
	file_v1_agent_proto_rawDescOnce.Do(func() {
		file_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_agent_proto_rawDesc), len(file_v1_agent_proto_rawDesc)))
	})
	return file_v1_agent_proto_rawDescData
}

var file_v1_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_v1_agent_proto_goTypes = []any{
	(InitEventStatus)(0),          // 0: clawker.agent.v1.InitEventStatus
	(*RegisterRequest)(nil),       // 1: clawker.agent.v1.RegisterRequest
	(*RegisterResponse)(nil),      // 2: clawker.agent.v1.RegisterResponse
	(*ClawkerdConfiguration)(nil), // 3: clawker.agent.v1.ClawkerdConfiguration
	(*OtelLogConfig)(nil),         // 4: clawker.agent.v1.OtelLogConfig
	(*FileLogConfig)(nil),         // 5: clawker.agent.v1.FileLogConfig
	(*RunInitRequest)(nil),        // 6: clawker.agent.v1.RunInitRequest
	(*InitStep)(nil),              // 7: clawker.agent.v1.InitStep
	(*RunInitResponse)(nil),       // 8: clawker.agent.v1.RunInitResponse
}
var file_v1_agent_proto_depIdxs = []int32{
	3, // 0: clawker.agent.v1.RegisterResponse.config:type_name -> clawker.agent.v1.ClawkerdConfiguration
	4, // 1: clawker.agent.v1.ClawkerdConfiguration.otel:type_name -> clawker.agent.v1.OtelLogConfig
	5, // 2: clawker.agent.v1.ClawkerdConfiguration.file_logging:type_name -> clawker.agent.v1.FileLogConfig
	7, // 3: clawker.agent.v1.RunInitRequest.steps:type_name -> clawker.agent.v1.InitStep
	0, // 4: clawker.agent.v1.RunInitResponse.status:type_name -> clawker.agent.v1.InitEventStatus
	1, // 5: clawker.agent.v1.AgentReportingService.Register:input_type -> clawker.agent.v1.RegisterRequest
	6, // 6: clawker.agent.v1.AgentCommandService.RunInit:input_type -> clawker.agent.v1.RunInitRequest
	2, // 7: clawker.agent.v1.AgentReportingService.Register:output_type -> clawker.agent.v1.RegisterResponse
	8, // 8: clawker.agent.v1.AgentCommandService.RunInit:output_type -> clawker.agent.v1.RunInitResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_v1_agent_proto_init() }
func file_v1_agent_proto_init() {
	if File_v1_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_agent_proto_rawDesc), len(file_v1_agent_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_v1_agent_proto_goTypes,
		DependencyIndexes: file_v1_agent_proto_depIdxs,
		EnumInfos:         file_v1_agent_proto_enumTypes,
		MessageInfos:      file_v1_agent_proto_msgTypes,
	}.Build()
	File_v1_agent_proto = out.File
	file_v1_agent_proto_goTypes = nil
	file_v1_agent_proto_depIdxs = nil
}
