// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/controlplane.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ContainerFirewallConfig carries the fields formerly serialized as the
// enableArgs JSON payload passed to `ebpf-manager enable`. Mirrors the
// configuration that populates a BPF container_config entry.
type ContainerFirewallConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// envoy_ip is the dotted-decimal IPv4 of the firewall stack's Envoy container.
	EnvoyIp string `protobuf:"bytes,1,opt,name=envoy_ip,json=envoyIp,proto3" json:"envoy_ip,omitempty"`
	// coredns_ip is the dotted-decimal IPv4 of the firewall stack's CoreDNS container.
	CorednsIp string `protobuf:"bytes,2,opt,name=coredns_ip,json=corednsIp,proto3" json:"coredns_ip,omitempty"`
	// gateway_ip is the dotted-decimal IPv4 of the clawker-net bridge gateway.
	GatewayIp string `protobuf:"bytes,3,opt,name=gateway_ip,json=gatewayIp,proto3" json:"gateway_ip,omitempty"`
	// cidr is the clawker-net subnet in CIDR notation (e.g. "172.20.0.0/24").
	Cidr string `protobuf:"bytes,4,opt,name=cidr,proto3" json:"cidr,omitempty"`
	// host_proxy_ip is the resolved IPv4 of host.docker.internal (optional).
	HostProxyIp string `protobuf:"bytes,5,opt,name=host_proxy_ip,json=hostProxyIp,proto3" json:"host_proxy_ip,omitempty"`
	// host_proxy_port is the host-proxy listener port (0 if unused).
	HostProxyPort uint32 `protobuf:"varint,6,opt,name=host_proxy_port,json=hostProxyPort,proto3" json:"host_proxy_port,omitempty"`
	// egress_port is the Envoy egress listener port the BPF programs redirect to.
	EgressPort    uint32 `protobuf:"varint,7,opt,name=egress_port,json=egressPort,proto3" json:"egress_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerFirewallConfig) Reset() {
	*x = ContainerFirewallConfig{}
	mi := &file_v1_controlplane_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerFirewallConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerFirewallConfig) ProtoMessage() {}

func (x *ContainerFirewallConfig) ProtoReflect() protoreflect.Message {
	mi := &file_v1_controlplane_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerFirewallConfig.ProtoReflect.Descriptor instead.
func (*ContainerFirewallConfig) Descriptor() ([]byte, []int) {
	return file_v1_controlplane_proto_rawDescGZIP(), []int{0}
}

func (x *ContainerFirewallConfig) GetEnvoyIp() string {
	if x != nil {
		return x.EnvoyIp
	}
	return ""
}

func (x *ContainerFirewallConfig) GetCorednsIp() string {
	if x != nil {
		return x.CorednsIp
	}
	return ""
}

func (x *ContainerFirewallConfig) GetGatewayIp() string {
	if x != nil {
		return x.GatewayIp
	}
	return ""
}

func (x *ContainerFirewallConfig) GetCidr() string {
	if x != nil {
		return x.Cidr
	}
	return ""
}

func (x *ContainerFirewallConfig) GetHostProxyIp() string {
	if x != nil {
		return x.HostProxyIp
	}
	return ""
}

func (x *ContainerFirewallConfig) GetHostProxyPort() uint32 {
	if x != nil {
		return x.HostProxyPort
	}
	return 0
}

func (x *ContainerFirewallConfig) GetEgressPort() uint32 {
	if x != nil {
		return x.EgressPort
	}
	return 0
}

// Route is one entry in the global route_map. Mirrors ebpf.Route.
type Route struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// domain_hash is the FNV-1a hash of the normalized destination domain.
	DomainHash uint32 `protobuf:"varint,1,opt,name=domain_hash,json=domainHash,proto3" json:"domain_hash,omitempty"`
	// dst_port is the original destination port (host byte order).
	DstPort uint32 `protobuf:"varint,2,opt,name=dst_port,json=dstPort,proto3" json:"dst_port,omitempty"`
	// envoy_port is the Envoy listener port the BPF programs redirect to.
	EnvoyPort     uint32 `protobuf:"varint,3,opt,name=envoy_port,json=envoyPort,proto3" json:"envoy_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Route) Reset() {
	*x = Route{}
	mi := &file_v1_controlplane_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Route) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Route) ProtoMessage() {}

func (x *Route) ProtoReflect() protoreflect.Message {
	mi := &file_v1_controlplane_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Route.ProtoReflect.Descriptor instead.
func (*Route) Descriptor() ([]byte, []int) {
	return file_v1_controlplane_proto_rawDescGZIP(), []int{1}
}

func (x *Route) GetDomainHash() uint32 {
	if x != nil {
		return x.DomainHash
	}
	return 0
}

func (x *Route) GetDstPort() uint32 {
	if x != nil {
		return x.DstPort
	}
	return 0
}

func (x *Route) GetEnvoyPort() uint32 {
	if x != nil {
		return x.EnvoyPort
	}
	return 0
}

// ContainerConfigSnapshot is a read-only view of a container_map entry.
type ContainerConfigSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnvoyIp       string                 `protobuf:"bytes,1,opt,name=envoy_ip,json=envoyIp,proto3" json:"envoy_ip,omitempty"`
	CorednsIp     string                 `protobuf:"bytes,2,opt,name=coredns_ip,json=corednsIp,proto3" json:"coredns_ip,omitempty"`
	GatewayIp     string                 `protobuf:"bytes,3,opt,name=gateway_ip,json=gatewayIp,proto3" json:"gateway_ip,omitempty"`
	NetAddr       string                 `protobuf:"bytes,4,opt,name=net_addr,json=netAddr,proto3" json:"net_addr,omitempty"`
	NetMask       string                 `protobuf:"bytes,5,opt,name=net_mask,json=netMask,proto3" json:"net_mask,omitempty"`
	HostProxyIp   string                 `protobuf:"bytes,6,opt,name=host_proxy_ip,json=hostProxyIp,proto3" json:"host_proxy_ip,omitempty"`
	HostProxyPort uint32                 `protobuf:"varint,7,opt,name=host_proxy_port,json=hostProxyPort,proto3" json:"host_proxy_port,omitempty"`
	EgressPort    uint32                 `protobuf:"varint,8,opt,name=egress_port,json=egressPort,proto3" json:"egress_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerConfigSnapshot) Reset() {
	*x = ContainerConfigSnapshot{}
	mi := &file_v1_controlplane_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerConfigSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerConfigSnapshot) ProtoMessage() {}

func (x *ContainerConfigSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_v1_controlplane_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerConfigSnapshot.ProtoReflect.Descriptor instead.
func (*ContainerConfigSnapshot) Descriptor() ([]byte, []int) {
	return file_v1_controlplane_proto_rawDescGZIP(), []int{2}
}

func (x *ContainerConfigSnapshot) GetEnvoyIp() string {
	if x != nil {
		return x.EnvoyIp
	}
	return ""
}

func (x *ContainerConfigSnapshot) GetCorednsIp() string {
	if x != nil {
		return x.CorednsIp
	}
	return ""
}

func (x *ContainerConfigSnapshot) GetGatewayIp() string {
	if x != nil {
		return x.GatewayIp
	}
	return ""
}

func (x *ContainerConfigSnapshot) GetNetAddr() string {
	if x != nil {
		return x.NetAddr
	}
	return ""
}

func (x *ContainerConfigSnapshot) GetNetMask() string {
	if x != nil {
		return x.NetMask
	}
	return ""
}

func (x *ContainerConfigSnapshot) GetHostProxyIp() string {
	if x != nil {
		return x.HostProxyIp
	}
	return ""
}

func (x *ContainerConfigSnapshot) GetHostProxyPort() uint32 {
	if x != nil {
		return x.HostProxyPort
	}
	return 0
}

func (x *ContainerConfigSnapshot) GetEgressPort() uint32 {
	if x != nil {
		return x.EgressPort
	}
	return 0
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_v1_controlplane_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_controlplane_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_v1_controlplane_proto_rawDescGZIP(), []int{3}
}

type HealthResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ok is true when the CP has successfully loaded the BPF programs and
	// both listeners are serving.
	Ok            bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_v1_controlplane_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_controlplane_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_v1_controlplane_proto_rawDescGZIP(), []int{4}
}

func (x *HealthResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type EnableContainerFirewallRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// container_id is the full Docker container ID.
	ContainerId string `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	// cgroup_path is the absolute path under /sys/fs/cgroup identifying the
	// container's cgroup (e.g. /sys/fs/cgroup/docker/<id>). The CP validates
	// this path via ebpf.CgroupID to prevent path injection.
	CgroupPath string `protobuf:"bytes,2,opt,name=cgroup_path,json=cgroupPath,proto3" json:"cgroup_path,omitempty"`
	// config carries the Envoy/CoreDNS/gateway IPs, CIDR, and host-proxy
	// settings that populate the container_config BPF map entry.
	Config        *ContainerFirewallConfig `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableContainerFirewallRequest) Reset() {
	*x = EnableContainerFirewallRequest{}
	mi := &file_v1_controlplane_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableContainerFirewallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableContainerFirewallRequest) ProtoMessage() {}

func (x *EnableContainerFirewallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_controlplane_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableContainerFirewallRequest.ProtoReflect.Descriptor instead.
func (*EnableContainerFirewallRequest) Descriptor() ([]byte, []int) {
	return file_v1_controlplane_proto_rawDescGZIP(), []int{5}
}

func (x *EnableContainerFirewallRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *EnableContainerFirewallRequest) GetCgroupPath() string {
	if x != nil {
		return x.CgroupPath
	}
	return ""
}

func (x *EnableContainerFirewallRequest) GetConfig() *ContainerFirewallConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type EnableContainerFirewallResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// cgroup_id is the inode ID the CP computed from cgroup_path.
	CgroupId      uint64 `protobuf:"varint,1,opt,name=cgroup_id,json=cgroupId,proto3" json:"cgroup_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableContainerFirewallResponse) Reset() {
	*x = EnableContainerFirewallResponse{}
	mi := &file_v1_controlplane_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableContainerFirewallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableContainerFirewallResponse) ProtoMessage() {}

func (x *EnableContainerFirewallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_controlplane_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableContainerFirewallResponse.ProtoReflect.Descriptor instead.
func (*EnableContainerFirewallResponse) Descriptor() ([]byte, []int) {
	return file_v1_controlplane_proto_rawDescGZIP(), []int{6}
}

func (x *EnableContainerFirewallResponse) GetCgroupId() uint64 {
	if x != nil {
		return x.CgroupId
	}
	return 0
}

type DisableContainerFirewallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CgroupPath    string                 `protobuf:"bytes,1,opt,name=cgroup_path,json=cgroupPath,proto3" json:"cgroup_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableContainerFirewallRequest) Reset() {
	*x = DisableContainerFirewallRequest{}
	mi := &file_v1_controlplane_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableContainerFirewallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableContainerFirewallRequest) ProtoMessage() {}

func (x *DisableContainerFirewallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_controlplane_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableContainerFirewallRequest.ProtoReflect.Descriptor instead.
func (*DisableContainerFirewallRequest) Descriptor() ([]byte, []int) {
	return file_v1_controlplane_proto_rawDescGZIP(), []int{7}
}

func (x *DisableContainerFirewallRequest) GetCgroupPath() string {
	if x != nil {
		return x.CgroupPath
	}
	return ""
}

type DisableContainerFirewallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CgroupId      uint64                 `protobuf:"varint,1,opt,name=cgroup_id,json=cgroupId,proto3" json:"cgroup_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableContainerFirewallResponse) Reset() {
	*x = DisableContainerFirewallResponse{}
	mi := &file_v1_controlplane_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableContainerFirewallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableContainerFirewallResponse) ProtoMessage() {}

func (x *DisableContainerFirewallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_controlplane_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableContainerFirewallResponse.ProtoReflect.Descriptor instead.
func (*DisableContainerFirewallResponse) Descriptor() ([]byte, []int) {
	return file_v1_controlplane_proto_rawDescGZIP(), []int{8}
}

func (x *DisableContainerFirewallResponse) GetCgroupId() uint64 {
	if x != nil {
		return x.CgroupId
	}
	return 0
}

type BypassContainerRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	CgroupPath string                 `protobuf:"bytes,1,opt,name=cgroup_path,json=cgroupPath,proto3" json:"cgroup_path,omitempty"`
	// timeout_seconds, if > 0, schedules an automatic Unbypass on the CP
	// after this many seconds. The timer lives in the CP process, so it
	// survives the caller exiting — critical for the `clawker firewall
	// bypass` CLI which may terminate before the timeout elapses.
	TimeoutSeconds int64 `protobuf:"varint,2,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BypassContainerRequest) Reset() {
	*x = BypassContainerRequest{}
	mi := &file_v1_controlplane_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BypassContainerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BypassContainerRequest) ProtoMessage() {}

func (x *BypassContainerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_controlplane_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BypassContainerRequest.ProtoReflect.Descriptor instead.
func (*BypassContainerRequest) Descriptor() ([]byte, []int) {
	return file_v1_controlplane_proto_rawDescGZIP(), []int{9}
}

func (x *BypassContainerRequest) GetCgroupPath() string {
	if x != nil {
		return x.CgroupPath
	}
	return ""
}

func (x *BypassContainerRequest) GetTimeoutSeconds() int64 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type BypassContainerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CgroupId      uint64                 `protobuf:"varint,1,opt,name=cgroup_id,json=cgroupId,proto3" json:"cgroup_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BypassContainerResponse) Reset() {
	*x = BypassContainerResponse{}
	mi := &file_v1_controlplane_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BypassContainerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BypassContainerResponse) ProtoMessage() {}

func (x *BypassContainerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_controlplane_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BypassContainerResponse.ProtoReflect.Descriptor instead.
func (*BypassContainerResponse) Descriptor() ([]byte, []int) {
	return file_v1_controlplane_proto_rawDescGZIP(), []int{10}
}

func (x *BypassContainerResponse) GetCgroupId() uint64 {
	if x != nil {
		return x.CgroupId
	}
	return 0
}

type UnbypassContainerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CgroupPath    string                 `protobuf:"bytes,1,opt,name=cgroup_path,json=cgroupPath,proto3" json:"cgroup_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnbypassContainerRequest) Reset() {
	*x = UnbypassContainerRequest{}
	mi := &file_v1_controlplane_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnbypassContainerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnbypassContainerRequest) ProtoMessage() {}

func (x *UnbypassContainerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_controlplane_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnbypassContainerRequest.ProtoReflect.Descriptor instead.
func (*UnbypassContainerRequest) Descriptor() ([]byte, []int) {
	return file_v1_controlplane_proto_rawDescGZIP(), []int{11}
}

func (x *UnbypassContainerRequest) GetCgroupPath() string {
	if x != nil {
		return x.CgroupPath
	}
	return ""
}

type UnbypassContainerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CgroupId      uint64                 `protobuf:"varint,1,opt,name=cgroup_id,json=cgroupId,proto3" json:"cgroup_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnbypassContainerResponse) Reset() {
	*x = UnbypassContainerResponse{}
	mi := &file_v1_controlplane_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnbypassContainerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnbypassContainerResponse) ProtoMessage() {}

func (x *UnbypassContainerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_controlplane_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnbypassContainerResponse.ProtoReflect.Descriptor instead.
func (*UnbypassContainerResponse) Descriptor() ([]byte, []int) {
	return file_v1_controlplane_proto_rawDescGZIP(), []int{12}
}

func (x *UnbypassContainerResponse) GetCgroupId() uint64 {
	if x != nil {
		return x.CgroupId
	}
	return 0
}

type SyncFirewallRoutesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Routes        []*Route               `protobuf:"bytes,1,rep,name=routes,proto3" json:"routes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncFirewallRoutesRequest) Reset() {
	*x = SyncFirewallRoutesRequest{}
	mi := &file_v1_controlplane_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncFirewallRoutesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncFirewallRoutesRequest) ProtoMessage() {}

func (x *SyncFirewallRoutesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_controlplane_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncFirewallRoutesRequest.ProtoReflect.Descriptor instead.
func (*SyncFirewallRoutesRequest) Descriptor() ([]byte, []int) {
	return file_v1_controlplane_proto_rawDescGZIP(), []int{13}
}

func (x *SyncFirewallRoutesRequest) GetRoutes() []*Route {
	if x != nil {
		return x.Routes
	}
	return nil
}

type SyncFirewallRoutesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// applied is the number of routes that were written to route_map.
	Applied       uint32 `protobuf:"varint,1,opt,name=applied,proto3" json:"applied,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncFirewallRoutesResponse) Reset() {
	*x = SyncFirewallRoutesResponse{}
	mi := &file_v1_controlplane_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncFirewallRoutesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncFirewallRoutesResponse) ProtoMessage() {}

func (x *SyncFirewallRoutesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_controlplane_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncFirewallRoutesResponse.ProtoReflect.Descriptor instead.
func (*SyncFirewallRoutesResponse) Descriptor() ([]byte, []int) {
	return file_v1_controlplane_proto_rawDescGZIP(), []int{14}
}

func (x *SyncFirewallRoutesResponse) GetApplied() uint32 {
	if x != nil {
		return x.Applied
	}
	return 0
}

type UpdateDnsCacheRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ip is the dotted-decimal IPv4 to key on.
	Ip string `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	// domain_hash is the FNV-1a hash of the resolved domain.
	DomainHash uint32 `protobuf:"varint,2,opt,name=domain_hash,json=domainHash,proto3" json:"domain_hash,omitempty"`
	// ttl_seconds is the absolute TTL from the DNS response.
	TtlSeconds    uint32 `protobuf:"varint,3,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDnsCacheRequest) Reset() {
	*x = UpdateDnsCacheRequest{}
	mi := &file_v1_controlplane_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDnsCacheRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDnsCacheRequest) ProtoMessage() {}

func (x *UpdateDnsCacheRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_controlplane_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDnsCacheRequest.ProtoReflect.Descriptor instead.
func (*UpdateDnsCacheRequest) Descriptor() ([]byte, []int) {
	return file_v1_controlplane_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateDnsCacheRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *UpdateDnsCacheRequest) GetDomainHash() uint32 {
	if x != nil {
		return x.DomainHash
	}
	return 0
}

func (x *UpdateDnsCacheRequest) GetTtlSeconds() uint32 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type UpdateDnsCacheResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDnsCacheResponse) Reset() {
	*x = UpdateDnsCacheResponse{}
	mi := &file_v1_controlplane_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDnsCacheResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDnsCacheResponse) ProtoMessage() {}

func (x *UpdateDnsCacheResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_controlplane_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDnsCacheResponse.ProtoReflect.Descriptor instead.
func (*UpdateDnsCacheResponse) Descriptor() ([]byte, []int) {
	return file_v1_controlplane_proto_rawDescGZIP(), []int{16}
}

type GarbageCollectDnsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GarbageCollectDnsRequest) Reset() {
	*x = GarbageCollectDnsRequest{}
	mi := &file_v1_controlplane_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GarbageCollectDnsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GarbageCollectDnsRequest) ProtoMessage() {}

func (x *GarbageCollectDnsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_controlplane_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GarbageCollectDnsRequest.ProtoReflect.Descriptor instead.
func (*GarbageCollectDnsRequest) Descriptor() ([]byte, []int) {
	return file_v1_controlplane_proto_rawDescGZIP(), []int{17}
}

type GarbageCollectDnsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// removed is the number of expired entries cleared.
	Removed       uint32 `protobuf:"varint,1,opt,name=removed,proto3" json:"removed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GarbageCollectDnsResponse) Reset() {
	*x = GarbageCollectDnsResponse{}
	mi := &file_v1_controlplane_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GarbageCollectDnsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GarbageCollectDnsResponse) ProtoMessage() {}

func (x *GarbageCollectDnsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_controlplane_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GarbageCollectDnsResponse.ProtoReflect.Descriptor instead.
func (*GarbageCollectDnsResponse) Descriptor() ([]byte, []int) {
	return file_v1_controlplane_proto_rawDescGZIP(), []int{18}
}

func (x *GarbageCollectDnsResponse) GetRemoved() uint32 {
	if x != nil {
		return x.Removed
	}
	return 0
}

type LookupContainerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CgroupPath    string                 `protobuf:"bytes,1,opt,name=cgroup_path,json=cgroupPath,proto3" json:"cgroup_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupContainerRequest) Reset() {
	*x = LookupContainerRequest{}
	mi := &file_v1_controlplane_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupContainerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupContainerRequest) ProtoMessage() {}

func (x *LookupContainerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_controlplane_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupContainerRequest.ProtoReflect.Descriptor instead.
func (*LookupContainerRequest) Descriptor() ([]byte, []int) {
	return file_v1_controlplane_proto_rawDescGZIP(), []int{19}
}

func (x *LookupContainerRequest) GetCgroupPath() string {
	if x != nil {
		return x.CgroupPath
	}
	return ""
}

type LookupContainerResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	CgroupId      uint64                   `protobuf:"varint,1,opt,name=cgroup_id,json=cgroupId,proto3" json:"cgroup_id,omitempty"`
	Config        *ContainerConfigSnapshot `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupContainerResponse) Reset() {
	*x = LookupContainerResponse{}
	mi := &file_v1_controlplane_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupContainerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupContainerResponse) ProtoMessage() {}

func (x *LookupContainerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_controlplane_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupContainerResponse.ProtoReflect.Descriptor instead.
func (*LookupContainerResponse) Descriptor() ([]byte, []int) {
	return file_v1_controlplane_proto_rawDescGZIP(), []int{20}
}

func (x *LookupContainerResponse) GetCgroupId() uint64 {
	if x != nil {
		return x.CgroupId
	}
	return 0
}

func (x *LookupContainerResponse) GetConfig() *ContainerConfigSnapshot {
	if x != nil {
		return x.Config
	}
	return nil
}

type ResolveHostnameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveHostnameRequest) Reset() {
	*x = ResolveHostnameRequest{}
	mi := &file_v1_controlplane_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveHostnameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveHostnameRequest) ProtoMessage() {}

func (x *ResolveHostnameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_controlplane_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveHostnameRequest.ProtoReflect.Descriptor instead.
func (*ResolveHostnameRequest) Descriptor() ([]byte, []int) {
	return file_v1_controlplane_proto_rawDescGZIP(), []int{21}
}

func (x *ResolveHostnameRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

type ResolveHostnameResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// addresses is the list of resolved IPs. Each entry is a dotted-decimal
	// IPv4 or colon-separated IPv6 address.
	Addresses     []string `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveHostnameResponse) Reset() {
	*x = ResolveHostnameResponse{}
	mi := &file_v1_controlplane_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveHostnameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveHostnameResponse) ProtoMessage() {}

func (x *ResolveHostnameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_controlplane_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveHostnameResponse.ProtoReflect.Descriptor instead.
func (*ResolveHostnameResponse) Descriptor() ([]byte, []int) {
	return file_v1_controlplane_proto_rawDescGZIP(), []int{22}
}

func (x *ResolveHostnameResponse) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

var File_v1_controlplane_proto protoreflect.FileDescriptor

const file_v1_controlplane_proto_rawDesc = "" +
	"\n" +
	"\x15v1/controlplane.proto\x12\x10clawker.agent.v1\"\xf3\x01\n" +
	"\x17ContainerFirewallConfig\x12\x19\n" +
	"\benvoy_ip\x18\x01 \x01(\tR\aenvoyIp\x12\x1d\n" +
	"\n" +
	"coredns_ip\x18\x02 \x01(\tR\tcorednsIp\x12\x1d\n" +
	"\n" +
	"gateway_ip\x18\x03 \x01(\tR\tgatewayIp\x12\x12\n" +
	"\x04cidr\x18\x04 \x01(\tR\x04cidr\x12\"\n" +
	"\rhost_proxy_ip\x18\x05 \x01(\tR\vhostProxyIp\x12&\n" +
	"\x0fhost_proxy_port\x18\x06 \x01(\rR\rhostProxyPort\x12\x1f\n" +
	"\vegress_port\x18\a \x01(\rR\n" +
	"egressPort\"b\n" +
	"\x05Route\x12\x1f\n" +
	"\vdomain_hash\x18\x01 \x01(\rR\n" +
	"domainHash\x12\x19\n" +
	"\bdst_port\x18\x02 \x01(\rR\adstPort\x12\x1d\n" +
	"\n" +
	"envoy_port\x18\x03 \x01(\rR\tenvoyPort\"\x95\x02\n" +
	"\x17ContainerConfigSnapshot\x12\x19\n" +
	"\benvoy_ip\x18\x01 \x01(\tR\aenvoyIp\x12\x1d\n" +
	"\n" +
	"coredns_ip\x18\x02 \x01(\tR\tcorednsIp\x12\x1d\n" +
	"\n" +
	"gateway_ip\x18\x03 \x01(\tR\tgatewayIp\x12\x19\n" +
	"\bnet_addr\x18\x04 \x01(\tR\anetAddr\x12\x19\n" +
	"\bnet_mask\x18\x05 \x01(\tR\anetMask\x12\"\n" +
	"\rhost_proxy_ip\x18\x06 \x01(\tR\vhostProxyIp\x12&\n" +
	"\x0fhost_proxy_port\x18\a \x01(\rR\rhostProxyPort\x12\x1f\n" +
	"\vegress_port\x18\b \x01(\rR\n" +
	"egressPort\"\x0f\n" +
	"\rHealthRequest\" \n" +
	"\x0eHealthResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"\xa7\x01\n" +
	"\x1eEnableContainerFirewallRequest\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x1f\n" +
	"\vcgroup_path\x18\x02 \x01(\tR\n" +
	"cgroupPath\x12A\n" +
	"\x06config\x18\x03 \x01(\v2).clawker.agent.v1.ContainerFirewallConfigR\x06config\">\n" +
	"\x1fEnableContainerFirewallResponse\x12\x1b\n" +
	"\tcgroup_id\x18\x01 \x01(\x04R\bcgroupId\"B\n" +
	"\x1fDisableContainerFirewallRequest\x12\x1f\n" +
	"\vcgroup_path\x18\x01 \x01(\tR\n" +
	"cgroupPath\"?\n" +
	" DisableContainerFirewallResponse\x12\x1b\n" +
	"\tcgroup_id\x18\x01 \x01(\x04R\bcgroupId\"b\n" +
	"\x16BypassContainerRequest\x12\x1f\n" +
	"\vcgroup_path\x18\x01 \x01(\tR\n" +
	"cgroupPath\x12'\n" +
	"\x0ftimeout_seconds\x18\x02 \x01(\x03R\x0etimeoutSeconds\"6\n" +
	"\x17BypassContainerResponse\x12\x1b\n" +
	"\tcgroup_id\x18\x01 \x01(\x04R\bcgroupId\";\n" +
	"\x18UnbypassContainerRequest\x12\x1f\n" +
	"\vcgroup_path\x18\x01 \x01(\tR\n" +
	"cgroupPath\"8\n" +
	"\x19UnbypassContainerResponse\x12\x1b\n" +
	"\tcgroup_id\x18\x01 \x01(\x04R\bcgroupId\"L\n" +
	"\x19SyncFirewallRoutesRequest\x12/\n" +
	"\x06routes\x18\x01 \x03(\v2\x17.clawker.agent.v1.RouteR\x06routes\"6\n" +
	"\x1aSyncFirewallRoutesResponse\x12\x18\n" +
	"\aapplied\x18\x01 \x01(\rR\aapplied\"i\n" +
	"\x15UpdateDnsCacheRequest\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x1f\n" +
	"\vdomain_hash\x18\x02 \x01(\rR\n" +
	"domainHash\x12\x1f\n" +
	"\vttl_seconds\x18\x03 \x01(\rR\n" +
	"ttlSeconds\"\x18\n" +
	"\x16UpdateDnsCacheResponse\"\x1a\n" +
	"\x18GarbageCollectDnsRequest\"5\n" +
	"\x19GarbageCollectDnsResponse\x12\x18\n" +
	"\aremoved\x18\x01 \x01(\rR\aremoved\"9\n" +
	"\x16LookupContainerRequest\x12\x1f\n" +
	"\vcgroup_path\x18\x01 \x01(\tR\n" +
	"cgroupPath\"y\n" +
	"\x17LookupContainerResponse\x12\x1b\n" +
	"\tcgroup_id\x18\x01 \x01(\x04R\bcgroupId\x12A\n" +
	"\x06config\x18\x02 \x01(\v2).clawker.agent.v1.ContainerConfigSnapshotR\x06config\"4\n" +
	"\x16ResolveHostnameRequest\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\"7\n" +
	"\x17ResolveHostnameResponse\x12\x1c\n" +
	"\taddresses\x18\x01 \x03(\tR\taddresses2\xd0\b\n" +
	"\x13ControlPlaneService\x12K\n" +
	"\x06Health\x12\x1f.clawker.agent.v1.HealthRequest\x1a .clawker.agent.v1.HealthResponse\x12~\n" +
	"\x17EnableContainerFirewall\x120.clawker.agent.v1.EnableContainerFirewallRequest\x1a1.clawker.agent.v1.EnableContainerFirewallResponse\x12\x81\x01\n" +
	"\x18DisableContainerFirewall\x121.clawker.agent.v1.DisableContainerFirewallRequest\x1a2.clawker.agent.v1.DisableContainerFirewallResponse\x12f\n" +
	"\x0fBypassContainer\x12(.clawker.agent.v1.BypassContainerRequest\x1a).clawker.agent.v1.BypassContainerResponse\x12l\n" +
	"\x11UnbypassContainer\x12*.clawker.agent.v1.UnbypassContainerRequest\x1a+.clawker.agent.v1.UnbypassContainerResponse\x12o\n" +
	"\x12SyncFirewallRoutes\x12+.clawker.agent.v1.SyncFirewallRoutesRequest\x1a,.clawker.agent.v1.SyncFirewallRoutesResponse\x12c\n" +
	"\x0eUpdateDnsCache\x12'.clawker.agent.v1.UpdateDnsCacheRequest\x1a(.clawker.agent.v1.UpdateDnsCacheResponse\x12l\n" +
	"\x11GarbageCollectDns\x12*.clawker.agent.v1.GarbageCollectDnsRequest\x1a+.clawker.agent.v1.GarbageCollectDnsResponse\x12f\n" +
	"\x0fLookupContainer\x12(.clawker.agent.v1.LookupContainerRequest\x1a).clawker.agent.v1.LookupContainerResponse\x12f\n" +
	"\x0fResolveHostname\x12(.clawker.agent.v1.ResolveHostnameRequest\x1a).clawker.agent.v1.ResolveHostnameResponseB=Z;github.com/schmitthub/clawker/internal/clawkerd/protocol/v1b\x06proto3"

var (
	file_v1_controlplane_proto_rawDescOnce sync.Once
	file_v1_controlplane_proto_rawDescData []byte
)

func file_v1_controlplane_proto_rawDescGZIP() []byte {
	file_v1_controlplane_proto_rawDescOnce.Do(func() {
		file_v1_controlplane_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_controlplane_proto_rawDesc), len(file_v1_controlplane_proto_rawDesc)))
	})
	return file_v1_controlplane_proto_rawDescData
}

var file_v1_controlplane_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_v1_controlplane_proto_goTypes = []any{
	(*ContainerFirewallConfig)(nil),          // 0: clawker.agent.v1.ContainerFirewallConfig
	(*Route)(nil),                            // 1: clawker.agent.v1.Route
	(*ContainerConfigSnapshot)(nil),          // 2: clawker.agent.v1.ContainerConfigSnapshot
	(*HealthRequest)(nil),                    // 3: clawker.agent.v1.HealthRequest
	(*HealthResponse)(nil),                   // 4: clawker.agent.v1.HealthResponse
	(*EnableContainerFirewallRequest)(nil),   // 5: clawker.agent.v1.EnableContainerFirewallRequest
	(*EnableContainerFirewallResponse)(nil),  // 6: clawker.agent.v1.EnableContainerFirewallResponse
	(*DisableContainerFirewallRequest)(nil),  // 7: clawker.agent.v1.DisableContainerFirewallRequest
	(*DisableContainerFirewallResponse)(nil), // 8: clawker.agent.v1.DisableContainerFirewallResponse
	(*BypassContainerRequest)(nil),           // 9: clawker.agent.v1.BypassContainerRequest
	(*BypassContainerResponse)(nil),          // 10: clawker.agent.v1.BypassContainerResponse
	(*UnbypassContainerRequest)(nil),         // 11: clawker.agent.v1.UnbypassContainerRequest
	(*UnbypassContainerResponse)(nil),        // 12: clawker.agent.v1.UnbypassContainerResponse
	(*SyncFirewallRoutesRequest)(nil),        // 13: clawker.agent.v1.SyncFirewallRoutesRequest
	(*SyncFirewallRoutesResponse)(nil),       // 14: clawker.agent.v1.SyncFirewallRoutesResponse
	(*UpdateDnsCacheRequest)(nil),            // 15: clawker.agent.v1.UpdateDnsCacheRequest
	(*UpdateDnsCacheResponse)(nil),           // 16: clawker.agent.v1.UpdateDnsCacheResponse
	(*GarbageCollectDnsRequest)(nil),         // 17: clawker.agent.v1.GarbageCollectDnsRequest
	(*GarbageCollectDnsResponse)(nil),        // 18: clawker.agent.v1.GarbageCollectDnsResponse
	(*LookupContainerRequest)(nil),           // 19: clawker.agent.v1.LookupContainerRequest
	(*LookupContainerResponse)(nil),          // 20: clawker.agent.v1.LookupContainerResponse
	(*ResolveHostnameRequest)(nil),           // 21: clawker.agent.v1.ResolveHostnameRequest
	(*ResolveHostnameResponse)(nil),          // 22: clawker.agent.v1.ResolveHostnameResponse
}
var file_v1_controlplane_proto_depIdxs = []int32{
	0,  // 0: clawker.agent.v1.EnableContainerFirewallRequest.config:type_name -> clawker.agent.v1.ContainerFirewallConfig
	1,  // 1: clawker.agent.v1.SyncFirewallRoutesRequest.routes:type_name -> clawker.agent.v1.Route
	2,  // 2: clawker.agent.v1.LookupContainerResponse.config:type_name -> clawker.agent.v1.ContainerConfigSnapshot
	3,  // 3: clawker.agent.v1.ControlPlaneService.Health:input_type -> clawker.agent.v1.HealthRequest
	5,  // 4: clawker.agent.v1.ControlPlaneService.EnableContainerFirewall:input_type -> clawker.agent.v1.EnableContainerFirewallRequest
	7,  // 5: clawker.agent.v1.ControlPlaneService.DisableContainerFirewall:input_type -> clawker.agent.v1.DisableContainerFirewallRequest
	9,  // 6: clawker.agent.v1.ControlPlaneService.BypassContainer:input_type -> clawker.agent.v1.BypassContainerRequest
	11, // 7: clawker.agent.v1.ControlPlaneService.UnbypassContainer:input_type -> clawker.agent.v1.UnbypassContainerRequest
	13, // 8: clawker.agent.v1.ControlPlaneService.SyncFirewallRoutes:input_type -> clawker.agent.v1.SyncFirewallRoutesRequest
	15, // 9: clawker.agent.v1.ControlPlaneService.UpdateDnsCache:input_type -> clawker.agent.v1.UpdateDnsCacheRequest
	17, // 10: clawker.agent.v1.ControlPlaneService.GarbageCollectDns:input_type -> clawker.agent.v1.GarbageCollectDnsRequest
	19, // 11: clawker.agent.v1.ControlPlaneService.LookupContainer:input_type -> clawker.agent.v1.LookupContainerRequest
	21, // 12: clawker.agent.v1.ControlPlaneService.ResolveHostname:input_type -> clawker.agent.v1.ResolveHostnameRequest
	4,  // 13: clawker.agent.v1.ControlPlaneService.Health:output_type -> clawker.agent.v1.HealthResponse
	6,  // 14: clawker.agent.v1.ControlPlaneService.EnableContainerFirewall:output_type -> clawker.agent.v1.EnableContainerFirewallResponse
	8,  // 15: clawker.agent.v1.ControlPlaneService.DisableContainerFirewall:output_type -> clawker.agent.v1.DisableContainerFirewallResponse
	10, // 16: clawker.agent.v1.ControlPlaneService.BypassContainer:output_type -> clawker.agent.v1.BypassContainerResponse
	12, // 17: clawker.agent.v1.ControlPlaneService.UnbypassContainer:output_type -> clawker.agent.v1.UnbypassContainerResponse
	14, // 18: clawker.agent.v1.ControlPlaneService.SyncFirewallRoutes:output_type -> clawker.agent.v1.SyncFirewallRoutesResponse
	16, // 19: clawker.agent.v1.ControlPlaneService.UpdateDnsCache:output_type -> clawker.agent.v1.UpdateDnsCacheResponse
	18, // 20: clawker.agent.v1.ControlPlaneService.GarbageCollectDns:output_type -> clawker.agent.v1.GarbageCollectDnsResponse
	20, // 21: clawker.agent.v1.ControlPlaneService.LookupContainer:output_type -> clawker.agent.v1.LookupContainerResponse
	22, // 22: clawker.agent.v1.ControlPlaneService.ResolveHostname:output_type -> clawker.agent.v1.ResolveHostnameResponse
	13, // [13:23] is the sub-list for method output_type
	3,  // [3:13] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_v1_controlplane_proto_init() }
func file_v1_controlplane_proto_init() {
	if File_v1_controlplane_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_controlplane_proto_rawDesc), len(file_v1_controlplane_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_controlplane_proto_goTypes,
		DependencyIndexes: file_v1_controlplane_proto_depIdxs,
		MessageInfos:      file_v1_controlplane_proto_msgTypes,
	}.Build()
	File_v1_controlplane_proto = out.File
	file_v1_controlplane_proto_goTypes = nil
	file_v1_controlplane_proto_depIdxs = nil
}
