// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/schmitthub/clawker/internal/controlplane/agent"
	"sync"
)

// Ensure, that ContainerInspectorMock does implement agent.ContainerInspector.
// If this is not the case, regenerate this file with moq.
var _ agent.ContainerInspector = &ContainerInspectorMock{}

// ContainerInspectorMock is a mock implementation of agent.ContainerInspector.
//
//	func TestSomethingThatUsesContainerInspector(t *testing.T) {
//
//		// make and configure a mocked agent.ContainerInspector
//		mockedContainerInspector := &ContainerInspectorMock{
//			InspectFunc: func(ctx context.Context, containerID string) (agent.ContainerInfo, error) {
//				panic("mock out the Inspect method")
//			},
//		}
//
//		// use mockedContainerInspector in code that requires agent.ContainerInspector
//		// and then make assertions.
//
//	}
type ContainerInspectorMock struct {
	// InspectFunc mocks the Inspect method.
	InspectFunc func(ctx context.Context, containerID string) (agent.ContainerInfo, error)

	// calls tracks calls to the methods.
	calls struct {
		// Inspect holds details about calls to the Inspect method.
		Inspect []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ContainerID is the containerID argument value.
			ContainerID string
		}
	}
	lockInspect sync.RWMutex
}

// Inspect calls InspectFunc.
func (mock *ContainerInspectorMock) Inspect(ctx context.Context, containerID string) (agent.ContainerInfo, error) {
	if mock.InspectFunc == nil {
		panic("ContainerInspectorMock.InspectFunc: method is nil but ContainerInspector.Inspect was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		ContainerID string
	}{
		Ctx:         ctx,
		ContainerID: containerID,
	}
	mock.lockInspect.Lock()
	mock.calls.Inspect = append(mock.calls.Inspect, callInfo)
	mock.lockInspect.Unlock()
	return mock.InspectFunc(ctx, containerID)
}

// InspectCalls gets all the calls that were made to Inspect.
// Check the length with:
//
//	len(mockedContainerInspector.InspectCalls())
func (mock *ContainerInspectorMock) InspectCalls() []struct {
	Ctx         context.Context
	ContainerID string
} {
	var calls []struct {
		Ctx         context.Context
		ContainerID string
	}
	mock.lockInspect.RLock()
	calls = mock.calls.Inspect
	mock.lockInspect.RUnlock()
	return calls
}
