// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/schmitthub/clawker/internal/controlplane/informer"
	"sync"
)

// Ensure, that InterfaceMock does implement informer.Interface.
// If this is not the case, regenerate this file with moq.
var _ informer.Interface = &InterfaceMock{}

// InterfaceMock is a mock implementation of informer.Interface.
//
//	func TestSomethingThatUsesInterface(t *testing.T) {
//
//		// make and configure a mocked informer.Interface
//		mockedInterface := &InterfaceMock{
//			GetFunc: func(key informer.Key) (informer.Resource, bool) {
//				panic("mock out the Get method")
//			},
//			HistoryFunc: func(key informer.Key) []informer.Transition {
//				panic("mock out the History method")
//			},
//			IncomingFunc: func(key informer.Key, relKind string) []informer.Resource {
//				panic("mock out the Incoming method")
//			},
//			LinkRelationFunc: func(ctx context.Context, rel informer.Relation, t informer.Transition) error {
//				panic("mock out the LinkRelation method")
//			},
//			ListFunc: func(f informer.Filter) []informer.Resource {
//				panic("mock out the List method")
//			},
//			NeighborsFunc: func(key informer.Key, relKind string) []informer.Resource {
//				panic("mock out the Neighbors method")
//			},
//			PatchFunc: func(ctx context.Context, key informer.Key, fn func(*informer.Resource), t informer.Transition) error {
//				panic("mock out the Patch method")
//			},
//			RemoveFunc: func(ctx context.Context, key informer.Key, t informer.Transition) error {
//				panic("mock out the Remove method")
//			},
//			StatsFunc: func() informer.Stats {
//				panic("mock out the Stats method")
//			},
//			SubscribeFunc: func(f informer.Filter) ([]informer.Resource, <-chan informer.Delta, func()) {
//				panic("mock out the Subscribe method")
//			},
//			UnlinkRelationFunc: func(ctx context.Context, from informer.Key, to informer.Key, kind string, t informer.Transition) error {
//				panic("mock out the UnlinkRelation method")
//			},
//			UpsertFunc: func(ctx context.Context, r informer.Resource, t informer.Transition) error {
//				panic("mock out the Upsert method")
//			},
//		}
//
//		// use mockedInterface in code that requires informer.Interface
//		// and then make assertions.
//
//	}
type InterfaceMock struct {
	// GetFunc mocks the Get method.
	GetFunc func(key informer.Key) (informer.Resource, bool)

	// HistoryFunc mocks the History method.
	HistoryFunc func(key informer.Key) []informer.Transition

	// IncomingFunc mocks the Incoming method.
	IncomingFunc func(key informer.Key, relKind string) []informer.Resource

	// LinkRelationFunc mocks the LinkRelation method.
	LinkRelationFunc func(ctx context.Context, rel informer.Relation, t informer.Transition) error

	// ListFunc mocks the List method.
	ListFunc func(f informer.Filter) []informer.Resource

	// NeighborsFunc mocks the Neighbors method.
	NeighborsFunc func(key informer.Key, relKind string) []informer.Resource

	// PatchFunc mocks the Patch method.
	PatchFunc func(ctx context.Context, key informer.Key, fn func(*informer.Resource), t informer.Transition) error

	// RemoveFunc mocks the Remove method.
	RemoveFunc func(ctx context.Context, key informer.Key, t informer.Transition) error

	// StatsFunc mocks the Stats method.
	StatsFunc func() informer.Stats

	// SubscribeFunc mocks the Subscribe method.
	SubscribeFunc func(f informer.Filter) ([]informer.Resource, <-chan informer.Delta, func())

	// UnlinkRelationFunc mocks the UnlinkRelation method.
	UnlinkRelationFunc func(ctx context.Context, from informer.Key, to informer.Key, kind string, t informer.Transition) error

	// UpsertFunc mocks the Upsert method.
	UpsertFunc func(ctx context.Context, r informer.Resource, t informer.Transition) error

	// calls tracks calls to the methods.
	calls struct {
		// Get holds details about calls to the Get method.
		Get []struct {
			// Key is the key argument value.
			Key informer.Key
		}
		// History holds details about calls to the History method.
		History []struct {
			// Key is the key argument value.
			Key informer.Key
		}
		// Incoming holds details about calls to the Incoming method.
		Incoming []struct {
			// Key is the key argument value.
			Key informer.Key
			// RelKind is the relKind argument value.
			RelKind string
		}
		// LinkRelation holds details about calls to the LinkRelation method.
		LinkRelation []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Rel is the rel argument value.
			Rel informer.Relation
			// T is the t argument value.
			T informer.Transition
		}
		// List holds details about calls to the List method.
		List []struct {
			// F is the f argument value.
			F informer.Filter
		}
		// Neighbors holds details about calls to the Neighbors method.
		Neighbors []struct {
			// Key is the key argument value.
			Key informer.Key
			// RelKind is the relKind argument value.
			RelKind string
		}
		// Patch holds details about calls to the Patch method.
		Patch []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key informer.Key
			// Fn is the fn argument value.
			Fn func(*informer.Resource)
			// T is the t argument value.
			T informer.Transition
		}
		// Remove holds details about calls to the Remove method.
		Remove []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key informer.Key
			// T is the t argument value.
			T informer.Transition
		}
		// Stats holds details about calls to the Stats method.
		Stats []struct {
		}
		// Subscribe holds details about calls to the Subscribe method.
		Subscribe []struct {
			// F is the f argument value.
			F informer.Filter
		}
		// UnlinkRelation holds details about calls to the UnlinkRelation method.
		UnlinkRelation []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// From is the from argument value.
			From informer.Key
			// To is the to argument value.
			To informer.Key
			// Kind is the kind argument value.
			Kind string
			// T is the t argument value.
			T informer.Transition
		}
		// Upsert holds details about calls to the Upsert method.
		Upsert []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// R is the r argument value.
			R informer.Resource
			// T is the t argument value.
			T informer.Transition
		}
	}
	lockGet            sync.RWMutex
	lockHistory        sync.RWMutex
	lockIncoming       sync.RWMutex
	lockLinkRelation   sync.RWMutex
	lockList           sync.RWMutex
	lockNeighbors      sync.RWMutex
	lockPatch          sync.RWMutex
	lockRemove         sync.RWMutex
	lockStats          sync.RWMutex
	lockSubscribe      sync.RWMutex
	lockUnlinkRelation sync.RWMutex
	lockUpsert         sync.RWMutex
}

// Get calls GetFunc.
func (mock *InterfaceMock) Get(key informer.Key) (informer.Resource, bool) {
	if mock.GetFunc == nil {
		panic("InterfaceMock.GetFunc: method is nil but Interface.Get was just called")
	}
	callInfo := struct {
		Key informer.Key
	}{
		Key: key,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(key)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedInterface.GetCalls())
func (mock *InterfaceMock) GetCalls() []struct {
	Key informer.Key
} {
	var calls []struct {
		Key informer.Key
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// History calls HistoryFunc.
func (mock *InterfaceMock) History(key informer.Key) []informer.Transition {
	if mock.HistoryFunc == nil {
		panic("InterfaceMock.HistoryFunc: method is nil but Interface.History was just called")
	}
	callInfo := struct {
		Key informer.Key
	}{
		Key: key,
	}
	mock.lockHistory.Lock()
	mock.calls.History = append(mock.calls.History, callInfo)
	mock.lockHistory.Unlock()
	return mock.HistoryFunc(key)
}

// HistoryCalls gets all the calls that were made to History.
// Check the length with:
//
//	len(mockedInterface.HistoryCalls())
func (mock *InterfaceMock) HistoryCalls() []struct {
	Key informer.Key
} {
	var calls []struct {
		Key informer.Key
	}
	mock.lockHistory.RLock()
	calls = mock.calls.History
	mock.lockHistory.RUnlock()
	return calls
}

// Incoming calls IncomingFunc.
func (mock *InterfaceMock) Incoming(key informer.Key, relKind string) []informer.Resource {
	if mock.IncomingFunc == nil {
		panic("InterfaceMock.IncomingFunc: method is nil but Interface.Incoming was just called")
	}
	callInfo := struct {
		Key     informer.Key
		RelKind string
	}{
		Key:     key,
		RelKind: relKind,
	}
	mock.lockIncoming.Lock()
	mock.calls.Incoming = append(mock.calls.Incoming, callInfo)
	mock.lockIncoming.Unlock()
	return mock.IncomingFunc(key, relKind)
}

// IncomingCalls gets all the calls that were made to Incoming.
// Check the length with:
//
//	len(mockedInterface.IncomingCalls())
func (mock *InterfaceMock) IncomingCalls() []struct {
	Key     informer.Key
	RelKind string
} {
	var calls []struct {
		Key     informer.Key
		RelKind string
	}
	mock.lockIncoming.RLock()
	calls = mock.calls.Incoming
	mock.lockIncoming.RUnlock()
	return calls
}

// LinkRelation calls LinkRelationFunc.
func (mock *InterfaceMock) LinkRelation(ctx context.Context, rel informer.Relation, t informer.Transition) error {
	if mock.LinkRelationFunc == nil {
		panic("InterfaceMock.LinkRelationFunc: method is nil but Interface.LinkRelation was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Rel informer.Relation
		T   informer.Transition
	}{
		Ctx: ctx,
		Rel: rel,
		T:   t,
	}
	mock.lockLinkRelation.Lock()
	mock.calls.LinkRelation = append(mock.calls.LinkRelation, callInfo)
	mock.lockLinkRelation.Unlock()
	return mock.LinkRelationFunc(ctx, rel, t)
}

// LinkRelationCalls gets all the calls that were made to LinkRelation.
// Check the length with:
//
//	len(mockedInterface.LinkRelationCalls())
func (mock *InterfaceMock) LinkRelationCalls() []struct {
	Ctx context.Context
	Rel informer.Relation
	T   informer.Transition
} {
	var calls []struct {
		Ctx context.Context
		Rel informer.Relation
		T   informer.Transition
	}
	mock.lockLinkRelation.RLock()
	calls = mock.calls.LinkRelation
	mock.lockLinkRelation.RUnlock()
	return calls
}

// List calls ListFunc.
func (mock *InterfaceMock) List(f informer.Filter) []informer.Resource {
	if mock.ListFunc == nil {
		panic("InterfaceMock.ListFunc: method is nil but Interface.List was just called")
	}
	callInfo := struct {
		F informer.Filter
	}{
		F: f,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	return mock.ListFunc(f)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//
//	len(mockedInterface.ListCalls())
func (mock *InterfaceMock) ListCalls() []struct {
	F informer.Filter
} {
	var calls []struct {
		F informer.Filter
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}

// Neighbors calls NeighborsFunc.
func (mock *InterfaceMock) Neighbors(key informer.Key, relKind string) []informer.Resource {
	if mock.NeighborsFunc == nil {
		panic("InterfaceMock.NeighborsFunc: method is nil but Interface.Neighbors was just called")
	}
	callInfo := struct {
		Key     informer.Key
		RelKind string
	}{
		Key:     key,
		RelKind: relKind,
	}
	mock.lockNeighbors.Lock()
	mock.calls.Neighbors = append(mock.calls.Neighbors, callInfo)
	mock.lockNeighbors.Unlock()
	return mock.NeighborsFunc(key, relKind)
}

// NeighborsCalls gets all the calls that were made to Neighbors.
// Check the length with:
//
//	len(mockedInterface.NeighborsCalls())
func (mock *InterfaceMock) NeighborsCalls() []struct {
	Key     informer.Key
	RelKind string
} {
	var calls []struct {
		Key     informer.Key
		RelKind string
	}
	mock.lockNeighbors.RLock()
	calls = mock.calls.Neighbors
	mock.lockNeighbors.RUnlock()
	return calls
}

// Patch calls PatchFunc.
func (mock *InterfaceMock) Patch(ctx context.Context, key informer.Key, fn func(*informer.Resource), t informer.Transition) error {
	if mock.PatchFunc == nil {
		panic("InterfaceMock.PatchFunc: method is nil but Interface.Patch was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Key informer.Key
		Fn  func(*informer.Resource)
		T   informer.Transition
	}{
		Ctx: ctx,
		Key: key,
		Fn:  fn,
		T:   t,
	}
	mock.lockPatch.Lock()
	mock.calls.Patch = append(mock.calls.Patch, callInfo)
	mock.lockPatch.Unlock()
	return mock.PatchFunc(ctx, key, fn, t)
}

// PatchCalls gets all the calls that were made to Patch.
// Check the length with:
//
//	len(mockedInterface.PatchCalls())
func (mock *InterfaceMock) PatchCalls() []struct {
	Ctx context.Context
	Key informer.Key
	Fn  func(*informer.Resource)
	T   informer.Transition
} {
	var calls []struct {
		Ctx context.Context
		Key informer.Key
		Fn  func(*informer.Resource)
		T   informer.Transition
	}
	mock.lockPatch.RLock()
	calls = mock.calls.Patch
	mock.lockPatch.RUnlock()
	return calls
}

// Remove calls RemoveFunc.
func (mock *InterfaceMock) Remove(ctx context.Context, key informer.Key, t informer.Transition) error {
	if mock.RemoveFunc == nil {
		panic("InterfaceMock.RemoveFunc: method is nil but Interface.Remove was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Key informer.Key
		T   informer.Transition
	}{
		Ctx: ctx,
		Key: key,
		T:   t,
	}
	mock.lockRemove.Lock()
	mock.calls.Remove = append(mock.calls.Remove, callInfo)
	mock.lockRemove.Unlock()
	return mock.RemoveFunc(ctx, key, t)
}

// RemoveCalls gets all the calls that were made to Remove.
// Check the length with:
//
//	len(mockedInterface.RemoveCalls())
func (mock *InterfaceMock) RemoveCalls() []struct {
	Ctx context.Context
	Key informer.Key
	T   informer.Transition
} {
	var calls []struct {
		Ctx context.Context
		Key informer.Key
		T   informer.Transition
	}
	mock.lockRemove.RLock()
	calls = mock.calls.Remove
	mock.lockRemove.RUnlock()
	return calls
}

// Stats calls StatsFunc.
func (mock *InterfaceMock) Stats() informer.Stats {
	if mock.StatsFunc == nil {
		panic("InterfaceMock.StatsFunc: method is nil but Interface.Stats was just called")
	}
	callInfo := struct {
	}{}
	mock.lockStats.Lock()
	mock.calls.Stats = append(mock.calls.Stats, callInfo)
	mock.lockStats.Unlock()
	return mock.StatsFunc()
}

// StatsCalls gets all the calls that were made to Stats.
// Check the length with:
//
//	len(mockedInterface.StatsCalls())
func (mock *InterfaceMock) StatsCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockStats.RLock()
	calls = mock.calls.Stats
	mock.lockStats.RUnlock()
	return calls
}

// Subscribe calls SubscribeFunc.
func (mock *InterfaceMock) Subscribe(f informer.Filter) ([]informer.Resource, <-chan informer.Delta, func()) {
	if mock.SubscribeFunc == nil {
		panic("InterfaceMock.SubscribeFunc: method is nil but Interface.Subscribe was just called")
	}
	callInfo := struct {
		F informer.Filter
	}{
		F: f,
	}
	mock.lockSubscribe.Lock()
	mock.calls.Subscribe = append(mock.calls.Subscribe, callInfo)
	mock.lockSubscribe.Unlock()
	return mock.SubscribeFunc(f)
}

// SubscribeCalls gets all the calls that were made to Subscribe.
// Check the length with:
//
//	len(mockedInterface.SubscribeCalls())
func (mock *InterfaceMock) SubscribeCalls() []struct {
	F informer.Filter
} {
	var calls []struct {
		F informer.Filter
	}
	mock.lockSubscribe.RLock()
	calls = mock.calls.Subscribe
	mock.lockSubscribe.RUnlock()
	return calls
}

// UnlinkRelation calls UnlinkRelationFunc.
func (mock *InterfaceMock) UnlinkRelation(ctx context.Context, from informer.Key, to informer.Key, kind string, t informer.Transition) error {
	if mock.UnlinkRelationFunc == nil {
		panic("InterfaceMock.UnlinkRelationFunc: method is nil but Interface.UnlinkRelation was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		From informer.Key
		To   informer.Key
		Kind string
		T    informer.Transition
	}{
		Ctx:  ctx,
		From: from,
		To:   to,
		Kind: kind,
		T:    t,
	}
	mock.lockUnlinkRelation.Lock()
	mock.calls.UnlinkRelation = append(mock.calls.UnlinkRelation, callInfo)
	mock.lockUnlinkRelation.Unlock()
	return mock.UnlinkRelationFunc(ctx, from, to, kind, t)
}

// UnlinkRelationCalls gets all the calls that were made to UnlinkRelation.
// Check the length with:
//
//	len(mockedInterface.UnlinkRelationCalls())
func (mock *InterfaceMock) UnlinkRelationCalls() []struct {
	Ctx  context.Context
	From informer.Key
	To   informer.Key
	Kind string
	T    informer.Transition
} {
	var calls []struct {
		Ctx  context.Context
		From informer.Key
		To   informer.Key
		Kind string
		T    informer.Transition
	}
	mock.lockUnlinkRelation.RLock()
	calls = mock.calls.UnlinkRelation
	mock.lockUnlinkRelation.RUnlock()
	return calls
}

// Upsert calls UpsertFunc.
func (mock *InterfaceMock) Upsert(ctx context.Context, r informer.Resource, t informer.Transition) error {
	if mock.UpsertFunc == nil {
		panic("InterfaceMock.UpsertFunc: method is nil but Interface.Upsert was just called")
	}
	callInfo := struct {
		Ctx context.Context
		R   informer.Resource
		T   informer.Transition
	}{
		Ctx: ctx,
		R:   r,
		T:   t,
	}
	mock.lockUpsert.Lock()
	mock.calls.Upsert = append(mock.calls.Upsert, callInfo)
	mock.lockUpsert.Unlock()
	return mock.UpsertFunc(ctx, r, t)
}

// UpsertCalls gets all the calls that were made to Upsert.
// Check the length with:
//
//	len(mockedInterface.UpsertCalls())
func (mock *InterfaceMock) UpsertCalls() []struct {
	Ctx context.Context
	R   informer.Resource
	T   informer.Transition
} {
	var calls []struct {
		Ctx context.Context
		R   informer.Resource
		T   informer.Transition
	}
	mock.lockUpsert.RLock()
	calls = mock.calls.Upsert
	mock.lockUpsert.RUnlock()
	return calls
}
