// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package controlplanetest

import (
	"github.com/schmitthub/clawker/internal/controlplane"
	"net"
	"sync"
)

// Ensure, that ControlPlaneServiceMock does implement controlplane.ControlPlaneService.
// If this is not the case, regenerate this file with moq.
var _ controlplane.ControlPlaneService = &ControlPlaneServiceMock{}

// ControlPlaneServiceMock is a mock implementation of controlplane.ControlPlaneService.
//
//	func TestSomethingThatUsesControlPlaneService(t *testing.T) {
//
//		// make and configure a mocked controlplane.ControlPlaneService
//		mockedControlPlaneService := &ControlPlaneServiceMock{
//			GetAgentFunc: func(containerID string) *controlplane.AgentConnection {
//				panic("mock out the GetAgent method")
//			},
//			IsRegisteredFunc: func(containerID string) bool {
//				panic("mock out the IsRegistered method")
//			},
//			ServeFunc: func(lis net.Listener) error {
//				panic("mock out the Serve method")
//			},
//			StopFunc: func()  {
//				panic("mock out the Stop method")
//			},
//		}
//
//		// use mockedControlPlaneService in code that requires controlplane.ControlPlaneService
//		// and then make assertions.
//
//	}
type ControlPlaneServiceMock struct {
	// GetAgentFunc mocks the GetAgent method.
	GetAgentFunc func(containerID string) *controlplane.AgentConnection

	// IsRegisteredFunc mocks the IsRegistered method.
	IsRegisteredFunc func(containerID string) bool

	// ServeFunc mocks the Serve method.
	ServeFunc func(lis net.Listener) error

	// StopFunc mocks the Stop method.
	StopFunc func()

	// calls tracks calls to the methods.
	calls struct {
		// GetAgent holds details about calls to the GetAgent method.
		GetAgent []struct {
			// ContainerID is the containerID argument value.
			ContainerID string
		}
		// IsRegistered holds details about calls to the IsRegistered method.
		IsRegistered []struct {
			// ContainerID is the containerID argument value.
			ContainerID string
		}
		// Serve holds details about calls to the Serve method.
		Serve []struct {
			// Lis is the lis argument value.
			Lis net.Listener
		}
		// Stop holds details about calls to the Stop method.
		Stop []struct {
		}
	}
	lockGetAgent     sync.RWMutex
	lockIsRegistered sync.RWMutex
	lockServe        sync.RWMutex
	lockStop         sync.RWMutex
}

// GetAgent calls GetAgentFunc.
func (mock *ControlPlaneServiceMock) GetAgent(containerID string) *controlplane.AgentConnection {
	if mock.GetAgentFunc == nil {
		panic("ControlPlaneServiceMock.GetAgentFunc: method is nil but ControlPlaneService.GetAgent was just called")
	}
	callInfo := struct {
		ContainerID string
	}{
		ContainerID: containerID,
	}
	mock.lockGetAgent.Lock()
	mock.calls.GetAgent = append(mock.calls.GetAgent, callInfo)
	mock.lockGetAgent.Unlock()
	return mock.GetAgentFunc(containerID)
}

// GetAgentCalls gets all the calls that were made to GetAgent.
// Check the length with:
//
//	len(mockedControlPlaneService.GetAgentCalls())
func (mock *ControlPlaneServiceMock) GetAgentCalls() []struct {
	ContainerID string
} {
	var calls []struct {
		ContainerID string
	}
	mock.lockGetAgent.RLock()
	calls = mock.calls.GetAgent
	mock.lockGetAgent.RUnlock()
	return calls
}

// IsRegistered calls IsRegisteredFunc.
func (mock *ControlPlaneServiceMock) IsRegistered(containerID string) bool {
	if mock.IsRegisteredFunc == nil {
		panic("ControlPlaneServiceMock.IsRegisteredFunc: method is nil but ControlPlaneService.IsRegistered was just called")
	}
	callInfo := struct {
		ContainerID string
	}{
		ContainerID: containerID,
	}
	mock.lockIsRegistered.Lock()
	mock.calls.IsRegistered = append(mock.calls.IsRegistered, callInfo)
	mock.lockIsRegistered.Unlock()
	return mock.IsRegisteredFunc(containerID)
}

// IsRegisteredCalls gets all the calls that were made to IsRegistered.
// Check the length with:
//
//	len(mockedControlPlaneService.IsRegisteredCalls())
func (mock *ControlPlaneServiceMock) IsRegisteredCalls() []struct {
	ContainerID string
} {
	var calls []struct {
		ContainerID string
	}
	mock.lockIsRegistered.RLock()
	calls = mock.calls.IsRegistered
	mock.lockIsRegistered.RUnlock()
	return calls
}

// Serve calls ServeFunc.
func (mock *ControlPlaneServiceMock) Serve(lis net.Listener) error {
	if mock.ServeFunc == nil {
		panic("ControlPlaneServiceMock.ServeFunc: method is nil but ControlPlaneService.Serve was just called")
	}
	callInfo := struct {
		Lis net.Listener
	}{
		Lis: lis,
	}
	mock.lockServe.Lock()
	mock.calls.Serve = append(mock.calls.Serve, callInfo)
	mock.lockServe.Unlock()
	return mock.ServeFunc(lis)
}

// ServeCalls gets all the calls that were made to Serve.
// Check the length with:
//
//	len(mockedControlPlaneService.ServeCalls())
func (mock *ControlPlaneServiceMock) ServeCalls() []struct {
	Lis net.Listener
} {
	var calls []struct {
		Lis net.Listener
	}
	mock.lockServe.RLock()
	calls = mock.calls.Serve
	mock.lockServe.RUnlock()
	return calls
}

// Stop calls StopFunc.
func (mock *ControlPlaneServiceMock) Stop() {
	if mock.StopFunc == nil {
		panic("ControlPlaneServiceMock.StopFunc: method is nil but ControlPlaneService.Stop was just called")
	}
	callInfo := struct {
	}{}
	mock.lockStop.Lock()
	mock.calls.Stop = append(mock.calls.Stop, callInfo)
	mock.lockStop.Unlock()
	mock.StopFunc()
}

// StopCalls gets all the calls that were made to Stop.
// Check the length with:
//
//	len(mockedControlPlaneService.StopCalls())
func (mock *ControlPlaneServiceMock) StopCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockStop.RLock()
	calls = mock.calls.Stop
	mock.lockStop.RUnlock()
	return calls
}
