// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"github.com/schmitthub/clawker/internal/project"
	"sync"
)

// Ensure, that RegistryMock does implement project.Registry.
// If this is not the case, regenerate this file with moq.
var _ project.Registry = &RegistryMock{}

// RegistryMock is a mock implementation of project.Registry.
//
//	func TestSomethingThatUsesRegistry(t *testing.T) {
//
//		// make and configure a mocked project.Registry
//		mockedRegistry := &RegistryMock{
//			CurrentRootFunc: func() (string, error) {
//				panic("mock out the CurrentRoot method")
//			},
//			ProjectByRootFunc: func(root string) (project.ProjectEntry, bool, error) {
//				panic("mock out the ProjectByRoot method")
//			},
//			ProjectsFunc: func() ([]project.ProjectEntry, error) {
//				panic("mock out the Projects method")
//			},
//			RegisterFunc: func(displayName string, rootDir string) (project.ProjectEntry, error) {
//				panic("mock out the Register method")
//			},
//			RegisterWorktreeFunc: func(projectRoot string, branch string, path string) error {
//				panic("mock out the RegisterWorktree method")
//			},
//			RemoveByRootFunc: func(root string) error {
//				panic("mock out the RemoveByRoot method")
//			},
//			ResolveRootFunc: func(cwd string) (string, error) {
//				panic("mock out the ResolveRoot method")
//			},
//			UnregisterWorktreeFunc: func(projectRoot string, branch string) error {
//				panic("mock out the UnregisterWorktree method")
//			},
//			UpdateFunc: func(entry project.ProjectEntry) (project.ProjectEntry, error) {
//				panic("mock out the Update method")
//			},
//		}
//
//		// use mockedRegistry in code that requires project.Registry
//		// and then make assertions.
//
//	}
type RegistryMock struct {
	// CurrentRootFunc mocks the CurrentRoot method.
	CurrentRootFunc func() (string, error)

	// ProjectByRootFunc mocks the ProjectByRoot method.
	ProjectByRootFunc func(root string) (project.ProjectEntry, bool, error)

	// ProjectsFunc mocks the Projects method.
	ProjectsFunc func() ([]project.ProjectEntry, error)

	// RegisterFunc mocks the Register method.
	RegisterFunc func(displayName string, rootDir string) (project.ProjectEntry, error)

	// RegisterWorktreeFunc mocks the RegisterWorktree method.
	RegisterWorktreeFunc func(projectRoot string, branch string, path string) error

	// RemoveByRootFunc mocks the RemoveByRoot method.
	RemoveByRootFunc func(root string) error

	// ResolveRootFunc mocks the ResolveRoot method.
	ResolveRootFunc func(cwd string) (string, error)

	// UnregisterWorktreeFunc mocks the UnregisterWorktree method.
	UnregisterWorktreeFunc func(projectRoot string, branch string) error

	// UpdateFunc mocks the Update method.
	UpdateFunc func(entry project.ProjectEntry) (project.ProjectEntry, error)

	// calls tracks calls to the methods.
	calls struct {
		// CurrentRoot holds details about calls to the CurrentRoot method.
		CurrentRoot []struct {
		}
		// ProjectByRoot holds details about calls to the ProjectByRoot method.
		ProjectByRoot []struct {
			// Root is the root argument value.
			Root string
		}
		// Projects holds details about calls to the Projects method.
		Projects []struct {
		}
		// Register holds details about calls to the Register method.
		Register []struct {
			// DisplayName is the displayName argument value.
			DisplayName string
			// RootDir is the rootDir argument value.
			RootDir string
		}
		// RegisterWorktree holds details about calls to the RegisterWorktree method.
		RegisterWorktree []struct {
			// ProjectRoot is the projectRoot argument value.
			ProjectRoot string
			// Branch is the branch argument value.
			Branch string
			// Path is the path argument value.
			Path string
		}
		// RemoveByRoot holds details about calls to the RemoveByRoot method.
		RemoveByRoot []struct {
			// Root is the root argument value.
			Root string
		}
		// ResolveRoot holds details about calls to the ResolveRoot method.
		ResolveRoot []struct {
			// Cwd is the cwd argument value.
			Cwd string
		}
		// UnregisterWorktree holds details about calls to the UnregisterWorktree method.
		UnregisterWorktree []struct {
			// ProjectRoot is the projectRoot argument value.
			ProjectRoot string
			// Branch is the branch argument value.
			Branch string
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// Entry is the entry argument value.
			Entry project.ProjectEntry
		}
	}
	lockCurrentRoot        sync.RWMutex
	lockProjectByRoot      sync.RWMutex
	lockProjects           sync.RWMutex
	lockRegister           sync.RWMutex
	lockRegisterWorktree   sync.RWMutex
	lockRemoveByRoot       sync.RWMutex
	lockResolveRoot        sync.RWMutex
	lockUnregisterWorktree sync.RWMutex
	lockUpdate             sync.RWMutex
}

// CurrentRoot calls CurrentRootFunc.
func (mock *RegistryMock) CurrentRoot() (string, error) {
	if mock.CurrentRootFunc == nil {
		panic("RegistryMock.CurrentRootFunc: method is nil but Registry.CurrentRoot was just called")
	}
	callInfo := struct {
	}{}
	mock.lockCurrentRoot.Lock()
	mock.calls.CurrentRoot = append(mock.calls.CurrentRoot, callInfo)
	mock.lockCurrentRoot.Unlock()
	return mock.CurrentRootFunc()
}

// CurrentRootCalls gets all the calls that were made to CurrentRoot.
// Check the length with:
//
//	len(mockedRegistry.CurrentRootCalls())
func (mock *RegistryMock) CurrentRootCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockCurrentRoot.RLock()
	calls = mock.calls.CurrentRoot
	mock.lockCurrentRoot.RUnlock()
	return calls
}

// ProjectByRoot calls ProjectByRootFunc.
func (mock *RegistryMock) ProjectByRoot(root string) (project.ProjectEntry, bool, error) {
	if mock.ProjectByRootFunc == nil {
		panic("RegistryMock.ProjectByRootFunc: method is nil but Registry.ProjectByRoot was just called")
	}
	callInfo := struct {
		Root string
	}{
		Root: root,
	}
	mock.lockProjectByRoot.Lock()
	mock.calls.ProjectByRoot = append(mock.calls.ProjectByRoot, callInfo)
	mock.lockProjectByRoot.Unlock()
	return mock.ProjectByRootFunc(root)
}

// ProjectByRootCalls gets all the calls that were made to ProjectByRoot.
// Check the length with:
//
//	len(mockedRegistry.ProjectByRootCalls())
func (mock *RegistryMock) ProjectByRootCalls() []struct {
	Root string
} {
	var calls []struct {
		Root string
	}
	mock.lockProjectByRoot.RLock()
	calls = mock.calls.ProjectByRoot
	mock.lockProjectByRoot.RUnlock()
	return calls
}

// Projects calls ProjectsFunc.
func (mock *RegistryMock) Projects() ([]project.ProjectEntry, error) {
	if mock.ProjectsFunc == nil {
		panic("RegistryMock.ProjectsFunc: method is nil but Registry.Projects was just called")
	}
	callInfo := struct {
	}{}
	mock.lockProjects.Lock()
	mock.calls.Projects = append(mock.calls.Projects, callInfo)
	mock.lockProjects.Unlock()
	return mock.ProjectsFunc()
}

// ProjectsCalls gets all the calls that were made to Projects.
// Check the length with:
//
//	len(mockedRegistry.ProjectsCalls())
func (mock *RegistryMock) ProjectsCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockProjects.RLock()
	calls = mock.calls.Projects
	mock.lockProjects.RUnlock()
	return calls
}

// Register calls RegisterFunc.
func (mock *RegistryMock) Register(displayName string, rootDir string) (project.ProjectEntry, error) {
	if mock.RegisterFunc == nil {
		panic("RegistryMock.RegisterFunc: method is nil but Registry.Register was just called")
	}
	callInfo := struct {
		DisplayName string
		RootDir     string
	}{
		DisplayName: displayName,
		RootDir:     rootDir,
	}
	mock.lockRegister.Lock()
	mock.calls.Register = append(mock.calls.Register, callInfo)
	mock.lockRegister.Unlock()
	return mock.RegisterFunc(displayName, rootDir)
}

// RegisterCalls gets all the calls that were made to Register.
// Check the length with:
//
//	len(mockedRegistry.RegisterCalls())
func (mock *RegistryMock) RegisterCalls() []struct {
	DisplayName string
	RootDir     string
} {
	var calls []struct {
		DisplayName string
		RootDir     string
	}
	mock.lockRegister.RLock()
	calls = mock.calls.Register
	mock.lockRegister.RUnlock()
	return calls
}

// RegisterWorktree calls RegisterWorktreeFunc.
func (mock *RegistryMock) RegisterWorktree(projectRoot string, branch string, path string) error {
	if mock.RegisterWorktreeFunc == nil {
		panic("RegistryMock.RegisterWorktreeFunc: method is nil but Registry.RegisterWorktree was just called")
	}
	callInfo := struct {
		ProjectRoot string
		Branch      string
		Path        string
	}{
		ProjectRoot: projectRoot,
		Branch:      branch,
		Path:        path,
	}
	mock.lockRegisterWorktree.Lock()
	mock.calls.RegisterWorktree = append(mock.calls.RegisterWorktree, callInfo)
	mock.lockRegisterWorktree.Unlock()
	return mock.RegisterWorktreeFunc(projectRoot, branch, path)
}

// RegisterWorktreeCalls gets all the calls that were made to RegisterWorktree.
// Check the length with:
//
//	len(mockedRegistry.RegisterWorktreeCalls())
func (mock *RegistryMock) RegisterWorktreeCalls() []struct {
	ProjectRoot string
	Branch      string
	Path        string
} {
	var calls []struct {
		ProjectRoot string
		Branch      string
		Path        string
	}
	mock.lockRegisterWorktree.RLock()
	calls = mock.calls.RegisterWorktree
	mock.lockRegisterWorktree.RUnlock()
	return calls
}

// RemoveByRoot calls RemoveByRootFunc.
func (mock *RegistryMock) RemoveByRoot(root string) error {
	if mock.RemoveByRootFunc == nil {
		panic("RegistryMock.RemoveByRootFunc: method is nil but Registry.RemoveByRoot was just called")
	}
	callInfo := struct {
		Root string
	}{
		Root: root,
	}
	mock.lockRemoveByRoot.Lock()
	mock.calls.RemoveByRoot = append(mock.calls.RemoveByRoot, callInfo)
	mock.lockRemoveByRoot.Unlock()
	return mock.RemoveByRootFunc(root)
}

// RemoveByRootCalls gets all the calls that were made to RemoveByRoot.
// Check the length with:
//
//	len(mockedRegistry.RemoveByRootCalls())
func (mock *RegistryMock) RemoveByRootCalls() []struct {
	Root string
} {
	var calls []struct {
		Root string
	}
	mock.lockRemoveByRoot.RLock()
	calls = mock.calls.RemoveByRoot
	mock.lockRemoveByRoot.RUnlock()
	return calls
}

// ResolveRoot calls ResolveRootFunc.
func (mock *RegistryMock) ResolveRoot(cwd string) (string, error) {
	if mock.ResolveRootFunc == nil {
		panic("RegistryMock.ResolveRootFunc: method is nil but Registry.ResolveRoot was just called")
	}
	callInfo := struct {
		Cwd string
	}{
		Cwd: cwd,
	}
	mock.lockResolveRoot.Lock()
	mock.calls.ResolveRoot = append(mock.calls.ResolveRoot, callInfo)
	mock.lockResolveRoot.Unlock()
	return mock.ResolveRootFunc(cwd)
}

// ResolveRootCalls gets all the calls that were made to ResolveRoot.
// Check the length with:
//
//	len(mockedRegistry.ResolveRootCalls())
func (mock *RegistryMock) ResolveRootCalls() []struct {
	Cwd string
} {
	var calls []struct {
		Cwd string
	}
	mock.lockResolveRoot.RLock()
	calls = mock.calls.ResolveRoot
	mock.lockResolveRoot.RUnlock()
	return calls
}

// UnregisterWorktree calls UnregisterWorktreeFunc.
func (mock *RegistryMock) UnregisterWorktree(projectRoot string, branch string) error {
	if mock.UnregisterWorktreeFunc == nil {
		panic("RegistryMock.UnregisterWorktreeFunc: method is nil but Registry.UnregisterWorktree was just called")
	}
	callInfo := struct {
		ProjectRoot string
		Branch      string
	}{
		ProjectRoot: projectRoot,
		Branch:      branch,
	}
	mock.lockUnregisterWorktree.Lock()
	mock.calls.UnregisterWorktree = append(mock.calls.UnregisterWorktree, callInfo)
	mock.lockUnregisterWorktree.Unlock()
	return mock.UnregisterWorktreeFunc(projectRoot, branch)
}

// UnregisterWorktreeCalls gets all the calls that were made to UnregisterWorktree.
// Check the length with:
//
//	len(mockedRegistry.UnregisterWorktreeCalls())
func (mock *RegistryMock) UnregisterWorktreeCalls() []struct {
	ProjectRoot string
	Branch      string
} {
	var calls []struct {
		ProjectRoot string
		Branch      string
	}
	mock.lockUnregisterWorktree.RLock()
	calls = mock.calls.UnregisterWorktree
	mock.lockUnregisterWorktree.RUnlock()
	return calls
}

// Update calls UpdateFunc.
func (mock *RegistryMock) Update(entry project.ProjectEntry) (project.ProjectEntry, error) {
	if mock.UpdateFunc == nil {
		panic("RegistryMock.UpdateFunc: method is nil but Registry.Update was just called")
	}
	callInfo := struct {
		Entry project.ProjectEntry
	}{
		Entry: entry,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	return mock.UpdateFunc(entry)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//
//	len(mockedRegistry.UpdateCalls())
func (mock *RegistryMock) UpdateCalls() []struct {
	Entry project.ProjectEntry
} {
	var calls []struct {
		Entry project.ProjectEntry
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}
