// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: agent/v1/agent.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentService_Connect_FullMethodName = "/clawker.agent.v1.AgentService/Connect"
	AgentService_Events_FullMethodName  = "/clawker.agent.v1.AgentService/Events"
)

// AgentServiceClient is the client API for AgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AgentService is the gRPC surface clawkerd (the per-container agent
// daemon) calls on the control plane.
//
// Transport: mTLS over TCP on the CP's clawker-net agent listener.
// Server requires a client cert chained to the CLI CA — clawkerd
// presents the per-agent leaf cert that the CLI minted at AnnounceAgent
// time.
//
// Authorization: bearer access token issued by Hydra to a dedicated
// agent OAuth2 client whose scopes are validated by the CP's auth
// interceptor.
//
// Topology: clawkerd is gRPC-client only; CP serves. The Connect stream
// IS the agent's lifetime command channel — single mTLS connection per
// agent, all clawkerd-initiated.
type AgentServiceClient interface {
	// Connect opens the agent's lifetime command channel. clawkerd sends
	// a ConnectRequest at startup (agent_name + PKCE verifier); CP
	// authenticates the channel-bound identity via slot consume plus a
	// cross-check on the peer cert CN, peer IP, and container labels,
	// pins the agent in the registry, then server-streams Command
	// messages for the lifetime of the agent. First message after auth
	// is Welcome (config delivery). Subsequent messages carry commands
	// as they are issued (B5+ adds payload variants). Stream closes on
	// eviction (container dies → dockerevents → cancel) or clawkerd
	// disconnect.
	Connect(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Command], error)
	// Events streams runtime telemetry from clawkerd to CP: log scrapes,
	// error events, monitoring data. Client-streaming; CP returns a
	// single EventAck on close. Identity-bound — caller must already be
	// registered via Connect (AgentIdentityInterceptor enforces). Stub
	// in this branch; B5 defines the Event payload shape and CP-side
	// consumer alongside the first concrete event type.
	Events(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Event, EventAck], error)
}

type agentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentServiceClient(cc grpc.ClientConnInterface) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) Connect(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Command], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[0], AgentService_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ConnectRequest, Command]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_ConnectClient = grpc.ServerStreamingClient[Command]

func (c *agentServiceClient) Events(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Event, EventAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[1], AgentService_Events_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Event, EventAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_EventsClient = grpc.ClientStreamingClient[Event, EventAck]

// AgentServiceServer is the server API for AgentService service.
// All implementations must embed UnimplementedAgentServiceServer
// for forward compatibility.
//
// AgentService is the gRPC surface clawkerd (the per-container agent
// daemon) calls on the control plane.
//
// Transport: mTLS over TCP on the CP's clawker-net agent listener.
// Server requires a client cert chained to the CLI CA — clawkerd
// presents the per-agent leaf cert that the CLI minted at AnnounceAgent
// time.
//
// Authorization: bearer access token issued by Hydra to a dedicated
// agent OAuth2 client whose scopes are validated by the CP's auth
// interceptor.
//
// Topology: clawkerd is gRPC-client only; CP serves. The Connect stream
// IS the agent's lifetime command channel — single mTLS connection per
// agent, all clawkerd-initiated.
type AgentServiceServer interface {
	// Connect opens the agent's lifetime command channel. clawkerd sends
	// a ConnectRequest at startup (agent_name + PKCE verifier); CP
	// authenticates the channel-bound identity via slot consume plus a
	// cross-check on the peer cert CN, peer IP, and container labels,
	// pins the agent in the registry, then server-streams Command
	// messages for the lifetime of the agent. First message after auth
	// is Welcome (config delivery). Subsequent messages carry commands
	// as they are issued (B5+ adds payload variants). Stream closes on
	// eviction (container dies → dockerevents → cancel) or clawkerd
	// disconnect.
	Connect(*ConnectRequest, grpc.ServerStreamingServer[Command]) error
	// Events streams runtime telemetry from clawkerd to CP: log scrapes,
	// error events, monitoring data. Client-streaming; CP returns a
	// single EventAck on close. Identity-bound — caller must already be
	// registered via Connect (AgentIdentityInterceptor enforces). Stub
	// in this branch; B5 defines the Event payload shape and CP-side
	// consumer alongside the first concrete event type.
	Events(grpc.ClientStreamingServer[Event, EventAck]) error
	mustEmbedUnimplementedAgentServiceServer()
}

// UnimplementedAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentServiceServer struct{}

func (UnimplementedAgentServiceServer) Connect(*ConnectRequest, grpc.ServerStreamingServer[Command]) error {
	return status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedAgentServiceServer) Events(grpc.ClientStreamingServer[Event, EventAck]) error {
	return status.Error(codes.Unimplemented, "method Events not implemented")
}
func (UnimplementedAgentServiceServer) mustEmbedUnimplementedAgentServiceServer() {}
func (UnimplementedAgentServiceServer) testEmbeddedByValue()                      {}

// UnsafeAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServiceServer will
// result in compilation errors.
type UnsafeAgentServiceServer interface {
	mustEmbedUnimplementedAgentServiceServer()
}

func RegisterAgentServiceServer(s grpc.ServiceRegistrar, srv AgentServiceServer) {
	// If the following call panics, it indicates UnimplementedAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentService_ServiceDesc, srv)
}

func _AgentService_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ConnectRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentServiceServer).Connect(m, &grpc.GenericServerStream[ConnectRequest, Command]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_ConnectServer = grpc.ServerStreamingServer[Command]

func _AgentService_Events_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentServiceServer).Events(&grpc.GenericServerStream[Event, EventAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_EventsServer = grpc.ClientStreamingServer[Event, EventAck]

// AgentService_ServiceDesc is the grpc.ServiceDesc for AgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "clawker.agent.v1.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _AgentService_Connect_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Events",
			Handler:       _AgentService_Events_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "agent/v1/agent.proto",
}
