// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"github.com/schmitthub/clawker/internal/controlplane/agentslots"
	"sync"
)

// Ensure, that RegistryMock does implement agentslots.Registry.
// If this is not the case, regenerate this file with moq.
var _ agentslots.Registry = &RegistryMock{}

// RegistryMock is a mock implementation of agentslots.Registry.
//
//	func TestSomethingThatUsesRegistry(t *testing.T) {
//
//		// make and configure a mocked agentslots.Registry
//		mockedRegistry := &RegistryMock{
//			ConsumeFunc: func(agentName string, verifier string) (*agentslots.Slot, error) {
//				panic("mock out the Consume method")
//			},
//			LenFunc: func() int {
//				panic("mock out the Len method")
//			},
//			ReserveFunc: func(slot agentslots.Slot) error {
//				panic("mock out the Reserve method")
//			},
//			StopFunc: func()  {
//				panic("mock out the Stop method")
//			},
//		}
//
//		// use mockedRegistry in code that requires agentslots.Registry
//		// and then make assertions.
//
//	}
type RegistryMock struct {
	// ConsumeFunc mocks the Consume method.
	ConsumeFunc func(agentName string, verifier string) (*agentslots.Slot, error)

	// LenFunc mocks the Len method.
	LenFunc func() int

	// ReserveFunc mocks the Reserve method.
	ReserveFunc func(slot agentslots.Slot) error

	// StopFunc mocks the Stop method.
	StopFunc func()

	// calls tracks calls to the methods.
	calls struct {
		// Consume holds details about calls to the Consume method.
		Consume []struct {
			// AgentName is the agentName argument value.
			AgentName string
			// Verifier is the verifier argument value.
			Verifier string
		}
		// Len holds details about calls to the Len method.
		Len []struct {
		}
		// Reserve holds details about calls to the Reserve method.
		Reserve []struct {
			// Slot is the slot argument value.
			Slot agentslots.Slot
		}
		// Stop holds details about calls to the Stop method.
		Stop []struct {
		}
	}
	lockConsume sync.RWMutex
	lockLen     sync.RWMutex
	lockReserve sync.RWMutex
	lockStop    sync.RWMutex
}

// Consume calls ConsumeFunc.
func (mock *RegistryMock) Consume(agentName string, verifier string) (*agentslots.Slot, error) {
	if mock.ConsumeFunc == nil {
		panic("RegistryMock.ConsumeFunc: method is nil but Registry.Consume was just called")
	}
	callInfo := struct {
		AgentName string
		Verifier  string
	}{
		AgentName: agentName,
		Verifier:  verifier,
	}
	mock.lockConsume.Lock()
	mock.calls.Consume = append(mock.calls.Consume, callInfo)
	mock.lockConsume.Unlock()
	return mock.ConsumeFunc(agentName, verifier)
}

// ConsumeCalls gets all the calls that were made to Consume.
// Check the length with:
//
//	len(mockedRegistry.ConsumeCalls())
func (mock *RegistryMock) ConsumeCalls() []struct {
	AgentName string
	Verifier  string
} {
	var calls []struct {
		AgentName string
		Verifier  string
	}
	mock.lockConsume.RLock()
	calls = mock.calls.Consume
	mock.lockConsume.RUnlock()
	return calls
}

// Len calls LenFunc.
func (mock *RegistryMock) Len() int {
	if mock.LenFunc == nil {
		panic("RegistryMock.LenFunc: method is nil but Registry.Len was just called")
	}
	callInfo := struct {
	}{}
	mock.lockLen.Lock()
	mock.calls.Len = append(mock.calls.Len, callInfo)
	mock.lockLen.Unlock()
	return mock.LenFunc()
}

// LenCalls gets all the calls that were made to Len.
// Check the length with:
//
//	len(mockedRegistry.LenCalls())
func (mock *RegistryMock) LenCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockLen.RLock()
	calls = mock.calls.Len
	mock.lockLen.RUnlock()
	return calls
}

// Reserve calls ReserveFunc.
func (mock *RegistryMock) Reserve(slot agentslots.Slot) error {
	if mock.ReserveFunc == nil {
		panic("RegistryMock.ReserveFunc: method is nil but Registry.Reserve was just called")
	}
	callInfo := struct {
		Slot agentslots.Slot
	}{
		Slot: slot,
	}
	mock.lockReserve.Lock()
	mock.calls.Reserve = append(mock.calls.Reserve, callInfo)
	mock.lockReserve.Unlock()
	return mock.ReserveFunc(slot)
}

// ReserveCalls gets all the calls that were made to Reserve.
// Check the length with:
//
//	len(mockedRegistry.ReserveCalls())
func (mock *RegistryMock) ReserveCalls() []struct {
	Slot agentslots.Slot
} {
	var calls []struct {
		Slot agentslots.Slot
	}
	mock.lockReserve.RLock()
	calls = mock.calls.Reserve
	mock.lockReserve.RUnlock()
	return calls
}

// Stop calls StopFunc.
func (mock *RegistryMock) Stop() {
	if mock.StopFunc == nil {
		panic("RegistryMock.StopFunc: method is nil but Registry.Stop was just called")
	}
	callInfo := struct {
	}{}
	mock.lockStop.Lock()
	mock.calls.Stop = append(mock.calls.Stop, callInfo)
	mock.lockStop.Unlock()
	mock.StopFunc()
}

// StopCalls gets all the calls that were made to Stop.
// Check the length with:
//
//	len(mockedRegistry.StopCalls())
func (mock *RegistryMock) StopCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockStop.RLock()
	calls = mock.calls.Stop
	mock.lockStop.RUnlock()
	return calls
}
