// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"github.com/schmitthub/clawker/internal/state"
	"sync"
	"time"
)

// Ensure, that StateStoreMock does implement state.StateStore.
// If this is not the case, regenerate this file with moq.
var _ state.StateStore = &StateStoreMock{}

// StateStoreMock is a mock implementation of state.StateStore.
//
//	func TestSomethingThatUsesStateStore(t *testing.T) {
//
//		// make and configure a mocked state.StateStore
//		mockedStateStore := &StateStoreMock{
//			CheckedAtFunc: func() time.Time {
//				panic("mock out the CheckedAt method")
//			},
//			LastSeenChangelogFunc: func() string {
//				panic("mock out the LastSeenChangelog method")
//			},
//			LatestVersionFunc: func() string {
//				panic("mock out the LatestVersion method")
//			},
//			RecordUpdateCheckFunc: func(checkedAt time.Time, latestVersion string) error {
//				panic("mock out the RecordUpdateCheck method")
//			},
//			SetLastSeenChangelogFunc: func(version string) error {
//				panic("mock out the SetLastSeenChangelog method")
//			},
//		}
//
//		// use mockedStateStore in code that requires state.StateStore
//		// and then make assertions.
//
//	}
type StateStoreMock struct {
	// CheckedAtFunc mocks the CheckedAt method.
	CheckedAtFunc func() time.Time

	// LastSeenChangelogFunc mocks the LastSeenChangelog method.
	LastSeenChangelogFunc func() string

	// LatestVersionFunc mocks the LatestVersion method.
	LatestVersionFunc func() string

	// RecordUpdateCheckFunc mocks the RecordUpdateCheck method.
	RecordUpdateCheckFunc func(checkedAt time.Time, latestVersion string) error

	// SetLastSeenChangelogFunc mocks the SetLastSeenChangelog method.
	SetLastSeenChangelogFunc func(version string) error

	// calls tracks calls to the methods.
	calls struct {
		// CheckedAt holds details about calls to the CheckedAt method.
		CheckedAt []struct {
		}
		// LastSeenChangelog holds details about calls to the LastSeenChangelog method.
		LastSeenChangelog []struct {
		}
		// LatestVersion holds details about calls to the LatestVersion method.
		LatestVersion []struct {
		}
		// RecordUpdateCheck holds details about calls to the RecordUpdateCheck method.
		RecordUpdateCheck []struct {
			// CheckedAt is the checkedAt argument value.
			CheckedAt time.Time
			// LatestVersion is the latestVersion argument value.
			LatestVersion string
		}
		// SetLastSeenChangelog holds details about calls to the SetLastSeenChangelog method.
		SetLastSeenChangelog []struct {
			// Version is the version argument value.
			Version string
		}
	}
	lockCheckedAt            sync.RWMutex
	lockLastSeenChangelog    sync.RWMutex
	lockLatestVersion        sync.RWMutex
	lockRecordUpdateCheck    sync.RWMutex
	lockSetLastSeenChangelog sync.RWMutex
}

// CheckedAt calls CheckedAtFunc.
func (mock *StateStoreMock) CheckedAt() time.Time {
	if mock.CheckedAtFunc == nil {
		panic("StateStoreMock.CheckedAtFunc: method is nil but StateStore.CheckedAt was just called")
	}
	callInfo := struct {
	}{}
	mock.lockCheckedAt.Lock()
	mock.calls.CheckedAt = append(mock.calls.CheckedAt, callInfo)
	mock.lockCheckedAt.Unlock()
	return mock.CheckedAtFunc()
}

// CheckedAtCalls gets all the calls that were made to CheckedAt.
// Check the length with:
//
//	len(mockedStateStore.CheckedAtCalls())
func (mock *StateStoreMock) CheckedAtCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockCheckedAt.RLock()
	calls = mock.calls.CheckedAt
	mock.lockCheckedAt.RUnlock()
	return calls
}

// LastSeenChangelog calls LastSeenChangelogFunc.
func (mock *StateStoreMock) LastSeenChangelog() string {
	if mock.LastSeenChangelogFunc == nil {
		panic("StateStoreMock.LastSeenChangelogFunc: method is nil but StateStore.LastSeenChangelog was just called")
	}
	callInfo := struct {
	}{}
	mock.lockLastSeenChangelog.Lock()
	mock.calls.LastSeenChangelog = append(mock.calls.LastSeenChangelog, callInfo)
	mock.lockLastSeenChangelog.Unlock()
	return mock.LastSeenChangelogFunc()
}

// LastSeenChangelogCalls gets all the calls that were made to LastSeenChangelog.
// Check the length with:
//
//	len(mockedStateStore.LastSeenChangelogCalls())
func (mock *StateStoreMock) LastSeenChangelogCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockLastSeenChangelog.RLock()
	calls = mock.calls.LastSeenChangelog
	mock.lockLastSeenChangelog.RUnlock()
	return calls
}

// LatestVersion calls LatestVersionFunc.
func (mock *StateStoreMock) LatestVersion() string {
	if mock.LatestVersionFunc == nil {
		panic("StateStoreMock.LatestVersionFunc: method is nil but StateStore.LatestVersion was just called")
	}
	callInfo := struct {
	}{}
	mock.lockLatestVersion.Lock()
	mock.calls.LatestVersion = append(mock.calls.LatestVersion, callInfo)
	mock.lockLatestVersion.Unlock()
	return mock.LatestVersionFunc()
}

// LatestVersionCalls gets all the calls that were made to LatestVersion.
// Check the length with:
//
//	len(mockedStateStore.LatestVersionCalls())
func (mock *StateStoreMock) LatestVersionCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockLatestVersion.RLock()
	calls = mock.calls.LatestVersion
	mock.lockLatestVersion.RUnlock()
	return calls
}

// RecordUpdateCheck calls RecordUpdateCheckFunc.
func (mock *StateStoreMock) RecordUpdateCheck(checkedAt time.Time, latestVersion string) error {
	if mock.RecordUpdateCheckFunc == nil {
		panic("StateStoreMock.RecordUpdateCheckFunc: method is nil but StateStore.RecordUpdateCheck was just called")
	}
	callInfo := struct {
		CheckedAt     time.Time
		LatestVersion string
	}{
		CheckedAt:     checkedAt,
		LatestVersion: latestVersion,
	}
	mock.lockRecordUpdateCheck.Lock()
	mock.calls.RecordUpdateCheck = append(mock.calls.RecordUpdateCheck, callInfo)
	mock.lockRecordUpdateCheck.Unlock()
	return mock.RecordUpdateCheckFunc(checkedAt, latestVersion)
}

// RecordUpdateCheckCalls gets all the calls that were made to RecordUpdateCheck.
// Check the length with:
//
//	len(mockedStateStore.RecordUpdateCheckCalls())
func (mock *StateStoreMock) RecordUpdateCheckCalls() []struct {
	CheckedAt     time.Time
	LatestVersion string
} {
	var calls []struct {
		CheckedAt     time.Time
		LatestVersion string
	}
	mock.lockRecordUpdateCheck.RLock()
	calls = mock.calls.RecordUpdateCheck
	mock.lockRecordUpdateCheck.RUnlock()
	return calls
}

// SetLastSeenChangelog calls SetLastSeenChangelogFunc.
func (mock *StateStoreMock) SetLastSeenChangelog(version string) error {
	if mock.SetLastSeenChangelogFunc == nil {
		panic("StateStoreMock.SetLastSeenChangelogFunc: method is nil but StateStore.SetLastSeenChangelog was just called")
	}
	callInfo := struct {
		Version string
	}{
		Version: version,
	}
	mock.lockSetLastSeenChangelog.Lock()
	mock.calls.SetLastSeenChangelog = append(mock.calls.SetLastSeenChangelog, callInfo)
	mock.lockSetLastSeenChangelog.Unlock()
	return mock.SetLastSeenChangelogFunc(version)
}

// SetLastSeenChangelogCalls gets all the calls that were made to SetLastSeenChangelog.
// Check the length with:
//
//	len(mockedStateStore.SetLastSeenChangelogCalls())
func (mock *StateStoreMock) SetLastSeenChangelogCalls() []struct {
	Version string
} {
	var calls []struct {
		Version string
	}
	mock.lockSetLastSeenChangelog.RLock()
	calls = mock.calls.SetLastSeenChangelog
	mock.lockSetLastSeenChangelog.RUnlock()
	return calls
}
