# Generated by Clawker - Claude Container Orchestration
# Base image for Claude Code 2.99.99-test on buildpack-deps:bookworm-scm

# Builder stage for callback-forwarder
FROM golang:1.25.10-alpine@sha256:8d22e29d960bc50cd025d93d5b7c7d220b1ee9aa7a239b3c8f55a57e987e8d45 AS callback-forwarder-builder
WORKDIR /build
COPY callback-forwarder.go .
RUN --mount=type=cache,target=/go/pkg/mod \
    CGO_ENABLED=0 go build -ldflags="-s -w" -o callback-forwarder callback-forwarder.go

# Builder stage for clawker-socket-server (unified socket forwarding)
FROM golang:1.25.10-alpine@sha256:8d22e29d960bc50cd025d93d5b7c7d220b1ee9aa7a239b3c8f55a57e987e8d45 AS socket-server-builder
WORKDIR /build
COPY clawker-socket-server.go .
RUN --mount=type=cache,target=/go/pkg/mod \
    CGO_ENABLED=0 go build -ldflags="-s -w" -o clawker-socket-server clawker-socket-server.go

FROM buildpack-deps:bookworm-scm AS final

ARG TZ=UTC
ENV TZ="$TZ"





# Install system packages

RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,target=/var/lib/apt,sharing=locked \
    apt-get update && apt-get install -y --no-install-recommends \
    less \
    procps \
    sudo \
    fzf \
    gcc \
    git \
    libc6-dev \
    zsh \
    make \
    man-db \
    unzip \
    gnupg2 \
    iproute2 \
    dnsutils \
    aggregate \
    jq \
    nano \
    vim \
    wget \
    curl \
    gh \
    locales \
    locales-all \
    && true




# Install Docker CLI (not daemon - we use host's Docker via socket mount)

RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,target=/var/lib/apt,sharing=locked \
    install -m 0755 -d /etc/apt/keyrings && \
    curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc && \
    chmod a+r /etc/apt/keyrings/docker.asc && \
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian $(. /etc/os-release && echo \"$VERSION_CODENAME\") stable" > /etc/apt/sources.list.d/docker.list && \
    apt-get update && \
    apt-get install -y --no-install-recommends docker-ce-cli docker-buildx-plugin docker-compose-plugin


# Node.js (≥22.10) trusts the OS CA bundle. Set globally — applies to root
# (build-time RUN steps) AND to the unprivileged ${USERNAME} (Claude Code
# hooks, user `npm`/`npx`). When the firewall MITM CA is added to
# /etc/ssl/certs via update-ca-certificates (clawker's late root block),
# `fetch()` and TLS calls from any process transparently trust clawker's
# interception cert.
ENV NODE_USE_SYSTEM_CA=1

# Root-global Node.js on /usr/local — the baked default for Claude Code's
# hooks/MCP tooling, any root_run / system build step, and the agent's Bash
# tool (all resolve it from ${PATH}). nvm (installed in the post-user_run
# block) is the runtime version-switch tool layered on top; this is the
# stable base.
#
# NODE_VERSION names the LTS *line* (e.g. "24"), not an exact patch; the latest
# patch in that line is resolved per-build from nodejs.org/dist/index.json so
# rebuilds float forward onto security patches (dep-rot rationale: see the nvm
# block below + docs/threat-model.mdx). Integrity is verified on every path:
#   - Debian: prebuilt tarball from nodejs.org/dist, GPG-verified via SHASUMS256.txt.asc.
#   - Alpine x86_64: musl prebuilt from unofficial-builds.nodejs.org, sha256-verified
#     against that mirror's SHASUMS256.txt (unofficial builds are unsigned — upstream's
#     musl integrity level).
#   - Alpine other arches: source build (./configure + make), GPG-verified against
#     nodejs.org/dist SHASUMS256.txt.
# All paths land node/npm under /usr/local.
ARG NODE_VERSION=24

RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,target=/var/lib/apt,sharing=locked \
    apt-get update && apt-get install -y --no-install-recommends \
        ca-certificates dirmngr xz-utils libatomic1 && \
    NODE_LTS_VERSION=$(curl -sSfL https://nodejs.org/dist/index.json | jq -r --arg ver "$NODE_VERSION" '[.[] | select(.lts != false)] | map(select(.version | startswith("v" + $ver + "."))) | .[0].version' | sed 's/^v//') && \
    { [ -n "$NODE_LTS_VERSION" ] && [ "$NODE_LTS_VERSION" != "null" ]; } || { echo "ERROR: could not resolve Node LTS line ${NODE_VERSION}" >&2; exit 1; } && \
    ARCH= && dpkgArch="$(dpkg --print-architecture)" && \
    case "${dpkgArch##*-}" in \
      amd64) ARCH='x64' ;; \
      arm64) ARCH='arm64' ;; \
      *) echo "ERROR: node prebuilt does not support architecture: $dpkgArch (only amd64 and arm64)" >&2; exit 1 ;; \
    esac && \
    set -ex && \
    export GNUPGHOME="$(mktemp -d)" && \
    for key in \
      5BE8A3F6C8A5C01D106C0AD820B1A390B168D356 \
      DD792F5973C6DE52C432CBDAC77ABFA00DDBF2B7 \
      CC68F5A3106FF448322E48ED27F5E38D5B0A215F \
      8FCCA13FEF1D0C2E91008E09770F7A9A5AE15600 \
      890C08DB8579162FEE0DF9DB8BEAB4DFCF555EF4 \
      C82FA3AE1CBEDC6BE46B9360C43CEC45C17AB93C \
      108F52B48DB57BB0CC439B2997B01419BD92F80A \
      A363A499291CBBC940DD62E41F10027AF002F8B0 \
    ; do \
      { gpg --batch --keyserver hkps://keys.openpgp.org --recv-keys "$key" && gpg --batch --fingerprint "$key"; } || \
      { gpg --batch --keyserver keyserver.ubuntu.com --recv-keys "$key" && gpg --batch --fingerprint "$key"; } ; \
    done && \
    curl -fsSLO --compressed "https://nodejs.org/dist/v$NODE_LTS_VERSION/node-v$NODE_LTS_VERSION-linux-$ARCH.tar.xz" && \
    curl -fsSLO --compressed "https://nodejs.org/dist/v$NODE_LTS_VERSION/SHASUMS256.txt.asc" && \
    gpg --batch --decrypt --output SHASUMS256.txt SHASUMS256.txt.asc && \
    gpgconf --kill all && \
    rm -rf "$GNUPGHOME" && \
    grep " node-v$NODE_LTS_VERSION-linux-$ARCH.tar.xz\$" SHASUMS256.txt | sha256sum -c - && \
    tar -xJf "node-v$NODE_LTS_VERSION-linux-$ARCH.tar.xz" -C /usr/local --strip-components=1 --no-same-owner && \
    rm "node-v$NODE_LTS_VERSION-linux-$ARCH.tar.xz" SHASUMS256.txt.asc SHASUMS256.txt && \
    ln -s /usr/local/bin/node /usr/local/bin/nodejs && \
    node --version && npm --version


# Setup locale
RUN locale-gen en_US.UTF-8




ARG USERNAME=claude

# Setup non-root user

RUN (groupadd --gid 1001 ${USERNAME} 2>/dev/null || groupadd ${USERNAME}) \
    && useradd --uid 1001 --gid ${USERNAME} --shell /bin/zsh --create-home ${USERNAME}


# Create docker group and add user for socket access
RUN groupadd -g 999 docker 2>/dev/null || groupadd docker 2>/dev/null || true && usermod -aG docker ${USERNAME}




# Create workspace, config, runtime, and credential directories with proper permissions.
# .gnupg and .ssh are pre-created so socket mounts don't create root-owned directories.
# .clawker-share is pre-created so the share volume mount inherits correct ownership.
# /run/clawker (bootstrap dir, root-owned 0700 — only clawkerd-as-root reads it) and
# /var/log/clawker (log file, root-owned — clawkerd writes the rotated log as root)
# are pre-created so clawkerd-as-PID-1 doesn't need mkdir at boot. /var/run/clawker
# is chowned to ${USERNAME} below so the user CMD (spawned by clawkerd with a
# privilege drop to ${USERNAME}) can read/write runtime state alongside the ready
# marker that clawkerd-as-root writes; the HEALTHCHECK probe itself runs as root
# (final USER directive at the bottom of this file) and stats the ready marker
# regardless of ownership.
RUN mkdir -p /home/${USERNAME}/.claude /home/${USERNAME}/.clawker-share /home/${USERNAME}/.gnupg /home/${USERNAME}/.ssh /workspace /run/clawker /var/log/clawker /var/run/clawker && \
    chmod 700 /home/${USERNAME}/.gnupg /home/${USERNAME}/.ssh && \
    chown -R ${USERNAME}:${USERNAME} /workspace /home/${USERNAME}/.claude /home/${USERNAME}/.clawker-share /home/${USERNAME}/.gnupg /home/${USERNAME}/.ssh /var/run/clawker

# Persist bash history
RUN SNIPPET="export PROMPT_COMMAND='history -a' && export HISTFILE=/commandhistory/.bash_history" \
    && mkdir /commandhistory \
    && touch /commandhistory/.bash_history \
    && chown -R ${USERNAME} /commandhistory

WORKDIR /workspace

# Install git-delta
ARG GIT_DELTA_VERSION=0.19.1
ARG GIT_DELTA_SHA256_AMD64=3b3064c5e474d120366f5917f54c612bbfd5733a70e5d10988d8028c7c877de9
ARG GIT_DELTA_SHA256_ARM64=1bd252110eafa1065c0798f9e68de0682127408e4b53db79733efa72c53b68bf
RUN --mount=type=cache,target=/tmp/downloads \
    ARCH=$(dpkg --print-architecture) && \
    DEB="git-delta_${GIT_DELTA_VERSION}_${ARCH}.deb" && \
    [ -f "/tmp/downloads/$DEB" ] || wget -O "/tmp/downloads/$DEB" "https://github.com/dandavison/delta/releases/download/${GIT_DELTA_VERSION}/$DEB" && \
    if [ "$ARCH" = "amd64" ]; then EXPECTED_SHA="${GIT_DELTA_SHA256_AMD64}"; \
    elif [ "$ARCH" = "arm64" ]; then EXPECTED_SHA="${GIT_DELTA_SHA256_ARM64}"; \
    else echo "ERROR: git-delta does not support architecture: $ARCH (only amd64 and arm64)" >&2; exit 1; fi && \
    echo "$EXPECTED_SHA  /tmp/downloads/$DEB" | sha256sum -c - && \
    dpkg -i "/tmp/downloads/$DEB"



# Managed enterprise settings (Linux managed path, highest precedence,
# cannot be overridden by user/project settings). REQUIRED — do not
# remove. Claude Code's Bash tool runs `/bin/zsh -c` and sources its own
# shell snapshot AFTER zsh init files, so the snapshot's PATH overrides
# anything `.zshenv` exports; managed-settings.json is the only documented
# enterprise mechanism that injects into that env. Points at `.local/bin`
# (where the claude binary lives); the inherited `${PATH}` carries the root
# `/usr/local` Node install as the floor, so `node` resolves for build-time
# `claude mcp add ...` (inject points, post_init) and the agent's Bash tool.
#
# Stays in early root scope (not the late clawker block) because any
# `claude` invocation in `after_claude_install` / `before_entrypoint`
# inject points reads this at session start — without `.local/bin` here, the
# user's build-time `claude mcp add ...` cannot find the `claude` binary. The
# heredoc body is structural (template-author-edited only), so locking it early
# has negligible cache cost vs the asset bumps in the late block.
RUN mkdir -p /etc/claude-code && cat > /etc/claude-code/managed-settings.json <<EOF
{
  "env": {
    "PATH": "/home/${USERNAME}/.local/bin:${PATH}"
  }
}
EOF

# Switch to non-root user for ENV/WORKDIR resolution. clawkerd (PID 1)
# is invoked as root by Docker — the USER directive only affects
# ENV/WORKDIR/RUN scope below this line. Privilege drop to ${USERNAME}
# happens in the spawn-child via SysProcAttr.Credential when clawkerd
# forks the user CMD on AgentReady; clawkerd itself stays root for log
# rotation, bootstrap reads, eBPF coordination, and Wait4(-1) reaping.
USER ${USERNAME}
ENV CLAWKER_USER=${USERNAME}

# Set static environment (PATH, SHELL, BROWSER — not config-dependent).
# `.local/bin` is load-bearing: Claude Code's installer drops the `claude`
# binary there (symlink to ~/.local/share/claude/versions/...), so without
# this PATH entry the agent itself is not invokable. Side benefit: any
# user_run installer that follows XDG (uv, pip --user, cargo, etc.) lands
# on PATH automatically.
ENV HOME=/home/${USERNAME}
ENV PATH=${HOME}/.local/bin:$PATH


# Set BROWSER so CLI tools (like Claude Code) use host-open for URLs
ENV BROWSER=/usr/local/bin/host-open
# Terminal color defaults; RuntimeEnv may override these based on host capabilities,
# using safe fallback values (xterm-256color, truecolor) rather than passing through host TERM.
ENV TERM=xterm-256color
ENV COLORTERM=truecolor
ENV LANG=en_US.UTF-8
# Tell Claude Code where its config lives — must match the config volume mount.
# CP's generic seed-apply init step places the manifest seeds (statusline,
# .config.json onboarding bypass, settings.json) here on first boot.
ENV CLAUDE_CONFIG_DIR=/home/${USERNAME}/.claude
# Telemetry: pre-configured for otel-collector on clawker-net (requires 'clawker monitor up').
# 'monitor up' also provisions OpenSearch indices + Dashboards via the
# clawker-opensearch-bootstrap one-shot service before the collector starts,
# so records land in templated (not dynamically-mapped) indices.
# Disabled at container creation if monitoring stack is not running; override with agent.env
ENV CLAUDE_CODE_ENABLE_TELEMETRY=1
# Beta gate: span tracing only fires when CLAUDE_CODE_ENHANCED_TELEMETRY_BETA=1
# is also set (per Claude Code docs). With both set, OTEL_TRACES_EXPORTER=otlp
# sends spans via the same OTLP base endpoint below.
ENV CLAUDE_CODE_ENHANCED_TELEMETRY_BETA=1
ENV OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
ENV OTEL_METRICS_EXPORTER=otlp
ENV OTEL_LOGS_EXPORTER=otlp
ENV OTEL_TRACES_EXPORTER=otlp
# Single base endpoint; OTel SDK appends /v1/metrics, /v1/logs, /v1/traces
# per signal. Collector OTLP/HTTP receiver listens on the standard paths.
ENV OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
ENV OTEL_METRICS_INCLUDE_ACCOUNT_UUID=true
ENV OTEL_METRICS_INCLUDE_SESSION_ID=true
ENV OTEL_LOGS_EXPORT_INTERVAL=5000
ENV OTEL_METRIC_EXPORT_INTERVAL=10000
ENV OTEL_LOG_TOOL_DETAILS=1
ENV OTEL_LOG_USER_PROMPTS=1

# zsh env file pre-created so any harness or user step can append to it;
# zsh sources .zshenv on every invocation (interactive and non-interactive).
SHELL ["/bin/zsh", "-o", "pipefail", "-c"]
ARG ZSH_ENV=/home/${USERNAME}/.zshenv
RUN touch ${ZSH_ENV}

ENV SHELL=/bin/zsh



# Use zsh-in-docker to configure plugins and theme
ARG ZSH_IN_DOCKER_VERSION=1.2.1
ARG ZSH_IN_DOCKER_SHA256=0cf15b6f9c63a8103eb33bad87dc4b43fed0e0ad5884dff90f943ee1e868796e
ARG ZSH_THEME=default
RUN wget -O /tmp/zsh-in-docker.sh "https://github.com/deluan/zsh-in-docker/releases/download/v${ZSH_IN_DOCKER_VERSION}/zsh-in-docker.sh" && \
    echo "${ZSH_IN_DOCKER_SHA256}  /tmp/zsh-in-docker.sh" | sha256sum -c - && \
    sh /tmp/zsh-in-docker.sh \
    -t ${ZSH_THEME} \
    -p git \
    -p fzf \
    -a "source /usr/share/doc/fzf/examples/key-bindings.zsh" \
    -a "source /usr/share/doc/fzf/examples/completion.zsh" \
    -a "export PROMPT_COMMAND='history -a' && export HISTFILE=/commandhistory/.bash_history" \
    -a "export TERM=xterm-256color" \
    -x && \
    rm /tmp/zsh-in-docker.sh




# nvm — runtime Node version-switch tool (the baked default node lives on
# /usr/local from the root install in block_1). zsh sources .zshenv on every
# invocation, so nvm is available in interactive and non-interactive shells.
# Install nvm via its canonical installer (nvm-sh). Floated, not pinned: a
# frozen tag rots into an unpatched installer Dependabot can't track (curl|bash,
# not a package) — the failure mode CVE-2026-10796 caused for nvm <=0.40.4. nvm
# itself checksums the Node tarballs it downloads. Rationale: docs/threat-model.mdx.
RUN NVM_LATEST=$(curl -sSfL https://api.github.com/repos/nvm-sh/nvm/releases/latest | jq -r '.tag_name') && \
      { [ -n "$NVM_LATEST" ] && [ "$NVM_LATEST" != "null" ]; } || { echo "ERROR: could not resolve latest nvm release tag" >&2; exit 1; } && \
      curl -sSfL https://raw.githubusercontent.com/nvm-sh/nvm/${NVM_LATEST}/install.sh | PROFILE=${ZSH_ENV} bash

# Claude Code version. Build-only ARG (not ENV — CC's runtime ignores it; only
# the install RUN below consumes it). Default is resolved against the npm
# registry at template-render time, so a fresh CC release (often several a week)
# rolls this value.
#
# MUST stay here, directly above its only consumer. BuildKit invalidates the
# cache at an ARG's DECLARATION line, not at first use — that "first use, not
# definition" rule is the classic (pre-BuildKit) builder's, and Docker 23+
# builds with BuildKit by default. Hoisting this declaration up the stage would
# re-run every layer below it (apt/apk, Node, git-delta, zsh-in-docker, ...) on
# every CC release. Adjacent placement scopes the CC-version cache miss to the
# install layer + the late root block alone.
# Override: clawker build --build-arg CLAUDE_CODE_VERSION=<version>
ARG CLAUDE_CODE_VERSION=2.99.99-test

# Install Claude Code
RUN --mount=type=cache,target=/home/${USERNAME}/.npm \
    curl -fsSL "https://claude.ai/install.sh" | bash -s ${CLAUDE_CODE_VERSION}

# Harness config seeds, staged for first-boot volume initialization (not
# shadowed by the config volume mount). The seed-manifest tells CP's generic
# seed-apply init step how to place each file into the harness config dir
# (paths + apply tokens match internal/consts SeedSubdir/SeedManifestFile and
# controlplane/agent ConfigSeedScript). Stays in the user-scope section so
# inject points and user Copy steps can reference the staged seeds.
COPY --chown=${USERNAME}:${USERNAME} assets/statusline.sh /home/${USERNAME}/.clawker/seed/.claude/statusline.sh
COPY --chown=${USERNAME}:${USERNAME} assets/claude-config.json /home/${USERNAME}/.clawker/seed/.claude/.config.json
COPY --chown=${USERNAME}:${USERNAME} assets/claude-settings.json /home/${USERNAME}/.clawker/seed/.claude/settings.json
RUN cat > /home/${USERNAME}/.clawker/seed-manifest <<'EOF'
copy-if-missing .claude/statusline.sh
copy-if-missing-or-empty .claude/.config.json
json-merge .claude/settings.json
EOF





# Health check for container readiness (checks for ready signal file)
HEALTHCHECK --interval=5s --timeout=3s --start-period=30s --retries=3 \
    CMD test -f /var/run/clawker/ready || exit 1



# Switch back to root: clawkerd is PID 1, runs as root, owns the
# supervisor responsibilities (spawn user CMD with privilege drop,
# forward signals, reap zombies, serve the CP-dialed mTLS listener).
USER root

# --- Begin clawker-managed root assets (consolidated for build-cache locality) ---
# Every COPY/RUN in this block changes with clawker release cadence
# (embedded scripts, agent prompt, firewall CA, clawkerd binary) and writes
# to root-owned paths (/etc/claude-code, /usr/local/bin, /usr/local/share).
# Keeping them at end-of-stage means a clawker bump invalidates ONLY this
# block — apt/apk, git-delta, zsh-in-docker, the harness install blocks,
# harness config seeds all stay cached above. The seeds live in the
# user-scope section (before USER root) so the after_harness_install inject
# point can reference ~/.clawker/seed/ contents. managed-settings.json
# lives in early root scope (before USER ${USERNAME}) — see comment there
# — because any build-time `claude` invocation in user inject points
# reads it at session start and depends on it for PATH augmentation.

# /etc/claude-code is created by the managed-settings.json RUN above; COPY auto-creates intermediates either way.
COPY assets/clawker-agent-prompt.md /etc/claude-code/CLAUDE.md

# Firewall CA cert for TLS inspection. docker build itself runs via host
# network (not through the per-container eBPF firewall), so curl/wget
# steps ABOVE this point don't need the CA — only runtime traffic does.
COPY clawker-ca.crt /usr/local/share/ca-certificates/clawker-firewall-ca.crt
RUN update-ca-certificates
ENV SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
ENV CURL_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt

# Host-proxy and socket-forwarder binaries. Single chmod batches the four files into one layer.
COPY host-open.sh /usr/local/bin/host-open
COPY git-credential-clawker.sh /usr/local/bin/git-credential-clawker
COPY --from=callback-forwarder-builder /build/callback-forwarder /usr/local/bin/callback-forwarder
COPY --from=socket-server-builder /build/clawker-socket-server /usr/local/bin/clawker-socket-server
RUN chmod +x /usr/local/bin/host-open \
             /usr/local/bin/git-credential-clawker \
             /usr/local/bin/callback-forwarder \
             /usr/local/bin/clawker-socket-server

# clawkerd: per-container agent daemon AND PID 1 init. Reads bootstrap
# material, completes the CP-driven Register handshake, serves the
# mTLS Session listener for command dispatch, and supervises the user
# CMD across its lifetime. See cmd/clawkerd for the source + CLAUDE.md.
# Last in the block — every clawker release rolls the binary content,
# so it ends up in its own layer with the smallest possible tail.
COPY --chown=root:root --chmod=755 clawkerd /usr/local/bin/clawkerd
# --- End clawker-managed assets ---

ENTRYPOINT ["/usr/local/bin/clawkerd"]
CMD ["claude"]
